{
  "hash": "d9bcb3ec66fe2f6d83a482049a27d5e2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Policy Brief 1: Strengthening Pesticide Poisoning Surveillance\"\nsubtitle: \"Closing the detection gap between NMC, NHLS, and PIH\"\nauthor: \"D2P Project Team\"\ndate: \"2025-09-05\"\ndate-modified: today\ncategories: [policy, surveillance, decision-makers]\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    number-sections: false\n---\n\n::: {.callout-important icon=false}\n## For Decision-Makers\n\n**Target audience:** Ministerial Advisory Committee (MAC), National Department of Health (NDoH), Provincial Health Leadership, NICD/NHLS leadership.\n\n**Companion briefs:** [Coordination](coordination_policy.qmd) · [Terbufos restriction](terbufos_policy.qmd).\n:::\n\n## 1. Policy question\n\n**Should NDoH invest in automated, multi-source pesticide-poisoning surveillance to close the detection gap between the NMC, NHLS laboratory, and PIH data streams?**\n\n## 2. Public health problem\n\nSouth Africa under-detects pesticide poisoning. Three data streams each see a fraction of the problem; none sees the whole:\n\n- Most cases never appear in NMC.\n- Severe laboratory results do not trigger a public-health alert.\n- The country's largest single source of clinical signal — the Poisons Information Helpline — is not used for surveillance.\n\n## 3. Status quo\n\n::: {.callout-note icon=false collapse=\"true\"}\n## Canonical model parameters (auto-loaded from the [Parameters Hub](../parameters_hub.html))\n\nAll numerical claims in this brief draw from a single CSV — [`amua_import_parameters_v4.csv`](../amua_import_parameters_v4.csv) — rendered in full at the [Parameters Hub](../parameters_hub.html). The headline values below are pulled from that file at render time; **do not edit the numbers in this brief — edit the CSV and re-render**.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hjxrmipiww\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hjxrmipiww table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hjxrmipiww thead, #hjxrmipiww tbody, #hjxrmipiww tfoot, #hjxrmipiww tr, #hjxrmipiww td, #hjxrmipiww th {\n  border-style: none;\n}\n\n#hjxrmipiww p {\n  margin: 0;\n  padding: 0;\n}\n\n#hjxrmipiww .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: small;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hjxrmipiww .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hjxrmipiww .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hjxrmipiww .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hjxrmipiww .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hjxrmipiww .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hjxrmipiww .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hjxrmipiww .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hjxrmipiww .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hjxrmipiww .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hjxrmipiww .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hjxrmipiww .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hjxrmipiww .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hjxrmipiww .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hjxrmipiww .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hjxrmipiww .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hjxrmipiww .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hjxrmipiww .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hjxrmipiww .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hjxrmipiww .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hjxrmipiww .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hjxrmipiww .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hjxrmipiww .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hjxrmipiww .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hjxrmipiww .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hjxrmipiww .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hjxrmipiww .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hjxrmipiww .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hjxrmipiww .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hjxrmipiww .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hjxrmipiww .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hjxrmipiww .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hjxrmipiww .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hjxrmipiww .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hjxrmipiww .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hjxrmipiww .gt_left {\n  text-align: left;\n}\n\n#hjxrmipiww .gt_center {\n  text-align: center;\n}\n\n#hjxrmipiww .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hjxrmipiww .gt_font_normal {\n  font-weight: normal;\n}\n\n#hjxrmipiww .gt_font_bold {\n  font-weight: bold;\n}\n\n#hjxrmipiww .gt_font_italic {\n  font-style: italic;\n}\n\n#hjxrmipiww .gt_super {\n  font-size: 65%;\n}\n\n#hjxrmipiww .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hjxrmipiww .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hjxrmipiww .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hjxrmipiww .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hjxrmipiww .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hjxrmipiww .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hjxrmipiww .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hjxrmipiww .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hjxrmipiww div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal\" style>Headline parameters used in this brief</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Pulled from amua_import_parameters_v4.csv at render time</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Parameter\">Parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Value\">Value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\">Annual NMC pesticide notifications</td>\n<td headers=\"Value\" class=\"gt_row gt_left\">1013</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left gt_striped\">Annual NHLS severe BChE inhibitions (live)</td>\n<td headers=\"Value\" class=\"gt_row gt_left gt_striped\">1779</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\">Annual PIH pesticide-related calls</td>\n<td headers=\"Value\" class=\"gt_row gt_left\">1158</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left gt_striped\">True annual burden (sum, upper bound)</td>\n<td headers=\"Value\" class=\"gt_row gt_left gt_striped\">3950</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\">Headline annual deaths</td>\n<td headers=\"Value\" class=\"gt_row gt_left\">2620</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left gt_striped\">Blended headline morbidity cost per case</td>\n<td headers=\"Value\" class=\"gt_row gt_left gt_striped\">R12,000</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\">Mortality cost per death (human-capital)</td>\n<td headers=\"Value\" class=\"gt_row gt_left\">R1.50 million</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left gt_striped\">Headline annual economic burden</td>\n<td headers=\"Value\" class=\"gt_row gt_left gt_striped\">R2.34 billion</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\">Response efficacy η (base case)</td>\n<td headers=\"Value\" class=\"gt_row gt_left\">0.30</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left gt_striped\">Detection probability — status quo</td>\n<td headers=\"Value\" class=\"gt_row gt_left gt_striped\">0.048</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\">Detection probability — full package</td>\n<td headers=\"Value\" class=\"gt_row gt_left\">0.83</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left gt_striped\">Full Package narrow operating cost / yr</td>\n<td headers=\"Value\" class=\"gt_row gt_left gt_striped\">R237,000</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\">Full Package whole-system operating cost / yr</td>\n<td headers=\"Value\" class=\"gt_row gt_left\">R1.19 million</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Who bears the R2.34B annual burden?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fnqccsvwqq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fnqccsvwqq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fnqccsvwqq thead, #fnqccsvwqq tbody, #fnqccsvwqq tfoot, #fnqccsvwqq tr, #fnqccsvwqq td, #fnqccsvwqq th {\n  border-style: none;\n}\n\n#fnqccsvwqq p {\n  margin: 0;\n  padding: 0;\n}\n\n#fnqccsvwqq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: small;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fnqccsvwqq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fnqccsvwqq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fnqccsvwqq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fnqccsvwqq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fnqccsvwqq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fnqccsvwqq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fnqccsvwqq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fnqccsvwqq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fnqccsvwqq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fnqccsvwqq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fnqccsvwqq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fnqccsvwqq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fnqccsvwqq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fnqccsvwqq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fnqccsvwqq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fnqccsvwqq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fnqccsvwqq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fnqccsvwqq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fnqccsvwqq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fnqccsvwqq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fnqccsvwqq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fnqccsvwqq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fnqccsvwqq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fnqccsvwqq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fnqccsvwqq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fnqccsvwqq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fnqccsvwqq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fnqccsvwqq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fnqccsvwqq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fnqccsvwqq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fnqccsvwqq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fnqccsvwqq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fnqccsvwqq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fnqccsvwqq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fnqccsvwqq .gt_left {\n  text-align: left;\n}\n\n#fnqccsvwqq .gt_center {\n  text-align: center;\n}\n\n#fnqccsvwqq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fnqccsvwqq .gt_font_normal {\n  font-weight: normal;\n}\n\n#fnqccsvwqq .gt_font_bold {\n  font-weight: bold;\n}\n\n#fnqccsvwqq .gt_font_italic {\n  font-style: italic;\n}\n\n#fnqccsvwqq .gt_super {\n  font-size: 65%;\n}\n\n#fnqccsvwqq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fnqccsvwqq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fnqccsvwqq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fnqccsvwqq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fnqccsvwqq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fnqccsvwqq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fnqccsvwqq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fnqccsvwqq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fnqccsvwqq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style>Annual burden by stakeholder (headline scenario, ZAR 2025)</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Each rand of the R2.34B falls on exactly one bearer</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Stakeholder\">Stakeholder</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Value\">Value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Share\">Share</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Stakeholder\" class=\"gt_row gt_left\">NDoH — public hospitals (UPFS ward + ICU + drugs)</td>\n<td headers=\"Value\" class=\"gt_row gt_right\">R70.00 million</td>\n<td headers=\"Share\" class=\"gt_row gt_right\">3%</td></tr>\n    <tr><td headers=\"Stakeholder\" class=\"gt_row gt_left gt_striped\">NHLS — laboratory (BChE, GC-MS, repeat clinical chemistry)</td>\n<td headers=\"Value\" class=\"gt_row gt_right gt_striped\">R10.00 million</td>\n<td headers=\"Share\" class=\"gt_row gt_right gt_striped\">0%</td></tr>\n    <tr><td headers=\"Stakeholder\" class=\"gt_row gt_left\">DALRRD — regulator (no burden-side share by construction)</td>\n<td headers=\"Value\" class=\"gt_row gt_right\">R0</td>\n<td headers=\"Share\" class=\"gt_row gt_right\">0%</td></tr>\n    <tr><td headers=\"Stakeholder\" class=\"gt_row gt_left gt_striped\">Individuals / households — out-of-pocket + lost wages</td>\n<td headers=\"Value\" class=\"gt_row gt_right gt_striped\">R10.00 million</td>\n<td headers=\"Share\" class=\"gt_row gt_right gt_striped\">0%</td></tr>\n    <tr><td headers=\"Stakeholder\" class=\"gt_row gt_left\">Households / wider society — lost lifetime earnings</td>\n<td headers=\"Value\" class=\"gt_row gt_right\">R2.25 billion</td>\n<td headers=\"Share\" class=\"gt_row gt_right\">96%</td></tr>\n    <tr><td headers=\"Stakeholder\" class=\"gt_row gt_left gt_striped\" style=\"font-weight: bold;\">TOTAL</td>\n<td headers=\"Value\" class=\"gt_row gt_right gt_striped\" style=\"font-weight: bold;\">R2.34 billion</td>\n<td headers=\"Share\" class=\"gt_row gt_right gt_striped\" style=\"font-weight: bold;\">100%</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n**Reading the table.** ~96 % of the R2.34B is **mortality, borne by households and the wider economy** as lost lifetime earnings (1,500 deaths × R1.5M human-capital, undiscounted; sensitivity: R1.05M at 3 % discount). The directly-budgeted health-sector share is **R80M** (NDoH ~R70M hospital + NHLS ~R10M lab) — modest in absolute terms, but it is the only column that appears on a departmental budget line. DALRRD bears **R0** of the *burden* side by construction: their cost sits on the *intervention* side (enforcement, recalls, registration action).\n\n\nFor the full sourced parameter set (CFR by severity, UPFS tariffs, per-option costs, induced-demand components, DALY monetisation, NMB), see the **[Parameters Hub](../parameters_hub.html)**. For the v2 → v3 critical appraisal, see [`parameter_appraisal.qmd`](../parameter_appraisal.qmd).\n\n### Canonical option costs (Detect · Act · Restrict)\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hgaqiqroxp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hgaqiqroxp table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hgaqiqroxp thead, #hgaqiqroxp tbody, #hgaqiqroxp tfoot, #hgaqiqroxp tr, #hgaqiqroxp td, #hgaqiqroxp th {\n  border-style: none;\n}\n\n#hgaqiqroxp p {\n  margin: 0;\n  padding: 0;\n}\n\n#hgaqiqroxp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: small;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hgaqiqroxp .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hgaqiqroxp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hgaqiqroxp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hgaqiqroxp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hgaqiqroxp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hgaqiqroxp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hgaqiqroxp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hgaqiqroxp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hgaqiqroxp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hgaqiqroxp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hgaqiqroxp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hgaqiqroxp .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hgaqiqroxp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hgaqiqroxp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hgaqiqroxp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hgaqiqroxp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hgaqiqroxp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hgaqiqroxp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hgaqiqroxp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hgaqiqroxp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hgaqiqroxp .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hgaqiqroxp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hgaqiqroxp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hgaqiqroxp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hgaqiqroxp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hgaqiqroxp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hgaqiqroxp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hgaqiqroxp .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hgaqiqroxp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hgaqiqroxp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hgaqiqroxp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hgaqiqroxp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hgaqiqroxp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hgaqiqroxp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hgaqiqroxp .gt_left {\n  text-align: left;\n}\n\n#hgaqiqroxp .gt_center {\n  text-align: center;\n}\n\n#hgaqiqroxp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hgaqiqroxp .gt_font_normal {\n  font-weight: normal;\n}\n\n#hgaqiqroxp .gt_font_bold {\n  font-weight: bold;\n}\n\n#hgaqiqroxp .gt_font_italic {\n  font-style: italic;\n}\n\n#hgaqiqroxp .gt_super {\n  font-size: 65%;\n}\n\n#hgaqiqroxp .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hgaqiqroxp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hgaqiqroxp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hgaqiqroxp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hgaqiqroxp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hgaqiqroxp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hgaqiqroxp .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hgaqiqroxp .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hgaqiqroxp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style>Option costs by stage (Detect · Act · Restrict)</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>All values pulled from amua_import_parameters_v3.csv at render time</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Option\">Option</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Cost\">Cost</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Notes\">Notes</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"3\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Detect\">Detect</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"Detect  Option\" class=\"gt_row gt_left\">S1 — NHLS→NMC IT feed (operating)</td>\n<td headers=\"Detect  Cost\" class=\"gt_row gt_right\">R60,000</td>\n<td headers=\"Detect  Notes\" class=\"gt_row gt_left\">0.05 FTE analyst + QA</td></tr>\n    <tr><td headers=\"Detect  Option\" class=\"gt_row gt_left gt_striped\">S3a — BChE auto-notify (operating)</td>\n<td headers=\"Detect  Cost\" class=\"gt_row gt_right gt_striped\">R55,000</td>\n<td headers=\"Detect  Notes\" class=\"gt_row gt_left gt_striped\">LIS HL7 middleware</td></tr>\n    <tr><td headers=\"Detect  Option\" class=\"gt_row gt_left\">S4 — PIH dashboard / MVD (operating)</td>\n<td headers=\"Detect  Cost\" class=\"gt_row gt_right\">R82,000</td>\n<td headers=\"Detect  Notes\" class=\"gt_row gt_left\">MVD redesign</td></tr>\n    <tr><td headers=\"Detect  Option\" class=\"gt_row gt_left gt_striped\">Surveillance MVP (S1+S3a+S4, operating) ★</td>\n<td headers=\"Detect  Cost\" class=\"gt_row gt_right gt_striped\">R137,000</td>\n<td headers=\"Detect  Notes\" class=\"gt_row gt_left gt_striped\">= R60k + R55k + R42k</td></tr>\n    <tr><td headers=\"Detect  Option\" class=\"gt_row gt_left\">Surveillance MVP setup (one-off)</td>\n<td headers=\"Detect  Cost\" class=\"gt_row gt_right\">R240,000</td>\n<td headers=\"Detect  Notes\" class=\"gt_row gt_left\">S3a HL7 dominates</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"3\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Act\">Act</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"Act  Option\" class=\"gt_row gt_left gt_striped\">C1 — NMC closure-of-loop field (operating)</td>\n<td headers=\"Act  Cost\" class=\"gt_row gt_right gt_striped\">R30,000</td>\n<td headers=\"Act  Notes\" class=\"gt_row gt_left gt_striped\">Schema + EHP training</td></tr>\n    <tr><td headers=\"Act  Option\" class=\"gt_row gt_left\">C2 — Structured DALRRD referral form (operating)</td>\n<td headers=\"Act  Cost\" class=\"gt_row gt_right\">R25,000</td>\n<td headers=\"Act  Notes\" class=\"gt_row gt_left\">Form + workflow</td></tr>\n    <tr><td headers=\"Act  Option\" class=\"gt_row gt_left gt_striped\">C3 — NICD→DALRRD intelligence feed (operating)</td>\n<td headers=\"Act  Cost\" class=\"gt_row gt_right gt_striped\">R40,000</td>\n<td headers=\"Act  Notes\" class=\"gt_row gt_left gt_striped\">Quarterly brief + alerts</td></tr>\n    <tr><td headers=\"Act  Option\" class=\"gt_row gt_left\">C4 — Clinician auto-feedback (operating)</td>\n<td headers=\"Act  Cost\" class=\"gt_row gt_right\">R20,000</td>\n<td headers=\"Act  Notes\" class=\"gt_row gt_left\">Email templating</td></tr>\n    <tr><td headers=\"Act  Option\" class=\"gt_row gt_left gt_striped\">C5 — Joint KPI dashboard (operating)</td>\n<td headers=\"Act  Cost\" class=\"gt_row gt_right gt_striped\">R30,000</td>\n<td headers=\"Act  Notes\" class=\"gt_row gt_left gt_striped\">Public hosting</td></tr>\n    <tr><td headers=\"Act  Option\" class=\"gt_row gt_left\">Coordination Full Package (operating) ★</td>\n<td headers=\"Act  Cost\" class=\"gt_row gt_right\">R145,000</td>\n<td headers=\"Act  Notes\" class=\"gt_row gt_left\">= Σ C1..C5</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"3\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Restrict\">Restrict</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"Restrict  Option\" class=\"gt_row gt_left gt_striped\">T2 — RUP + audit + formulation restriction (low)</td>\n<td headers=\"Restrict  Cost\" class=\"gt_row gt_right gt_striped\">R1.00 million</td>\n<td headers=\"Restrict  Notes\" class=\"gt_row gt_left gt_striped\">DALRRD inspectorate, lower</td></tr>\n    <tr><td headers=\"Restrict  Option\" class=\"gt_row gt_left\">T2 — RUP + audit + formulation restriction (mid)★</td>\n<td headers=\"Restrict  Cost\" class=\"gt_row gt_right\">R2.00 million</td>\n<td headers=\"Restrict  Notes\" class=\"gt_row gt_left\">Working value</td></tr>\n    <tr><td headers=\"Restrict  Option\" class=\"gt_row gt_left gt_striped\">T2 — RUP + audit + formulation restriction (hi)</td>\n<td headers=\"Restrict  Cost\" class=\"gt_row gt_right gt_striped\">R3.00 million</td>\n<td headers=\"Restrict  Notes\" class=\"gt_row gt_left gt_striped\">Upper</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::: {.callout-tip icon=false collapse=\"true\"}\n## Under the hood — models, packages, and formulae\n\n**Software stack.** This site is built with **Quarto v1.x** rendering R chunks through **R ≥ 4.3** and **knitr**. Tables use **[gt](https://gt.rstudio.com/)**; data wrangling **[tidyverse](https://www.tidyverse.org/)** (`dplyr`, `readr`, `tibble`); percentage formatting **[scales](https://scales.r-lib.org/)**; diagrams **[mermaid](https://mermaid.js.org/)** via Quarto's built-in diagram filter. The interactive [Parameter Playground](../parameter_playground.qmd) layer adds **[Observable JS](https://observablehq.com/@observablehq/observable-javascript)** via Quarto OJS.\n\n**Canonical parameter file.** All numerical values in every brief, the one-pager, and the playground resolve through `pick(name)` → `readr::read_csv(\"../amua_import_parameters_v3.csv\")` → string lookup → `as.numeric()` → `zar()` formatter. **No rand value in any brief is a literal in prose** (except where prose paraphrases a CSV-sourced value). The audit chain is: CSV row → `_shared_parameters.qmd` `pick()` call → rendered `gt` cell.\n\n**Burden model (closed-form, deterministic).**\n\n$$\nC_{\\text{burden}} \\;=\\; \\underbrace{\\sum_{s \\in \\{\\text{PIH},\\text{NHLS},\\text{NMC}\\}} n_s \\cdot c^{\\text{morb}}_s}_{\\text{morbidity}} \\;+\\; \\underbrace{n_{\\text{deaths}} \\cdot c^{\\text{mort}}_{\\text{HC}}}_{\\text{mortality (human-capital)}}\n$$\n\nwhere $n_s$ = stream counts (rows `n_pih_annual`, `n_nhls_severe_annual`, `n_nmc_annual`), $c^{\\text{morb}}_s$ = stratum-specific per-case morbidity costs (rows `c_morbidity_*`), $n_{\\text{deaths}} = 2{,}620$ (`n_deaths_statssa_macod` — **StatsSA MACOD 2023 (X40-X49) is the canonical truth source for deaths and is updated as new StatsSA releases land**; `n_deaths_headline` mirrors it), $c^{\\text{mort}}_{\\text{HC}} = $ 25 productive years × R60k median income, undiscounted (`c_mortality_human_capital`). Stratified-CFR alternative (`C_burden_total_conservative` ≈ R1.34B) is supplied as a sensitivity.\n\n**Coordination decision tree (closed-form joint probability).**\n\n$$\nP(\\text{loop closed}) \\;=\\; \\prod_{i=1}^{8} p_i\n$$\n\nover eight sequential nodes (notify → SMS → investigate → record → refer → DALRRD acts → feedback → feedback to clinician). Status-quo joint product ≈ 1.1 % (`p_loop_closed_status_quo`); Full Package ≈ 70 % (`p_loop_closed_FP`). Deaths averted = $\\Delta P \\times \\eta \\times n_{\\text{burden}} \\times p_{\\text{death}}$, with $\\eta$ from `eta_response_mid` = 0.30 and $p_{\\text{death}}$ from `cfr_headline_mid` = 0.125.\n\n**Terbufos bracketed estimate.**\n\n$$\n\\text{Deaths averted}_{T3} \\;=\\; f_{\\text{attr}} \\cdot \\phi_{\\text{retired}} \\cdot n_{\\text{deaths}}\n$$\n\nwith $f_{\\text{attr}} \\in [0.20, 0.35]$ (`frac_terbufos_attributable_{lo,mid,hi}`, anchored to Sri Lanka Class Ia withdrawal natural experiments, Gunnell et al. *Lancet Glob Health* 2017) and $\\phi_{\\text{retired}} \\in [0.60, 0.80]$ (Sri Lanka substitution-incompleteness). Bracket: 200–400 deaths/yr (`n_deaths_averted_T3_{lo,hi}`).\n\n**Surveillance detection model.**\n\n$$\n\\text{Cases averted} \\;=\\; (P_{\\text{detect}} - P_{\\text{detect}}^{\\text{SQ}}) \\cdot \\eta \\cdot n_{\\text{burden}}\n$$\n\nwith $P_{\\text{detect}}$ pulled from `d_status_quo`, `d_option1_NHLS_MOU`, …, `d_full_package` (expert elicitation, beta priors). Cost-effectiveness uses **net monetary benefit (NMB)** at the SA cost-effectiveness threshold $\\lambda$ = R38,500/DALY averted (Edoka & Stacey 2020).\n\n**Probabilistic sensitivity analysis (PSA).** Each CSV row carries a `dist=<family>(<params>)` tag (`beta`, `gamma`, `fixed`) parsed by the analysis pipeline (`wrangling_v2.r`) for Monte Carlo PSA. Distributions follow standard health-economics conventions: gamma for costs (shape 25 → CV ≈ 0.20), beta for probabilities (parameterised on the sample-equivalent count), fixed for deterministic anchors and derived sums.\n\n**What this site does *not* do.** No mixed-effects regression, no machine-learning model, no causal-inference identification strategy, no Bayesian hierarchical model. The site is a transparent deterministic burden-and-decision-tree calculator with explicit PSA. Strength comes from auditability, not algorithmic complexity.\n:::\n:::\n\n\n::: {.callout-note}\n## Health-sector share of the burden — what surveillance unlocks\n\nThe public health system bears **~R80M of the R2.34B annual burden** on its own budget lines (~R70M NDoH ward/ICU/ventilation/antidote; ~R10M NHLS BChE + confirmatory). Surveillance is a **necessary but not sufficient** input to reducing that burden — it changes only what is *seen*. Burden reduction comes from the coordinated response (source removal, regulatory action, clinical management) covered in the [Coordination](coordination_policy.qmd) and [Terbufos](terbufos_policy.qmd) briefs. **This brief therefore measures the proportion of true burden detected (P_detect); it does not measure cases or deaths averted.**\n:::\n\n**Architecturally, the three streams are unlinked:**\n\n```{mermaid}\n%%| label: fig-surv-current-system\n%%| fig-cap: \"Current surveillance architecture. NMC is NDoH-owned and has demonstrated flexibility and resilience as a national surveillance platform. NHLS BChE results can be routed to NMC via NHLS CDW → NICD SDW (this feed already exists for infectious disease). Two active gaps remain: PIH consultations are not linked to NMC, with neither stream holding a complete minimum dataset for surveillance; forensic chemical toxicology is post-mortem only and fully de-identified (not fit for surveillance linkage in its current form; MLDI system development is a potential future pathway).\"\nflowchart LR\n    A[Healthcare Facility<br/>Clinician / PHO] -->|NMC notification| E[(\"NDoH / NMC<br/><b>NDoH-owned</b><br/>Source of truth\")]\n    A --> NHLS\n\n    subgraph NHLS[NHLS]\n        direction TB\n        C1[BChE Assay<br/>1,779 severe/year<br/>10,626 tests 2023<br/><i>Live patients</i>]\n        C2[Chemical Toxicology<br/><i>Post-mortem only —<br/>not yet done on<br/>live patients</i>]\n        CDW[(NHLS CDW)]\n        C1 -->|monthly extract| CDW\n    end\n\n    SDW[(NICD SDW)]\n    CDW -->|\"✓ MOU feed<br/>operational\"| SDW\n    SDW -->|BChE monthly| E\n\n    A --> D[PIH Consultation<br/>~1,158 clinician calls/yr<br/><i>No minimum dataset</i>]\n\n    C2 -.x Not available for<br/>live-patient surveillance.-x E\n    D -.No minimum viable<br/>dataset defined.-> E\n\n    style E fill:#9f9,stroke:#060,stroke-width:2px\n    style A fill:#fde,stroke:#333\n    style C1 fill:#bbf,stroke:#333\n    style C2 fill:#ffd9b3,stroke:#cc8800,stroke-dasharray: 5 5\n    style D fill:#bfb,stroke:#333\n    style CDW fill:#e6f0ff,stroke:#3366cc\n    style SDW fill:#e6f0ff,stroke:#3366cc\n```\n\n**What this means in plain numbers.**\n\n- NMC notifications: 1,013 ([`n_nmc_annual`](../parameters_hub.qmd#tbl-burden))\n- NHLS severe BChE inhibitions: 1,779 ([`n_nhls_severe_annual`](../parameters_hub.qmd#tbl-burden)) out of 10,626 BChE tests ([`n_nhls_total_annual`](../parameters_hub.qmd#tbl-burden))\n- PIH clinician-initiated calls: 1,158 ([`n_pih_annual`](../parameters_hub.qmd#tbl-burden))\n- Implied true annual burden: $N_\\text{true} = \\frac{2,620}{0.125} = 20,960$ ([`n_true_burden_from_statssa_mid`](../parameters_hub.qmd#tbl-burden))\n\nNMC alone captures $P_\\text{detect} = \\frac{1,013}{20,960} = 0.048$ ([`d_status_quo`](../parameters_hub.qmd#tbl-detection)), i.e. **< 5 %**.\n\n::: {.callout-caution appearance=\"minimal\" collapse=\"true\"}\n## Caveat: this denominator rests on a CFR assumption\nThe 20,960 denominator applies a 12.5% CFR to the StatsSA MACOD death count (ICD-10 X40–X49) — but that CFR derives from NMC-*notified* severe cases (the sicker end of the distribution). The undetected majority are likely milder; a blended CFR of 3–5% implies 52,000–87,000 true cases and a status-quo P_detect of 1–2%. Relative option rankings (Option 1, Option 2, MVP†) are stable across this range — the percentage-point gain for each option is unchanged; only the absolute number of true cases detected would differ.\n\n†MVP = Minimum Viable Package (Option 1 + Option 2 combined).\n:::\n\n### Detection vs. true burden — a critical distinction\n\nBetter surveillance has **two opposite numerical effects** that decision-makers must not confuse:\n\n| Effect | Direction | Driver | Interpretation |\n|:-------|:---------:|:-------|:---------------|\n| **Observed** burden | ↑ | Better case-finding (auto-notify, MVD ingest) | The headline \"case count\" will rise as detection improves — this is success, not failure. |\n| **True** burden | ↓ | Faster source removal, targeted regulation, prevention | Future poisoning cases and clusters are averted. |\n\nOnce the integrated streams are live, reported case counts will rise as detection improves and historical burden estimates should be re-calibrated against the expanded data. This is a surveillance artefact, not a true increase in poisonings, and must be communicated as such in any public reporting.\n\n## 4. Root cause analysis\n\n```{mermaid}\n%%| label: fig-surv-fishbone\n%%| fig-cap: \"Root causes of surveillance under-detection and the surveillance-improvement options that address each one.\"\nflowchart LR\n    A[Surveillance under-detection] --> B[NHLS–NMC MOU not<br/>IT-implemented]\n    A --> C[PIH data not used<br/>for surveillance]\n    A --> D[Delayed manual reporting]\n    A --> F[No live-patient<br/>chemical toxicology]\n\n    B --> G[\"✓ NHLS→NMC IT feed<br/><i>Completed</i>\"]\n    C --> H[Option 2: PIH MVD<br/>+ dashboard]\n    D --> I[Option 1: BChE<br/>auto-notify <i>capability exists</i>]\n    F --> J[Option 5: Sentinel<br/>toxicology + auto-notify]\n\n    style A fill:#f99,stroke:#333\n    style G fill:#e0e0e0,stroke:#999,stroke-dasharray: 5 5\n    style H fill:#9f9,stroke:#333\n    style I fill:#9f9,stroke:#333\n    style J fill:#9f9,stroke:#333\n```\n\nThree active root causes remain **executional, not legislative**, and are each already legally permissible under Section 90 of the National Health Act (2003) and the existing NMC regulations. The fourth root cause (NHLS–NMC IT connectivity) has been resolved — the LIS-to-NMC feed is operational, though a severity-threshold rules engine still needs to be configured to enable automated alerting. \n\n## 5. Policy options\n\n::: {.callout-tip icon=false}\n## ✓ NHLS–NMC IT feed — now operational\n\nThe NHLS–NICD LIS-to-NMC connector is operational; daily BChE data flows to NICD under the existing MOU. The three active options below build on this.\n:::\n\n::: {.callout-note appearance=\"simple\"}\n**Reading guide — option numbering.** Options below are numbered **1–5 in narrative build order**. Backend parameter codes in the CSV (`c_S1_*`, `c_S2_*`, `c_S1b_*`, `c_option6_*`) are stable identifiers that pre-date the renumbering and **do not follow the brief's order**. Cross-walk:\n\n| Option (display) | Description | CSV parameter family |\n|:-----------------|:-----------|:---------------------|\n| **Option 1** | BChE auto-notification *(first build, ★ recommended)* | `c_S2_BChE_autonotify_*` |\n| **Option 2** | PIH dashboard + MVD *(second build, ★ recommended — completes the MVP)* | `c_S1_PIH_MVD_*` |\n| **Option 3** | Community layer *(Phase 2, conditional)* | `c_S1b_*` |\n| **Option 4** | NMC CIF + agricultural extension *(bridge to coordination)* | (no dedicated parameter) |\n| **Option 5** | Sentinel live-patient toxicology *(research-funded, distinct purpose)* | `c_option6_*` |\n\nS0 (NHLS→NMC IT feed) is operational and in the baseline. **Surveillance MVP = Options 1 + 2.**\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Audit trail — mini-budget backing the S0 operating cost (R60,000/yr, now in baseline) {#sec-s0-mini-budget}\n\n`c_S0_NHLS_NMC_feed_op` = R60,000/yr (gamma(25, 2400)); `c_S0_NHLS_NMC_feed_setup` = R80,000 one-off (already incurred). This feed is **in the status-quo baseline** — it is not a marginal cost of adopting the Surveillance MVP, but its operating cost is relevant context for decision-makers auditing total program spend.\n\n| # | Line item | Driver | Annual (R) | Source / anchor |\n|:-:|:----------|:-------|-----------:|:----------------|\n| 1 | NICD analyst data extraction + cleaning | 0.05 FTE × R650k DPSA L10-11 | 32,500 | DPSA L10-11 scale 2024 (Tab 1 NMC analyst CTE) |\n| 2 | NHLS CDW data extract QA (monthly BChE pull validation) | 0.02 FTE × R900k NHLS medical scientist | 18,000 | NHLS Patterson grade D 2024 (Tab 1 NHLS scientist CTE) |\n| 3 | NICD SDW hosting + data-feed monitoring (shared cloud, pesticide slice) | AWS af-south-1 shared allocation | 6,000 | NICD data platform budget 2024 (Tab 2 \"Data warehouse / ETL\") |\n| 4 | Annual MOU compliance review + governance documentation | Inter-agency MOU review + admin | 3,500 | NICD legal + NHLS MOU management |\n|   | **Total** |   | **60,000** | matches `c_S0_NHLS_NMC_feed_op` in [`amua_import_parameters_v4.csv`](../amua_import_parameters_v4.csv) |\n\n**Distribution.** gamma(shape = 25, scale = 2,400) → mean R60,000, SD ≈ R12,000. Items 1 and 2 are time-allocated personnel cost at standard CTE rates; items 3 and 4 are direct cash outlays. The same analyst CTE anchor (R650k DPSA L10-11) underpins the NMC baseline in §7 Tab 1, so S0 is consistent with and additive to the status-quo build-up.\n\n**Setup.** `c_S0_NHLS_NMC_feed_setup` = R80,000 (one-off) covered: legal/MOU negotiation, data-mapping and schema agreement, NICD SDW ingestion script development, UAT. Already incurred; not a cost of adopting the MVP.\n:::\n\n### Option 1 — BChE auto-notification *(★ recommended — first build, capability exists)*\n\nConfigure the NHLS LIS to fire an automatic NICD notification when a BChE result shows severe inhibition (< 10 % of normal)*, within 24 hours of validation. **No new test, no new reagent contract** — only an IT configuration on top of the ~10,626 BChE tests/year already performed (1,779 severe in 2023). Detection rises to ~13 % of true cases (up from ~5 %) for a one-off setup of **R200,000**, then **R55,000/year** from Year 2 (Year 1 total: **R255,000**), deliverable in 2–4 weeks. Uses existing NHLS infrastructure with a single owner (NHLS LIS) and delivers the largest single-option P_detect uplift (+8.5 pp) — recommended as the first build.\n\n* Severe inhibition is most closely related to severe sequelae such as hospitalisation and death [Chaudhary S, Jain N, Atam V, Agarwal A, Singh K, Sawlani K, et al. Prognostic significance of estimation of pseudocholinesterase activity and role of pralidoxime therapy in organophosphorous poisoning. Toxicol Int. 2013;20(3):214]. Taking any BChE test will likely increase the FP rate and this will not be accounted for.\n\n::: {.callout-note collapse=\"true\"}\n## Audit trail — mini-budget backing Option 1 (BChE auto-notify): R55,000/yr {#sec-opt1-mini-budget}\n\n`c_S2_BChE_autonotify_op` = R55,000/yr (gamma(25, 2200)) covers the pure IT infrastructure required to keep the HL7 auto-notification middleware running (for poisoning only) — **no new laboratory tests, no new reagent contract, no new hires.** The one-off LIS reconfiguration and UAT cost (`c_S2_BChE_autonotify_setup` = R200,000) is separately parameterised. All figures are 2024–2025 ZAR, marginal over the status-quo NHLS BChE baseline.\n\n| # | Line item | Driver | Annual (R) | Source / anchor |\n|:-:|:----------|:-------|-----------:|:----------------|\n| 1 | HL7 middleware hosting (Mirth Connect; af-south-1 t3.small VM) | VM + storage, 12 mo | 18,000 | AWS af-south-1 pricing 2024 (same tier as §7 Tab 2 \"LIS rule engine middleware\") |\n| 2 | NHLS LIS IT engineer maintenance | 0.02 FTE × R750k SITA/state IT rate | 15,000 | SITA / state IT contracting 2024 (Tab 1 Cross-cutting data engineer CTE) |\n| 3 | NHLS medical scientist alert QA review | 0.005 FTE × R900k NHLS Patterson grade D | 4,500 | NHLS Patterson grade D 2024 (Tab 1 NHLS scientist CTE) |\n| 4 | NICD epidemiologist alert triage + NMC routing | 0.01 FTE × R650k DPSA L10-11 | 6,500 | DPSA L10-11 scale 2024 (Tab 1 NMC analyst CTE) |\n| 5 | Mirth Connect enterprise support licence / maintenance agreement | Annual contract | 7,000 | NHLS IT estimate (cited in `c_S2_BChE_autonotify_op` source note) |\n| 6 | NICD analyst QA reconciliation (NHLS→NMC matching spot-checks) | 0.005 FTE × R650k | 3,250 | DPSA L10-11 scale 2024 |\n| 7 | On-call incident-response allowance (middleware outage cover) | Annual allowance | 750 | NHLS IT estimate |\n|   | **Total** |   | **55,000** | matches `c_S2_BChE_autonotify_op` in [`amua_import_parameters_v4.csv`](../amua_import_parameters_v4.csv) |\n\n**Distribution.** gamma(shape = 25, scale = 2,200) → mean R55,000, SD ≈ R11,000 (95% CI ≈ R36k–R78k). Items 1 and 5 are direct cash outlays (cloud hosting + licence); items 2, 3, 4 and 6 are time-allocated personnel cost at §7 Tab 1 CTE rates — no new hires; the Option 1 allocation is additive to the existing pesticide share of those posts.\n\n**Sensitivity.** Middleware hosting tier is the dominant driver (t3.small → t3.medium adds ~R12,000/yr); doubling the NHLS IT FTE share adds ~R15,000/yr. Neither moves Option 1 above Option 2 in operating cost (R82,000/yr).\n\n**Setup.** `c_S2_BChE_autonotify_setup` = R200,000 (one-off) covers NHLS LIS HL7 rule development, configuration of the severity threshold (< 10% of normal enzyme activity), UAT across NHLS network sites, and go-live sign-off. Spent once; not part of the recurring R55,000/yr.\n:::\n\n### Option 2 — PIH live dashboard + Minimum Viable Dataset *(★ recommended — second build, completes the MVP)*\n\nTwo layers:\n\n- **Short term (1–2 weeks):** PIH publishes a live dashboard of pesticide-related calls (counts, geography, agent, severity, demographics, **AfriTox agent name**). No new data; just a daily extract from existing call records.\n- **Medium term (3–9 months):** PIH and NICD agree a **Minimum Viable Dataset (MVD)** so the ~1,158 clinician-initiated calls/year can be ingested into NMC as a structured surveillance stream. **Agent-name capture is a mandatory MVD field** — both PIH and NMC must record the AfriTox product name for every case. To make this reciprocal, **NMC should add a structured agent drop-down** (pesticide class → active ingredient → AfriTox product name) to its NDoH-hosted notification form: PIH records what the caller *reports*; NMC records what the clinician *confirms*. Combined: agent-attribution signal system-wide at near-zero marginal cost.\n\nDetection rises to ~10 % of true cases (up from ~5 %) for a one-off setup of **R40,000**, then **R82,000/year** from Year 2 (Year 1 total: **R122,000**; includes AfriTox agent-name harmonisation). The dashboard ships in days; the MVD ingest is the second build to complete the MVP.\n\n::: {.callout-note collapse=\"true\"}\n## Audit trail — mini-budget backing Option 2 (PIH dashboard + MVD): R82,000/yr {#sec-opt2-mini-budget}\n\nThe `c_S1_PIH_MVD_op` parameter (mean R82,000/yr; gamma(25, 3280)) is **not a single quoted price** — it is the sum of seven small recurring line items required to keep the PIH dashboard live, the MVD pipeline running, and the AfriTox agent drop-down synchronised between PIH and NMC. All figures are 2024–2025 ZAR, marginal over the status-quo PIH operation (which is already costed in §7 Tab 1–2 from [`data/surveillance_costing.xlsx`](../data/surveillance_costing.xlsx)).\n\n| # | Line item | Driver | Annual (R) | Source / anchor |\n|:-:|:----------|:-------|-----------:|:----------------|\n| 1 | Dashboard hosting (PIH Tygerberg cloud VM) | AWS af-south-1 t3.small + RDS + backup, 12 mo | 18,000 | AWS af-south-1 pricing 2024 (also Tab 2 of [`surveillance_costing.xlsx`](../data/surveillance_costing.xlsx), row \"Dashboard hosting (Tygerberg cloud VM)\", pesticide share) |\n| 2 | Daily PIH→dashboard extract pipeline (script + on-call) | 0.02 FTE × R780k poisons specialist | 15,600 | DoH pharmacy OSD scale 2024 (PIH specialist CTE used in Tab 1) |\n| 3 | AfriTox agent-name harmonisation maintenance (PIH ↔ NMC drop-down sync, quarterly refresh) | 0.02 FTE × R650k NICD epidemiologist | 13,000 | DPSA L10-11 scale 2024 (Tab 1 NMC analyst CTE) |\n| 4 | MVD ingest pipeline operations (ETL run, error handling, schema drift) | NICD data engineer 0.015 FTE × R750k | 11,250 | SITA / state IT contracting 2024 (Tab 1 Cross-cutting) |\n| 5 | QA + monthly NMC reconciliation (PIH-ingested rows vs NMC) | 1 h/wk × R650k NICD analyst (0.01 FTE) | 6,500 | DPSA L10-11 scale 2024 |\n| 6 | Annual data-dictionary review + minor MVD releases | PIH + NICD workshop, 2 d/yr; consumables | 10,000 | PIH admin estimate (consistent with `c_S1_PIH_MVD_setup` R40,000 one-off) |\n| 7 | Licences + alert SMS (Power BI workspace seats, ~5,000 outbound SMS/yr @ R0.20) | Microsoft ZA EA + Clickatell rate | 7,650 | Microsoft ZA EA 2024; Clickatell / BulkSMS ZA 2024 (same anchors as §7 Tab 2) |\n|   | **Total** |   | **82,000** | matches `c_S1_PIH_MVD_op` in [`amua_import_parameters_v4.csv`](../amua_import_parameters_v4.csv) |\n\n**Distribution.** gamma(shape = 25, scale = 3,280) → mean R82,000, SD ≈ R16,400 (95% CI ≈ R53k–R116k); absorbs reasonable variation across all seven items. Items 1, 4 and 7 are direct cash outlays (cloud, ETL, licences, SMS); items 2, 3, 5 and 6 are time-allocated personnel cost at §7 Tab 1 CTE rates — no new hires, ring-fenced fractions of existing PIH and NICD posts.\n\n**Sensitivity — what would push it materially higher.** (i) Power BI Premium dedicated capacity rather than a small VM (+R30–50k/yr); (ii) replacing the 0.02 FTE pharmacist time with a dedicated data engineer FTE (+R60k/yr at 0.1 FTE); (iii) 5× alert-SMS volume during outbreaks (+R3–5k/yr). None move the option above Option 1 (R55,000/yr) or near Option 3 (R-millions/yr).\n:::\n\n### Option 3 — Community layer (Phase 2) *(commission after MVP pilot if rural/informal gap confirms)*\n\nOptions 1 and 2 improve detection within the **formal healthcare system** (PIH, NHLS BChE, NMC-notified facilities). They cannot reach cases that never arrive at a formal facility — the child taken to a traditional healer after ingesting street-sold granules, the farm worker who doesn't present at all, the informal-settlement cluster whose care pathway bypasses formal services.\n\n::: {.callout-important}\n**Pre-condition — non-clinician reporting must be enabled.** Option 3 only delivers a coverage uplift if PIH (and the NMC CIF, via Option 4) accept structured reports from **non-medical personnel**: community health workers (CHWs), environmental health practitioners (EHPs), ward-based outreach teams, agricultural extension officers, teachers, traditional healers, and community members. The Option 2 PIH stream is built on the ~1,158 *clinician-initiated* PIH calls/year and by construction cannot see cases that never reach a clinician. Without a dedicated non-clinician intake channel — Tier-1 CHW checklist as the structured form, EHP call-back as validation — the CHW network has nowhere to land its reports and Option 3 reduces to training cost with no measurable P_detect gain.\n:::\n\n**The MVP ceiling (~19% P_detect)** is bounded by the reach of formal administrative streams. Option 3 is the mechanism for going beyond it, but only after the MVP has confirmed the remaining gap is structural rather than a compliance issue within the formal system.\n\n**Trigger condition.** Commission Option 3 if, after 6 months of MVP operation, the geographic distribution of PIH + NHLS + NMC cases shows ≥40% of severe cases originating in districts with low formal-facility access (defined as <1 public hospital per 50km radius). This is a data-driven go/no-go, not a discretionary expansion. CSV parameters: `d_S1b_event_community_*`, `c_S1b_setup_*`, `c_S1b_op_*`, `p_fp_S1b_*`.\n\n**False-positive load and triage architecture.** The gross false-positive rate is ~35% (range 20–50%). At P_detect = 0.40 on the mid-burden of 20,960 true cases, the gross notification volume would be ~12,898 events/yr — of which ~8,384 are true cases and ~4,514 are false alerts *before filtering*. This is solvable with a **two-tier triage architecture** — the same design used by WHO-EWARN, APSED, and comparable LMIC systems:\n\n1. **Tier 1 — CHW structured checklist**: Community health workers report via a mobile checklist requiring ≥2 of: acute onset, ≥2 affected persons, known or suspected product contact. Events not meeting criteria are logged but no dispatch is triggered.\n2. **Tier 2 — EHP call-back within 24 hours**: A provincial EHP calls back to confirm before committing to on-site investigation.\n\nWith a two-tier filter, the effective net FP rate drops to approximately 8–12% — within the investigation capacity modelled in the [Coordination brief](coordination_policy.qmd).\n\n**Two-stage rollout — Free State and Gauteng first.** These two provinces account for an estimated **~50% of the annual pesticide-poisoning burden** (working assumption; to be confirmed against the MVP pilot's geographic distribution from NMC, NHLS, and PIH data). Comparable LMIC systems have achieved P_detect in the range 0.25–0.55 — 1.3–2.9× the MVP ceiling.\n\n| Stage | Provinces | Est. burden share | Setup cost | Operating cost/yr | Go/no-go criterion |\n|:------|:----------|------------------:|-----------:|------------------:|:-------------------|\n| **Option 3 pilot** | Free State + Gauteng | ~50% | ~R1M | ~R0.8M/yr | Month 12: net P_detect >35% and net FP <15% |\n| **Option 3 national** | All 9 provinces | 100% | ~R3.5M | ~R2.5M/yr | Conditional on pilot outcome |\n\nThe cost range (R1M–R3.5M setup; R0.8M–R2.5M/yr operating — approximately 6–18× the MVP operating cost) directly reflects the two-stage choice.\n\n::: {.callout-note collapse=\"true\"}\n## Audit trail — mini-budget backing Option 3 (community layer) operating cost range {#sec-opt3-mini-budget}\n\nThe three `c_S1b_op_*` parameters reflect **distinct deployment footprints**, not sensitivity bounds around a single estimate. All figures are 2024–2025 ZAR, marginal over the Surveillance MVP baseline.\n\n**Lo scenario — pilot (2 provinces: Free State + Gauteng) | `c_S1b_op_lo` = R800,000/yr**\n\n| # | Line item | Driver | Annual (R) | Source / anchor |\n|:-:|:----------|:-------|-----------:|:----------------|\n| 1 | Provincial coordinators ×4 (FS + Gauteng) | 4 × R120,000 DPSA L8 pesticide-surveillance allocation | 480,000 | DPSA L8 mid-step CTE ~R600k–R750k; R120k = ~17% FTE allocation |\n| 2 | Platform hosting + mobile checklist app | AWS af-south-1 + off-the-shelf EBS mobile app, 2-province scale | 120,000 | AWS af-south-1 pricing 2024 |\n| 3 | CHW structured training + annual refresher | 2 provinces × 2 training cohorts + consumables | 120,000 | LMIC community surveillance analogue (IDSR pilot) |\n| 4 | NICD data analyst + monthly reporting | 0.1 FTE × R650k DPSA L10-11 | 65,000 | DPSA L10-11 scale 2024 |\n| 5 | EHP call-back protocol management + QA | 0.015 FTE × R650k NICD analyst | 15,000 | DPSA L10-11 scale 2024 |\n|   | **Total (lo / pilot)** |   | **800,000** | matches `c_S1b_op_lo` |\n\n**Mid scenario — working value (8 provinces) | `c_S1b_op_mid` = R1,500,000/yr**\n\nFrom CSV note: *\"~8 provincial coordinators (DPSA L8, R120k each) + national analyst + platform hosting + annual CHW refresher.\"*\n\n| # | Line item | Driver | Annual (R) | Source / anchor |\n|:-:|:----------|:-------|-----------:|:----------------|\n| 1 | Provincial coordinators ×8 | 8 × R120,000 DPSA L8 | 960,000 | DPSA L8 scale 2024 (same unit cost as lo) |\n| 2 | National NICD analyst | 0.2 FTE × R650k DPSA L10-11 | 130,000 | DPSA L10-11 scale 2024 |\n| 3 | Platform hosting + app maintenance | AWS multi-province scale + maintenance | 180,000 | AWS af-south-1 pricing 2024 |\n| 4 | Annual CHW refresher training | 8 provinces × cohort costs | 230,000 | EWARN/IDSR analogues |\n|   | **Total (mid / working)** |   | **1,500,000** | matches `c_S1b_op_mid` |\n\n**Hi scenario — full 9-province + dedicated EHP nodes | `c_S1b_op_hi` = R2,500,000/yr**\n\nFrom CSV note: *\"full 9-province deployment with dedicated EHP nodes and enhanced data cleaning.\"*\n\n| # | Line item | Driver | Annual (R) | Source / anchor |\n|:-:|:----------|:-------|-----------:|:----------------|\n| 1 | Provincial coordinators + dedicated EHP nodes ×9 | 9 × R160,000 DPSA L8-9 (dedicated EHP grade) | 1,440,000 | DPSA L8-L9 scale 2024 |\n| 2 | National NICD analyst (enhanced share) | 0.3 FTE × R650k | 195,000 | DPSA L10-11 scale 2024 |\n| 3 | Platform hosting + enhanced data-cleaning infrastructure | 9-province scale + QA pipeline | 350,000 | AWS af-south-1 + QA infrastructure estimate |\n| 4 | Annual CHW refresher training (9 provinces) | 9 provinces × full cohort | 515,000 | WHO-EWARN mature deployment analogue |\n|   | **Total (hi / full)** |   | **2,500,000** | matches `c_S1b_op_hi` |\n\n**DPSA L8 anchor.** R120,000 represents ~16–20% FTE of a DPSA L8 mid-step CTE (~R600k–R750k/yr). In practice this is an existing EHP or health-promotion officer whose pesticide-poisoning community-surveillance duties are ring-fenced at that fraction — not a new hire. The same unit cost applies across all three scenarios; the scenarios differ in the number of provinces covered and whether dedicated EHP nodes (requiring L8-9 grade) are included.\n\n**Setup parameters.** `c_S1b_setup_lo/mid/hi` = R1M / R2M / R3.5M (one-off) cover mobile-app development, protocol design, and initial CHW training. They are separately parameterised and not included in the operating cost rows above.\n:::\n\n### Option 4 — NMC case investigation form + agricultural extension *(bridge to coordination)*\n\nSurveillance *counts* cases; **investigation** captures the source, the product, and the trigger for source removal. The NDoH [*Guideline for the Investigation of Human Chemical Poisoning* (2023)](https://www.health.gov.za/wp-content/uploads/2023/09/DOH-Guideline-Investigation-Human-Chemical-Poisoning-1.pdf) already defines a structured Case Investigation Form (CIF) that EHPs and clinicians are expected to complete within 48 hours of any chemical-poisoning notification — but uptake is inconsistent, the form is not embedded in the NMC workflow, and it lacks interventions that are carried out by DOA (source removal). In addition, occupational exposure (if appropriate) ought to be captured. \n\nThis option does two complementary things and is the **minimum surveillance-side investment required to make the [Coordination response](coordination_policy.qmd) operational**:\n\n1. **Operationalise the existing NDoH CIF inside NMC.** Embed the 2023 guideline's investigation fields as a structured second-stage form auto-triggered by any pesticide-poisoning notification — whether the notification originates from NMC, the Option 2 PIH MVD ingest, or the Option 1 BChE auto-notify rule. EHPs receive a workflow alert; CIF completion within 48 hours becomes a tracked NMC performance indicator (district-level KPI, reported quarterly).\n2. **Add an agricultural-investigation extension module.** Additional structured fields layered onto the CIF for:\n    - **Product origin:** formal retail / informal repackaged / agricultural concentrate / unknown;\n    - **AfriTox-coded agent name** (reciprocal with the Option 2 drop-down so PIH-reported and NMC-confirmed agent names are directly comparable);\n    - **Exposure context:** occupational (farm worker, applicator) / dietary / accidental / intentional / pediatric ingestion;\n    - **Site geolocation** (farm GPS / household / market / school) with district code;\n    - **Source-removal trigger flag** — an explicit field that, when set by the EHP, hands the case off to the DALRRD-Act-36 + DoH source-removal workflow described in the [Coordination brief](coordination_policy.qmd).\n\n**Cost.** ~R45,000 setup (form-template build into the NMC platform; one-day inter-departmental design workshop with NDoH EHP directorate, DALRRD Act-36 registrar, NICD, and PIH) and ~R35,000/yr operating (NICD analyst 0.04 FTE × R650k DPSA L10-11 for form-completion QA, drop-down maintenance and quarterly performance reporting to NDoH). **No new headcount** — same DPSA L10-11 analyst anchor used for S0, Option 1 and Option 2; no new IT platform — the NMC notification system already supports structured secondary forms.\n\n**P_detect impact.** Option 4 does not raise the share of true cases entering surveillance — that is the role of Options 1, 2 and 3. Its value is converting detected cases into actionable investigations: the data-quality bridge that lets the coordination response act on the right cases, with the right product information, at the right site. The agent-attribution field from Option 2 records the *what*; the CIF + agricultural extension records the *where, how, and who*.\n\n**Governance.** The form lives inside NMC; build, governance and KPIs are NDoH-owned surveillance infrastructure. The [Coordination brief](coordination_policy.qmd) *consumes* the structured CIF outputs to trigger source removal and inter-departmental escalation. No new legislation required: the CIF exists in the 2023 guideline; Section 90 of the National Health Act and the NMC regulations already authorise the data flows.\n\n### Option 5 — Sentinel live-patient toxicology *(★ recommended, medium term — distinct purpose, research-funded)*\n\nNHLS currently performs chemical toxicology (qualitative/quantitative pesticide assays) **post-mortem only**. There is no live-patient toxicology capability. Option 5 funds a sentinel tertiary site (e.g. CHB) to perform live-patient chemical toxicology and/or mass spectometry, scaling to 4–5 sites in phase 2–3. This will only capture ~ 323 severe poisoning cases. \n\n::: {.callout-caution appearance=\"minimal\"}\n**Forensic chemistry is fully de-identified and not fit for surveillance linkage.** No patient, facility, or case-linkage identifiers: cannot be matched to NMC or PIH records without structural re-design of specimen accessioning. The **MLDI system** is the longer-term pathway for surveillance-ready post-mortem toxicology — a separate workstream from Option 5.\n:::\n\n**Option 5 has a different purpose from Options 1 and 2** and is *not* a detection-coverage uplift. Options 1 and 2 raise the share of true cases entering surveillance. **Option 5 identifies the chemical agents found in severely poisoned living patients at sentinel sites** — the missing evidence base for product-specific regulation (see [Terbufos brief](terbufos_policy.qmd)). Without it, ~10,000 survivors/year are recorded with agent \"unknown / suspected\" and targeted product restriction has no quantitative footing. Some signal is captured in the SAMRC Injury and Mortality Survey (Prinsloo et al.) (*** NOTE FOR THE AUTHOR ***).\n\nCost: ~R1.2M pilot site → ~R3.6M for 5-site rollout, 6–12 months. Funded from research-surveillance streams (SAMRC, Bloomberg, Gates), not the surveillance operating budget. Full quantitative concept in the [sentinel toxicology appendix](surveillance_concept_note.qmd).\n\n::: {.callout-note collapse=\"true\"}\n## Audit trail — mini-budget backing Option 5 (sentinel toxicology) costs {#sec-opt5-mini-budget}\n\nFour component-level parameters in [`amua_import_parameters_v4.csv`](../amua_import_parameters_v4.csv) underpin both Option 5 cost rows. The pilot and 5-site budgets run **below the maximum specimen capacity** (`n_specimens_per_site_per_year` = 646): the pilot targets ~150 GC-MS screens and ~200 clinical batteries (ramp-up year); the 5-site rollout targets ~100 screens and ~133 batteries per site per year (steady-state research enrolment).\n\n**Pilot — 1 sentinel site (CHB) | `c_option6_pilot_year1` = R1,200,000/yr**\n\n| # | Line item | Driver | Annual (R) | CSV parameter / source |\n|:-:|:----------|:-------|-----------:|:----------------------|\n| 1 | Research nurse 0.5 FTE (TASK research band) | Per-site personnel anchor | 175,000 | `c_research_nurse_05FTE_per_site` |\n| 2 | GC-MS / LC-MS multi-residue screens (~150 specimens × R2,500) | Pilot ramp-up volume | 375,000 | `c_gcms_screen_per_specimen` × pilot volume |\n| 3 | Enhanced clinical batteries (~200 patients × R1,500; BChE + LFT + U&E + repeat) | All enrolled patients | 300,000 | `c_clinical_battery_per_patient` × pilot volume |\n| 4 | Chemical pathologist co-investigator time (0.07 FTE × R1,500k NHLS Patterson grade E) | Sign-out + supervision | 105,000 | NHLS Patterson grade E 2024 (Tab 1 NHLS chemical pathologist CTE) |\n| 5 | REDCap data management + statistical reporting | 1-site platform + annual report | 80,000 | Concept Note DRAFT 3 |\n| 6 | Site consumables, specimen transport + cold chain, overheads | ~150 specimens × ~R1,100 blended overhead | 165,000 | NHLS logistics tariff 2024 + consumables estimate |\n|   | **Total (pilot, 1 site)** |   | **1,200,000** | matches `c_option6_pilot_year1` |\n\n**Full rollout — 5 sentinel sites | `c_option6_full_5site_annual` = R3,625,000/yr**\n\n| # | Line item | Driver | Annual (R) | CSV parameter / source |\n|:-:|:----------|:-------|-----------:|:----------------------|\n| 1 | Research nurses ×5 (0.5 FTE each) | 5 × `c_research_nurse_05FTE_per_site` | 875,000 | `c_research_nurse_05FTE_per_site` × 5 |\n| 2 | GC-MS screens (5 sites × ~100 specimens × R2,500) | Steady-state research volume | 1,250,000 | `c_gcms_screen_per_specimen` × 5-site volume |\n| 3 | Enhanced clinical batteries (5 sites × ~133 patients × R1,500) | BChE + LFT + U&E + repeat | 997,500 | `c_clinical_battery_per_patient` × 5-site volume |\n| 4 | Multi-site coordination (NHLS + NICD; 0.2 FTE × R750k data engineer) | Network coordination | 150,000 | SITA / state IT contracting 2024 (Tab 1 Cross-cutting) |\n| 5 | Data management + reporting (multi-site REDCap + analysis) | 5-site QA + annual report | 202,500 | Concept Note DRAFT 3 |\n| 6 | Site consumables, transport, cold chain (5 sites × R30k) | Per-site recurring overhead | 150,000 | NHLS logistics tariff 2024 |\n|   | **Total (5-site)** |   | **3,625,000** | matches `c_option6_full_5site_annual` |\n\n**Why Option 5 sits outside the surveillance operating budget.** Option 5 is a **research investment** — it generates the agent-attribution evidence base for targeted regulatory action and does not raise P_detect. Its value is quantified in the [Terbufos brief](terbufos_policy.qmd), where regulatory restriction converts agent-attribution evidence into deaths averted.\n\n**Why specimens run below the per-site capacity of 646.** `n_specimens_per_site_per_year` (= 646) is the *anatomically derived maximum* (2 specimens per patient × 323 patients — the sample-size calculation for the agent-attribution study at p = 0.3, d = 0.05). Actual enrolment ramps up over the pilot year (~150 screens) to a steady state of ~100–133 screens per site, constrained by the research budget rather than specimen throughput.\n:::\n\n### Summary comparison\n\n\n| Option | Setup (one-off) | Annual operating (yr 2+) | Year 1 total | P_detect (per-case) | Δ vs. status quo | R / pp† | Time | Parameter |\n|:-------|----------------:|-------------------------:|-------------:|:-------------------:|:----------------:|----------:|:-----|:----------|\n| Status quo | — | R0 | R0 | $\\frac{1,013}{20,960} = 0.048$ | — | — | — | [`d_status_quo`](../parameters_hub.qmd#tbl-detection) |\n| Option 1 — BChE auto-notify *(first build; CSV: `c_S2_*`)* | R200,000 | R55,000 | R255,000 | $\\frac{1,013 + 1,779}{20,960} = 0.133$ | +8.5 pp | R6,471 / pp | 2–4 wks | [`d_S2_BChE_autonotify`](../parameters_hub.qmd#tbl-detection) |\n| Option 2 — PIH dashboard + MVD (+AfriTox agent name) *(second build; CSV: `c_S1_*`)* | R40,000 | R82,000 | R122,000 | $\\frac{1,013 + 1,158}{20,960} = 0.104$ | +5.6 pp | R14,643 / pp | 1–2 wks dash / 3–9 mo MVD | [`d_S1_PIH_MVD`](../parameters_hub.qmd#tbl-detection) |\n| **Surveillance MVP — Option 1 + Option 2** | **R240,000** | **R137,000** | **R377,000** | $\\frac{1,013 + 1,779 + 1,158}{20,960} = 0.189$ | **+14.1 pp** | **R9,716 / pp** | **12 weeks** | [`d_surveillance_mvp`](../parameters_hub.qmd#tbl-detection) |\n| Option 3 — Community layer (Phase 2) *(pilot: FS + Gauteng; national conditional on pilot; **requires PIH/NMC intake from non-clinicians**; CSV: `c_S1b_*`)* | R1M–R3.5M | Pilot R0.8M/yr; national R2.5M/yr | R1.8M–R6.0M | 0.25–0.55 (working: 0.40) | +20 to +50 pp | R39,604–R49,801 / pp | 12 mo pilot → national | [`d_S1b_event_community_mid`](../parameters_hub.qmd) |\n| Option 4 — NMC CIF + agricultural extension *(bridge to coordination)* | R45,000 | R35,000/yr | R80,000 | n/a (not a coverage uplift) | enables source-removal hand-off | n/a | 4–8 wks | NDoH 2023 CIF guideline |\n| Option 5 — Sentinel toxicology *(agent attribution — distinct purpose, research-funded; CSV: `c_option6_*`)* | — (incl. in yr 1) | R3.6M/yr (5-site) | R1.2M (1-site pilot) | n/a (not a coverage uplift) | feeds product-banning evidence base | n/a | 6–12 mo pilot | — |\n\n: **Intermediate-outcome costing analysis — surveillance options, base-case.** Costs are 2024–25 ZAR; P_detect is the per-case detection probability anchored to the StatsSA MACOD 2023 mid-burden of 20,960 true cases/year. †**R / pp** = annual operating cost ÷ percentage-point gain in P_detect over status quo. Options 1 and 2 expand coverage within the formal health system. Option 5 is a parallel agent-attribution investment, not a coverage uplift. Option 4 is a data-quality / investigation-form upgrade that converts detected cases into source-removal hand-offs to the [Coordination brief](coordination_policy.qmd); it does not raise P_detect by design. Option 3 is a Phase 2 community layer, commissioned conditional on (i) MVP pilot data confirming a structural rural/informal gap (≥40% of severe cases in low-facility-access districts after 6 months of MVP operation) **and** (ii) PIH/NMC opening a non-clinician intake channel. {.striped .hover}\n\n::: {.callout-note collapse=\"true\"}\n## Audit trail — mini-budget backing the R137,000/yr Surveillance MVP operating cost {#sec-mvp-mini-budget}\n\n`c_surv_MVP_op` = R137,000/yr is a **deterministic sum** of two independent components. No distributional assumption is placed on the total; uncertainty propagates through the component gamma distributions in any PSA.\n\n| Component | CSV parameter | Annual (R) | Mini-budget |\n|:----------|:-------------|----------:|:-----------|\n| Option 2 — PIH dashboard + MVD (+ AfriTox harmonisation) | `c_S1_PIH_MVD_op` | 82,000 | [Option 2 audit trail](#sec-opt2-mini-budget) |\n| Option 1 — BChE auto-notification | `c_S2_BChE_autonotify_op` | 55,000 | [Option 1 audit trail](#sec-opt1-mini-budget) |\n| **Surveillance MVP total** | `c_surv_MVP_op` | **137,000** | |\n\n**No double-counting.** Option 1 (NHLS HL7 middleware, LIS IT maintenance, NHLS scientist QA, NICD alert triage) and Option 2 (PIH cloud hosting, MVD ETL pipeline, AfriTox harmonisation, QA, licences/SMS) sit on entirely separate operational pathways. The two NICD analyst allocations sum to ~0.05 FTE (Option 2: ~0.035 FTE; Option 1: ~0.015 FTE) — within the 0.2 FTE post already costed in the §7 Tab 1 NMC baseline. **The MVP does not require new headcount.**\n\n**Setup.** `c_surv_MVP_setup` = R240,000 (one-off) = `c_S1_PIH_MVD_setup` (R40,000) + `c_S2_BChE_autonotify_setup` (R200,000), the Option 1 LIS HL7 reconfiguration dominating. S0 is already operational; its setup is not double-counted here.\n:::\n\n::: {.callout-note}\n## Audit: parameter names for costing each policy option\n\nEvery annual and setup cost in this brief is linked to a row in [`amua_import_parameters_v4.csv`](../amua_import_parameters_v4.csv):\n\n| Option | Setup cost parameter | Operating cost parameter |\n|:-------|:--------------------|:------------------------|\n| Option 2 — PIH dashboard + MVD (+ AfriTox harmonisation) | `c_S1_PIH_MVD_setup` | `c_S1_PIH_MVD_op` |\n| Option 1 — BChE auto-notification | `c_S2_BChE_autonotify_setup` | `c_S2_BChE_autonotify_op` |\n| Surveillance MVP (Option 1 + Option 2) | `c_surv_MVP_setup` | `c_surv_MVP_op` |\n| Option 3 — community layer *(sensitivity: lo / mid / hi)* | `c_S1b_setup_mid` (lo/hi also exist) | `c_S1b_op_mid` (lo/hi also exist) |\n| S0 — NHLS-NMC IT feed (operational, in baseline) | `c_S0_NHLS_NMC_feed_setup` | `c_S0_NHLS_NMC_feed_op` |\n| Status quo (NICD program) | — | `c_status_quo_program` |\n\nParameter codes (`c_S1_*`, `c_S2_*`, `c_S1b_*`, `c_option6_*`) pre-date this brief's narrative reorder — see the cross-walk at the top of §5. Each option's mini-budget audit trail unpacks the figures into unit-cost and personnel-time components: [S0](#sec-s0-mini-budget) · [Option 1: BChE](#sec-opt1-mini-budget) · [Option 2: PIH MVD](#sec-opt2-mini-budget) · [MVP (1+2)](#sec-mvp-mini-budget) · [Option 3: Community](#sec-opt3-mini-budget) · [Option 5: Sentinel](#sec-opt5-mini-budget). All anchors are DPSA salary scales, NHLS Patterson grades, SITA contracting benchmarks, and AWS af-south-1 pricing — the same anchors as the §7 status-quo build-up. To update a cost: edit the CSV cell and re-render.\n:::\n\n## 6. Decision tree — from surveillance investment to detection uplift {#sec-decision-tree}\n\n::: {.callout-note collapse=\"true\"}\n## Audit trail — how every P_detect value in this brief was derived\n\nAll active P_detect values are **derived, not elicited**, on a single per-case scale. The arithmetic is auditable from three published anchors.\n\n### Step 1 — the implied true annual burden (denominator)\n\n| Anchor | Value | Source |\n|--|--:|--|\n| Annual NMC pesticide notifications | 1,013 | `n_nmc_annual` — NICD NMC Annual Report 2023 |\n| NMC-hospitalised case-fatality rate | 12.5 % | `cfr_headline_mid` (range 10–15 %) — Free State 2018-19 + NMC observed |\n| StatsSA MACOD pesticide-poisoning deaths/yr | 2,620 | `n_deaths_statssa_macod` — StatsSA Causes of Death, 2023: Table 4.12: Accidental poisoning by and exposure to noxious substance (X40-X49) |\n\nIf notified cases have CFR ≈ 12.5 %, then the *full* true burden satisfies $\\text{true cases} \\times \\text{CFR} = \\text{deaths}$, so\n\n$$\nN_\\text{true} \\;=\\; \\frac{2{,}620}{0.125} \\;=\\; \\mathbf{20{,}960}\\ \\text{cases/year} \\quad (\\texttt{n\\_true\\_burden\\_from\\_statssa\\_mid})\n$$\n\nThis is the **single denominator** used for every per-case P_detect below.\n\n### Step 2 — the per-stream numerators (2023 actuals)\n\n| Stream | Annual count | CSV row | Source |\n|--|--:|--|--|\n| NMC notifications | 1,013 | `n_nmc_annual` | NICD NMC Annual Report 2023 |\n| NHLS severe BChE inhibitions (<10 % of normal enzyme activity) | 1,779 | `n_nhls_severe_annual` | NHLS LIS 2023 (of 10,626 total tests) |\n| PIH clinician-initiated calls | 1,158 | `n_pih_annual` | PIH (Tygerberg) 2023 |\n\nThe three streams are treated as **mutually exclusive** in the base case (severe BChE ≠ NMC-notified ≠ PIH-called); the overlap-correction sensitivity is parameterised separately in the hub.\n\n### Step 3 — P_detect for each option\n\nEach option adds one or more streams to the NMC base. The numerator is the sum of streams reaching the surveillance system; the denominator is always 20,960.\n\n| Option | Streams summed | Arithmetic | P_detect | CSV row |\n|--|--|--:|--:|--|\n| Status quo | NMC only | $1{,}013 / 20{,}960$ | **0.048** | `d_status_quo` |\n| Option 2 — PIH MVD + dashboard | NMC + PIH | $(1{,}013 + 1{,}158) / 20{,}960 = 2{,}171 / 20{,}960$ | **0.104** | `d_S1_PIH_MVD` |\n| Option 1 — BChE auto-notify | NMC + NHLS severe | $(1{,}013 + 1{,}779) / 20{,}960 = 2{,}792 / 20{,}960$ | **0.133** | `d_S2_BChE_autonotify` |\n| **Surveillance MVP (Option 1 + Option 2)** | NMC + NHLS severe + PIH | $(1{,}013 + 1{,}779 + 1{,}158) / 20{,}960 = 3{,}950 / 20{,}960$ | **0.189** | `d_surveillance_mvp` |\n\n### Step 4 — CFR sensitivity bracket on the status-quo anchor\n\nThe denominator scales inversely with the CFR assumed for NMC-notified cases (CSV: `d_status_quo_lo`, `d_status_quo_hi`):\n\n- Lower bound (CFR = 0.10): $P_\\text{detect}^{SQ} = 1{,}013 \\times 0.10 / 2{,}620 = 0.039$ (implied burden 26,200)\n- Mid (CFR = 0.125): $P_\\text{detect}^{SQ} = 0.048$ (implied burden 20,960)\n- Upper (CFR = 0.15): $P_\\text{detect}^{SQ} = 1{,}013 \\times 0.15 / 2{,}620 = 0.058$ (implied burden 17,467)\n\nThe same CFR bracket applies proportionally to Option 1, Option 2 and the MVP — e.g. the MVP varies from 0.158 (CFR 0.15) to 0.236 (CFR 0.10).\n\n### Step 5 — why this replaces the v1 value of 0.45\n\nThe legacy v1 figure was an expert-elicited estimate on a different scale, derived from a model of spatial event sensitivity rather than per-case detection. That quantity answered a different question and is not comparable to a per-case detection probability. This brief now uses the **per-case** framing throughout — every value above is directly auditable from NICD + NHLS + PIH + StatsSA published figures and the canonical [`amua_import_parameters_v4.csv`](../amua_import_parameters_v4.csv).\n:::\n\n```{mermaid}\n%%| fig-cap: \"Surveillance investment decision tree — per-case detection uplift only. Each option raises P_detect, the share of true annual cases (~20,960 StatsSA-anchored mid-burden) that enter the surveillance system. The absolute burden impact of these uplifts depends on response-side parameters covered in the coordination and terbufos briefs. Option 5 (sentinel toxicology) is shown separately because it is an agent-attribution investment, not a coverage uplift. All numerical values pulled from amua_import_parameters_v4.csv at render time.\"\nflowchart TD\n    INV{Surveillance<br/>investment?} -->|None| SQ[Status quo<br/>P_detect = 0.048<br/>~5% of true cases]:::bad\n    INV -->|Option 2 only<br/>R82,000/yr| O1[+ PIH MVD<br/>P_detect = 0.104<br/>+5.6 pp vs SQ]:::warn\n    INV -->|Option 1 only<br/>R55,000/yr| O2[+ BChE auto-notify<br/>P_detect = 0.133<br/>+8.5 pp vs SQ]:::warn\n    INV -->|Option 1 + Option 2<br/>R137,000/yr| MVP[Surveillance MVP<br/>P_detect = 0.189<br/>+14.1 pp vs SQ]:::good\n    OPT5[Option 5 Sentinel toxicology<br/>agent attribution<br/><i>parallel investment —<br/>see Terbufos brief</i>]:::aux\n\n    classDef bad fill:#fdd,stroke:#cc0000,stroke-width:1.5px\n    classDef warn fill:#ffe9b3,stroke:#cc8800,stroke-width:1.5px\n    classDef good fill:#cfc,stroke:#060,stroke-width:1.5px\n    classDef aux fill:#e6f0ff,stroke:#3366cc,stroke-width:1.5px,stroke-dasharray: 5 5\n```\n\nThe tree reports **per-case detection uplift in percentage points**. The status-quo node is a **measurement** of the current detection gap (1,013 NMC notifications ÷ ~20,960 implied true cases), not a baseline from which deaths are counted as averted — surveillance has no response attached. Four detection inputs (`d_status_quo`, `d_S2_BChE_autonotify`, `d_S1_PIH_MVD`, `d_surveillance_mvp`) and three operating-cost rows (`c_S1_PIH_MVD_op`, `c_S2_BChE_autonotify_op`, `c_surv_MVP_op`) live in [`amua_import_parameters_v4.csv`](../amua_import_parameters_v4.csv) — edit the CSV and re-render. Option 5 sits outside this tree: it is an agent-attribution investment whose value is parameterised in the [Terbufos brief](terbufos_policy.qmd) and the [sentinel toxicology appendix](surveillance_concept_note.qmd).\n\n::: {.callout-note appearance=\"minimal\"}\n**Option 3 (Phase 2 community layer) is not modelled in this decision tree.** The MVP arm represents the ceiling achievable by linking existing administrative streams. Option 3 would require a new arm with P_detect drawn from `d_S1b_event_community_mid` = 0.40 (range 0.25–0.55) and annual operating cost drawn from `c_S1b_op_mid` = 1,500,000. It is excluded from the current tree because it is a Phase 2 option commissioned conditional on MVP pilot results, not a parallel near-term decision; and because its coordination cost depends on the net false-positive rate after two-tier triage (`p_fp_S1b_mid` = 0.35 gross; ~8–12% net) modelled in the [Coordination brief](coordination_policy.qmd).\n:::\n\n**For burden impact, see the next brief.** These P_detect figures feed the [Coordination brief](coordination_policy.qmd) decision tree, where response efficacy η converts detection into cases averted, and the [Terbufos brief](terbufos_policy.qmd), where regulatory restriction converts cases into deaths averted.\n\n## 7. Status-quo costing — what surveillance costs today {#sec-costing}\n\n::: {.callout-note icon=false}\n## How to read & edit this section\n\nThe tables below are the **average-cost economic build-up of running surveillance for pesticide poisoning today** (status quo, 2024–25 ZAR). They are sourced from an editable workbook — [`data/surveillance_costing.xlsx`](../data/surveillance_costing.xlsx) — with three sheets:\n\n- **`personnel`** — staff time (CTE × FTE %) by stream\n- **`system`** — infrastructure, hosting, SMS, reagents by stream\n- **`allocation`** — what share of each stream's total volume is pesticide-related (e.g. ~100 pesticide notifications/month out of ~10,000 total NMC notifications ≈ **0.84 %** of NMC platform OPEX is attributable to pesticide work)\n\nTo revise a unit cost or FTE, **edit a cell in the .xlsx and re-render** — every number below updates. The CSV (`amua_import_parameters_v4.csv`) remains the source of truth for *model* parameters and *marginal* policy-option costs (Option 1 / Option 2 / MVP). Salary anchors come from the DPSA scales (L10–11), NHLS Patterson grades (D/E), DoH OSD scales (MO, pharmacy), NICD recruitment notices and SITA contracting benchmarks; system anchors come from NHLS State Tender RT-262, AWS af-south-1 pricing, Clickatell/BulkSMS SA, and the NICD ICT budget — full citations are in each row's `source` column.\n:::\n\n\n::: {.cell}\n\n:::\n\n\n::: {.panel-tabset}\n\n### 1. Personnel\n\nAnnual cost-to-employer × FTE share attributable to pesticide surveillance, by stream.\n\n\n::: {#tbl-cost-personnel .cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"iphxxbamra\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iphxxbamra table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iphxxbamra thead, #iphxxbamra tbody, #iphxxbamra tfoot, #iphxxbamra tr, #iphxxbamra td, #iphxxbamra th {\n  border-style: none;\n}\n\n#iphxxbamra p {\n  margin: 0;\n  padding: 0;\n}\n\n#iphxxbamra .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 11px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iphxxbamra .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iphxxbamra .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iphxxbamra .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iphxxbamra .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iphxxbamra .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iphxxbamra .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iphxxbamra .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iphxxbamra .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iphxxbamra .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iphxxbamra .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iphxxbamra .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iphxxbamra .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iphxxbamra .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iphxxbamra .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iphxxbamra .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iphxxbamra .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iphxxbamra .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iphxxbamra .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iphxxbamra .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iphxxbamra .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iphxxbamra .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iphxxbamra .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iphxxbamra .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iphxxbamra .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iphxxbamra .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iphxxbamra .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iphxxbamra .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iphxxbamra .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iphxxbamra .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iphxxbamra .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iphxxbamra .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iphxxbamra .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iphxxbamra .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iphxxbamra .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iphxxbamra .gt_left {\n  text-align: left;\n}\n\n#iphxxbamra .gt_center {\n  text-align: center;\n}\n\n#iphxxbamra .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iphxxbamra .gt_font_normal {\n  font-weight: normal;\n}\n\n#iphxxbamra .gt_font_bold {\n  font-weight: bold;\n}\n\n#iphxxbamra .gt_font_italic {\n  font-style: italic;\n}\n\n#iphxxbamra .gt_super {\n  font-size: 65%;\n}\n\n#iphxxbamra .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iphxxbamra .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iphxxbamra .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iphxxbamra .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iphxxbamra .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iphxxbamra .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iphxxbamra .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#iphxxbamra .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#iphxxbamra div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"annual_cte_zar\">Annual CTE (R)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"fte_pct\">FTE %</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"annual_cost_zar\">Allocated cost (R/yr)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rationale\">Rationale</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"source\">Source</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"6\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Cross\">Cross</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">NICD data engineer (notification feeds)</th>\n<td headers=\"Cross stub_1_1 annual_cte_zar\" class=\"gt_row gt_right\">750,000</td>\n<td headers=\"Cross stub_1_1 fte_pct\" class=\"gt_row gt_right\">10.0%</td>\n<td headers=\"Cross stub_1_1 annual_cost_zar\" class=\"gt_row gt_right\">75,000</td>\n<td headers=\"Cross stub_1_1 rationale\" class=\"gt_row gt_left\">Maintains NHLS-&gt;NMC IT feed (now operational) and BChE auto-notify rules.</td>\n<td headers=\"Cross stub_1_1 source\" class=\"gt_row gt_left\">SITA / state IT contracting 2024</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">NICD biostatistician (signal detection)</th>\n<td headers=\"Cross stub_1_2 annual_cte_zar\" class=\"gt_row gt_right\">850,000</td>\n<td headers=\"Cross stub_1_2 fte_pct\" class=\"gt_row gt_right\">5.0%</td>\n<td headers=\"Cross stub_1_2 annual_cost_zar\" class=\"gt_row gt_right\">42,500</td>\n<td headers=\"Cross stub_1_2 rationale\" class=\"gt_row gt_left\">Spatial-temporal monitoring of pesticide signals across streams.</td>\n<td headers=\"Cross stub_1_2 source\" class=\"gt_row gt_left\">DPSA L11-12 scale 2024</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"6\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"NMC\">NMC</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">NICD epidemiologist (analyst)</th>\n<td headers=\"NMC stub_1_3 annual_cte_zar\" class=\"gt_row gt_right\">650,000</td>\n<td headers=\"NMC stub_1_3 fte_pct\" class=\"gt_row gt_right\">20.0%</td>\n<td headers=\"NMC stub_1_3 annual_cost_zar\" class=\"gt_row gt_right\">130,000</td>\n<td headers=\"NMC stub_1_3 rationale\" class=\"gt_row gt_left\">0.2 FTE reviewing/cleaning the ~12k annual NMC notifications; pesticide is ~1% of intake.</td>\n<td headers=\"NMC stub_1_3 source\" class=\"gt_row gt_left\">DPSA L10-11 scale 2024 + NICD recruitment</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Provincial communicable-disease coord.</th>\n<td headers=\"NMC stub_1_4 annual_cte_zar\" class=\"gt_row gt_right\">700,000</td>\n<td headers=\"NMC stub_1_4 fte_pct\" class=\"gt_row gt_right\">5.0%</td>\n<td headers=\"NMC stub_1_4 annual_cost_zar\" class=\"gt_row gt_right\">35,000</td>\n<td headers=\"NMC stub_1_4 rationale\" class=\"gt_row gt_left\">Triage of pesticide-flagged notifications across 9 provinces (cumulative 0.05 FTE).</td>\n<td headers=\"NMC stub_1_4 source\" class=\"gt_row gt_left\">DoH provincial OSD scale 2024</td></tr>\n    <tr><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Clinician notification time</th>\n<td headers=\"NMC stub_1_5 annual_cte_zar\" class=\"gt_row gt_right\">1,100,000</td>\n<td headers=\"NMC stub_1_5 fte_pct\" class=\"gt_row gt_right\">2.0%</td>\n<td headers=\"NMC stub_1_5 annual_cost_zar\" class=\"gt_row gt_right\">22,000</td>\n<td headers=\"NMC stub_1_5 rationale\" class=\"gt_row gt_left\">~10 min/notification x ~1,013 notifications/yr ~ 169 hr ~ 1.8% of one MO's year.</td>\n<td headers=\"NMC stub_1_5 source\" class=\"gt_row gt_left\">DoH MO Grade 1-3 OSD 2024</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"6\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"PIH\">PIH</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Poisons information specialist</th>\n<td headers=\"PIH stub_1_6 annual_cte_zar\" class=\"gt_row gt_right\">780,000</td>\n<td headers=\"PIH stub_1_6 fte_pct\" class=\"gt_row gt_right\">80.0%</td>\n<td headers=\"PIH stub_1_6 annual_cost_zar\" class=\"gt_row gt_right\">624,000</td>\n<td headers=\"PIH stub_1_6 rationale\" class=\"gt_row gt_left\">Pesticide is ~80% of PIH call volume (12000 of ~16000 clinician-initiated calls).</td>\n<td headers=\"PIH stub_1_6 source\" class=\"gt_row gt_left\">DoH pharmacy OSD 2024; PIH 2023 report</td></tr>\n    <tr><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_left gt_stub\">PIH clinical toxicologist (oversight)</th>\n<td headers=\"PIH stub_1_7 annual_cte_zar\" class=\"gt_row gt_right\">1,300,000</td>\n<td headers=\"PIH stub_1_7 fte_pct\" class=\"gt_row gt_right\">5.0%</td>\n<td headers=\"PIH stub_1_7 annual_cost_zar\" class=\"gt_row gt_right\">65,000</td>\n<td headers=\"PIH stub_1_7 rationale\" class=\"gt_row gt_left\">Senior medical review of complex pesticide consults.</td>\n<td headers=\"PIH stub_1_7 source\" class=\"gt_row gt_left\">Stellenbosch FoMHS appointment letters</td></tr>\n    <tr><th id=\"grand_summary_stub_1\" scope=\"row\" class=\"gt_row gt_left gt_stub gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">Total personnel</th>\n<td headers=\"grand_summary_stub_1 annual_cte_zar\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 fte_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 annual_cost_zar\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">993,500</td>\n<td headers=\"grand_summary_stub_1 rationale\" class=\"gt_row gt_left gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 source\" class=\"gt_row gt_left gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### 2. System\n\nInfrastructure, hosting, SMS, reagents and licences — unit cost × annual volume, then allocated to the pesticide share of stream activity where applicable.\n\n\n::: {#tbl-cost-system .cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jzbgtlwpds\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jzbgtlwpds table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jzbgtlwpds thead, #jzbgtlwpds tbody, #jzbgtlwpds tfoot, #jzbgtlwpds tr, #jzbgtlwpds td, #jzbgtlwpds th {\n  border-style: none;\n}\n\n#jzbgtlwpds p {\n  margin: 0;\n  padding: 0;\n}\n\n#jzbgtlwpds .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 11px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jzbgtlwpds .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jzbgtlwpds .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jzbgtlwpds .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jzbgtlwpds .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jzbgtlwpds .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzbgtlwpds .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jzbgtlwpds .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jzbgtlwpds .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jzbgtlwpds .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jzbgtlwpds .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jzbgtlwpds .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jzbgtlwpds .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jzbgtlwpds .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jzbgtlwpds .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jzbgtlwpds .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jzbgtlwpds .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jzbgtlwpds .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jzbgtlwpds .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzbgtlwpds .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jzbgtlwpds .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jzbgtlwpds .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jzbgtlwpds .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzbgtlwpds .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jzbgtlwpds .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jzbgtlwpds .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzbgtlwpds .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzbgtlwpds .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jzbgtlwpds .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzbgtlwpds .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jzbgtlwpds .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzbgtlwpds .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jzbgtlwpds .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzbgtlwpds .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jzbgtlwpds .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzbgtlwpds .gt_left {\n  text-align: left;\n}\n\n#jzbgtlwpds .gt_center {\n  text-align: center;\n}\n\n#jzbgtlwpds .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jzbgtlwpds .gt_font_normal {\n  font-weight: normal;\n}\n\n#jzbgtlwpds .gt_font_bold {\n  font-weight: bold;\n}\n\n#jzbgtlwpds .gt_font_italic {\n  font-style: italic;\n}\n\n#jzbgtlwpds .gt_super {\n  font-size: 65%;\n}\n\n#jzbgtlwpds .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jzbgtlwpds .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jzbgtlwpds .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jzbgtlwpds .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jzbgtlwpds .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jzbgtlwpds .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jzbgtlwpds .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jzbgtlwpds .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jzbgtlwpds div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"unit_cost_zar\">Unit cost (R)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"units_per_yr\">Units/yr</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"annual_cost_zar\">Raw cost (R/yr)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pesticide_share_pct\">Pesticide share</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pesticide_cost_zar\">Allocated cost (R/yr)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rationale\">Rationale</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"source\">Source</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"8\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"BChE\">BChE</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Butyrylcholinesterase reagent</th>\n<td headers=\"BChE stub_1_1 unit_cost_zar\" class=\"gt_row gt_right\">90</td>\n<td headers=\"BChE stub_1_1 units_per_yr\" class=\"gt_row gt_right\">10,626</td>\n<td headers=\"BChE stub_1_1 annual_cost_zar\" class=\"gt_row gt_right\">958,678</td>\n<td headers=\"BChE stub_1_1 pesticide_share_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"BChE stub_1_1 pesticide_cost_zar\" class=\"gt_row gt_right\">958,678</td>\n<td headers=\"BChE stub_1_1 rationale\" class=\"gt_row gt_left\">Per-assay reagent (NHLS State Tender RT-262 unit price).</td>\n<td headers=\"BChE stub_1_1 source\" class=\"gt_row gt_left\">NHLS State Tender RT-262 (2023)</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Sample courier / cold chain</th>\n<td headers=\"BChE stub_1_2 unit_cost_zar\" class=\"gt_row gt_right\">25</td>\n<td headers=\"BChE stub_1_2 units_per_yr\" class=\"gt_row gt_right\">10,626</td>\n<td headers=\"BChE stub_1_2 annual_cost_zar\" class=\"gt_row gt_right\">265,650</td>\n<td headers=\"BChE stub_1_2 pesticide_share_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"BChE stub_1_2 pesticide_cost_zar\" class=\"gt_row gt_right\">265,650</td>\n<td headers=\"BChE stub_1_2 rationale\" class=\"gt_row gt_left\">Per-specimen transport across NHLS network.</td>\n<td headers=\"BChE stub_1_2 source\" class=\"gt_row gt_left\">NHLS logistics tariff 2024</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">LIS rule engine middleware (HL7 router)</th>\n<td headers=\"BChE stub_1_3 unit_cost_zar\" class=\"gt_row gt_right\">180,000</td>\n<td headers=\"BChE stub_1_3 units_per_yr\" class=\"gt_row gt_right\">1</td>\n<td headers=\"BChE stub_1_3 annual_cost_zar\" class=\"gt_row gt_right\">180,000</td>\n<td headers=\"BChE stub_1_3 pesticide_share_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"BChE stub_1_3 pesticide_cost_zar\" class=\"gt_row gt_right\">180,000</td>\n<td headers=\"BChE stub_1_3 rationale\" class=\"gt_row gt_left\">Mirth Connect hosting + maintenance.</td>\n<td headers=\"BChE stub_1_3 source\" class=\"gt_row gt_left\">NHLS LIS team estimate</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"8\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Cross\">Cross</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Data warehouse / ETL (NICD)</th>\n<td headers=\"Cross stub_1_4 unit_cost_zar\" class=\"gt_row gt_right\">240,000</td>\n<td headers=\"Cross stub_1_4 units_per_yr\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Cross stub_1_4 annual_cost_zar\" class=\"gt_row gt_right\">240,000</td>\n<td headers=\"Cross stub_1_4 pesticide_share_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"Cross stub_1_4 pesticide_cost_zar\" class=\"gt_row gt_right\">240,000</td>\n<td headers=\"Cross stub_1_4 rationale\" class=\"gt_row gt_left\">Snowflake / Azure Synapse share for cross-stream linkage.</td>\n<td headers=\"Cross stub_1_4 source\" class=\"gt_row gt_left\">NICD data platform budget 2024</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"8\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"NMC\">NMC</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Dashboard hosting (Power BI Premium share)</th>\n<td headers=\"NMC stub_1_5 unit_cost_zar\" class=\"gt_row gt_right\">18,000</td>\n<td headers=\"NMC stub_1_5 units_per_yr\" class=\"gt_row gt_right\">1</td>\n<td headers=\"NMC stub_1_5 annual_cost_zar\" class=\"gt_row gt_right\">18,000</td>\n<td headers=\"NMC stub_1_5 pesticide_share_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"NMC stub_1_5 pesticide_cost_zar\" class=\"gt_row gt_right\">18,000</td>\n<td headers=\"NMC stub_1_5 rationale\" class=\"gt_row gt_left\">Pesticide pages on national NMC dashboard (estimate).</td>\n<td headers=\"NMC stub_1_5 source\" class=\"gt_row gt_left\">Microsoft ZA enterprise agreement 2024</td></tr>\n    <tr><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Outbound SMS to EHPs (notification alerts)</th>\n<td headers=\"NMC stub_1_6 unit_cost_zar\" class=\"gt_row gt_right\">0</td>\n<td headers=\"NMC stub_1_6 units_per_yr\" class=\"gt_row gt_right\">20,000</td>\n<td headers=\"NMC stub_1_6 annual_cost_zar\" class=\"gt_row gt_right\">3,000</td>\n<td headers=\"NMC stub_1_6 pesticide_share_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"NMC stub_1_6 pesticide_cost_zar\" class=\"gt_row gt_right\">3,000</td>\n<td headers=\"NMC stub_1_6 rationale\" class=\"gt_row gt_left\">~ poisoning case *10 SMSs  = 1000/year</td>\n<td headers=\"NMC stub_1_6 source\" class=\"gt_row gt_left\">Clickatell / BulkSMS ZA 2024</td></tr>\n    <tr><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_left gt_stub\">NMC platform hosting + maintenance</th>\n<td headers=\"NMC stub_1_7 unit_cost_zar\" class=\"gt_row gt_right\">180,000</td>\n<td headers=\"NMC stub_1_7 units_per_yr\" class=\"gt_row gt_right\">1</td>\n<td headers=\"NMC stub_1_7 annual_cost_zar\" class=\"gt_row gt_right\">180,000</td>\n<td headers=\"NMC stub_1_7 pesticide_share_pct\" class=\"gt_row gt_right\">0.8%</td>\n<td headers=\"NMC stub_1_7 pesticide_cost_zar\" class=\"gt_row gt_right\">1,512</td>\n<td headers=\"NMC stub_1_7 rationale\" class=\"gt_row gt_left\">Annual platform OPEX (NICD ICT budget line, pesticide share ~1%).</td>\n<td headers=\"NMC stub_1_7 source\" class=\"gt_row gt_left\">NICD ICT budget 2024</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"8\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"PIH\">PIH</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_8\" scope=\"row\" class=\"gt_row gt_left gt_stub\">AfriTox database licence (annual)</th>\n<td headers=\"PIH stub_1_8 unit_cost_zar\" class=\"gt_row gt_right\">120,000</td>\n<td headers=\"PIH stub_1_8 units_per_yr\" class=\"gt_row gt_right\">1</td>\n<td headers=\"PIH stub_1_8 annual_cost_zar\" class=\"gt_row gt_right\">120,000</td>\n<td headers=\"PIH stub_1_8 pesticide_share_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"PIH stub_1_8 pesticide_cost_zar\" class=\"gt_row gt_right\">120,000</td>\n<td headers=\"PIH stub_1_8 rationale\" class=\"gt_row gt_left\">Poison agent reference database; pesticide is ~15% of queries.</td>\n<td headers=\"PIH stub_1_8 source\" class=\"gt_row gt_left\">PIH AfriTox renewal invoice</td></tr>\n    <tr><th id=\"stub_1_9\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Dashboard hosting (Tygerberg cloud VM)</th>\n<td headers=\"PIH stub_1_9 unit_cost_zar\" class=\"gt_row gt_right\">42,000</td>\n<td headers=\"PIH stub_1_9 units_per_yr\" class=\"gt_row gt_right\">1</td>\n<td headers=\"PIH stub_1_9 annual_cost_zar\" class=\"gt_row gt_right\">42,000</td>\n<td headers=\"PIH stub_1_9 pesticide_share_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"PIH stub_1_9 pesticide_cost_zar\" class=\"gt_row gt_right\">42,000</td>\n<td headers=\"PIH stub_1_9 rationale\" class=\"gt_row gt_left\">AWS af-south-1 small VM + storage + backup.</td>\n<td headers=\"PIH stub_1_9 source\" class=\"gt_row gt_left\">AWS af-south-1 pricing 2024</td></tr>\n    <tr><th id=\"stub_1_10\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Telephony (toll-free 0861-555-777)</th>\n<td headers=\"PIH stub_1_10 unit_cost_zar\" class=\"gt_row gt_right\">85,000</td>\n<td headers=\"PIH stub_1_10 units_per_yr\" class=\"gt_row gt_right\">1</td>\n<td headers=\"PIH stub_1_10 annual_cost_zar\" class=\"gt_row gt_right\">72,250</td>\n<td headers=\"PIH stub_1_10 pesticide_share_pct\" class=\"gt_row gt_right\">15.0%</td>\n<td headers=\"PIH stub_1_10 pesticide_cost_zar\" class=\"gt_row gt_right\">10,866</td>\n<td headers=\"PIH stub_1_10 rationale\" class=\"gt_row gt_left\">Toll-free line annual cost (pesticide share ~15%).</td>\n<td headers=\"PIH stub_1_10 source\" class=\"gt_row gt_left\">Telkom toll-free annual 2024</td></tr>\n    <tr><th id=\"grand_summary_stub_1\" scope=\"row\" class=\"gt_row gt_left gt_stub gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">Total system (pesticide-allocated)</th>\n<td headers=\"grand_summary_stub_1 unit_cost_zar\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 units_per_yr\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 annual_cost_zar\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 pesticide_share_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 pesticide_cost_zar\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">1,839,706</td>\n<td headers=\"grand_summary_stub_1 rationale\" class=\"gt_row gt_left gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 source\" class=\"gt_row gt_left gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### 3. Allocation factors\n\nWhy these proportions matter: platform-level OPEX (NMC hosting, PIH telephony, AfriTox licence) covers *all* notifiable / call activity, of which pesticide poisoning is only a slice. The denominator drives the allocated cost.\n\n\n::: {#tbl-cost-allocation .cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vwrnlndvdz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vwrnlndvdz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vwrnlndvdz thead, #vwrnlndvdz tbody, #vwrnlndvdz tfoot, #vwrnlndvdz tr, #vwrnlndvdz td, #vwrnlndvdz th {\n  border-style: none;\n}\n\n#vwrnlndvdz p {\n  margin: 0;\n  padding: 0;\n}\n\n#vwrnlndvdz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 11px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vwrnlndvdz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vwrnlndvdz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vwrnlndvdz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vwrnlndvdz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vwrnlndvdz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vwrnlndvdz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vwrnlndvdz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vwrnlndvdz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vwrnlndvdz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vwrnlndvdz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vwrnlndvdz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vwrnlndvdz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vwrnlndvdz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vwrnlndvdz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vwrnlndvdz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vwrnlndvdz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vwrnlndvdz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vwrnlndvdz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vwrnlndvdz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vwrnlndvdz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vwrnlndvdz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vwrnlndvdz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vwrnlndvdz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vwrnlndvdz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vwrnlndvdz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vwrnlndvdz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vwrnlndvdz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vwrnlndvdz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vwrnlndvdz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vwrnlndvdz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vwrnlndvdz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vwrnlndvdz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vwrnlndvdz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vwrnlndvdz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vwrnlndvdz .gt_left {\n  text-align: left;\n}\n\n#vwrnlndvdz .gt_center {\n  text-align: center;\n}\n\n#vwrnlndvdz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vwrnlndvdz .gt_font_normal {\n  font-weight: normal;\n}\n\n#vwrnlndvdz .gt_font_bold {\n  font-weight: bold;\n}\n\n#vwrnlndvdz .gt_font_italic {\n  font-style: italic;\n}\n\n#vwrnlndvdz .gt_super {\n  font-size: 65%;\n}\n\n#vwrnlndvdz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vwrnlndvdz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vwrnlndvdz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vwrnlndvdz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vwrnlndvdz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vwrnlndvdz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vwrnlndvdz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vwrnlndvdz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vwrnlndvdz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pesticide_count_yr\">Pesticide (n/yr)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"total_count_yr\">Total (n/yr)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"allocation_pct\">Share</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rationale\">Rationale</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"source\">Source</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"6\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"NMC\">NMC</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Notifications: pesticide / all notifiable</th>\n<td headers=\"NMC stub_1_1 pesticide_count_yr\" class=\"gt_row gt_right\">1,013</td>\n<td headers=\"NMC stub_1_1 total_count_yr\" class=\"gt_row gt_right\">120,000</td>\n<td headers=\"NMC stub_1_1 allocation_pct\" class=\"gt_row gt_right\">0.84%</td>\n<td headers=\"NMC stub_1_1 rationale\" class=\"gt_row gt_left\">~100 pesticide notifications/month vs ~10,000/month all notifiable conditions.</td>\n<td headers=\"NMC stub_1_1 source\" class=\"gt_row gt_left\">NICD NMC Annual Report 2023</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"6\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"PIH\">PIH</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Calls: pesticide / clinician-initiated total</th>\n<td headers=\"PIH stub_1_2 pesticide_count_yr\" class=\"gt_row gt_right\">17,000</td>\n<td headers=\"PIH stub_1_2 total_count_yr\" class=\"gt_row gt_right\">12,000</td>\n<td headers=\"PIH stub_1_2 allocation_pct\" class=\"gt_row gt_right\">15.04%</td>\n<td headers=\"PIH stub_1_2 rationale\" class=\"gt_row gt_left\">Pesticide is ~15% of PIH clinician-initiated call volume.</td>\n<td headers=\"PIH stub_1_2 source\" class=\"gt_row gt_left\">PIH Annual Report 2023</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"6\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"BChE\">BChE</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">BChE tests: pesticide-suspected / all BChE</th>\n<td headers=\"BChE stub_1_3 pesticide_count_yr\" class=\"gt_row gt_right\">10,626</td>\n<td headers=\"BChE stub_1_3 total_count_yr\" class=\"gt_row gt_right\">10,626</td>\n<td headers=\"BChE stub_1_3 allocation_pct\" class=\"gt_row gt_right\">100.00%</td>\n<td headers=\"BChE stub_1_3 rationale\" class=\"gt_row gt_left\">BChE testing is essentially pesticide-specific; allocation ~100%.</td>\n<td headers=\"BChE stub_1_3 source\" class=\"gt_row gt_left\">NHLS LIS 2023</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### 4. Status-quo total\n\nStatus-quo annual cost of running pesticide-poisoning surveillance across the three streams, summed from the personnel and system sheets.\n\n\n::: {#tbl-cost-total .cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"djoctuanzq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#djoctuanzq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#djoctuanzq thead, #djoctuanzq tbody, #djoctuanzq tfoot, #djoctuanzq tr, #djoctuanzq td, #djoctuanzq th {\n  border-style: none;\n}\n\n#djoctuanzq p {\n  margin: 0;\n  padding: 0;\n}\n\n#djoctuanzq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 11px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#djoctuanzq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#djoctuanzq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#djoctuanzq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#djoctuanzq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#djoctuanzq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#djoctuanzq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#djoctuanzq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#djoctuanzq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#djoctuanzq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#djoctuanzq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#djoctuanzq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#djoctuanzq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#djoctuanzq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#djoctuanzq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#djoctuanzq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#djoctuanzq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#djoctuanzq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#djoctuanzq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#djoctuanzq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#djoctuanzq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#djoctuanzq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#djoctuanzq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#djoctuanzq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#djoctuanzq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#djoctuanzq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#djoctuanzq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#djoctuanzq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#djoctuanzq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#djoctuanzq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#djoctuanzq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#djoctuanzq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#djoctuanzq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#djoctuanzq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#djoctuanzq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#djoctuanzq .gt_left {\n  text-align: left;\n}\n\n#djoctuanzq .gt_center {\n  text-align: center;\n}\n\n#djoctuanzq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#djoctuanzq .gt_font_normal {\n  font-weight: normal;\n}\n\n#djoctuanzq .gt_font_bold {\n  font-weight: bold;\n}\n\n#djoctuanzq .gt_font_italic {\n  font-style: italic;\n}\n\n#djoctuanzq .gt_super {\n  font-size: 65%;\n}\n\n#djoctuanzq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#djoctuanzq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#djoctuanzq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#djoctuanzq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#djoctuanzq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#djoctuanzq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#djoctuanzq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#djoctuanzq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#djoctuanzq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"personnel_zar\">Personnel (R/yr)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"system_zar\">System (R/yr)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"total_zar\">Total (R/yr)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">BChE</th>\n<td headers=\"stub_1_1 personnel_zar\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stub_1_1 system_zar\" class=\"gt_row gt_right\">1,404,328</td>\n<td headers=\"stub_1_1 total_zar\" class=\"gt_row gt_right\">1,404,328</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">PIH</th>\n<td headers=\"stub_1_2 personnel_zar\" class=\"gt_row gt_right\">689,000</td>\n<td headers=\"stub_1_2 system_zar\" class=\"gt_row gt_right\">172,866</td>\n<td headers=\"stub_1_2 total_zar\" class=\"gt_row gt_right\">861,866</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Cross</th>\n<td headers=\"stub_1_3 personnel_zar\" class=\"gt_row gt_right\">117,500</td>\n<td headers=\"stub_1_3 system_zar\" class=\"gt_row gt_right\">240,000</td>\n<td headers=\"stub_1_3 total_zar\" class=\"gt_row gt_right\">357,500</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\">NMC</th>\n<td headers=\"stub_1_4 personnel_zar\" class=\"gt_row gt_right\">187,000</td>\n<td headers=\"stub_1_4 system_zar\" class=\"gt_row gt_right\">22,512</td>\n<td headers=\"stub_1_4 total_zar\" class=\"gt_row gt_right\">209,512</td></tr>\n    <tr><th id=\"grand_summary_stub_1\" scope=\"row\" class=\"gt_row gt_left gt_stub gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">Status-quo total</th>\n<td headers=\"grand_summary_stub_1 personnel_zar\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">993,500</td>\n<td headers=\"grand_summary_stub_1 system_zar\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">1,839,706</td>\n<td headers=\"grand_summary_stub_1 total_zar\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">2,833,206</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### 5. Marginal cost of policy options\n\nFor comparison: the **additional** annual operating cost of each surveillance investment, pulled directly from [`amua_import_parameters_v4.csv`](../amua_import_parameters_v4.csv) (these are the same numbers driving the decision tree in §6).\n\n\n::: {#tbl-cost-marginal .cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gsgeumqsbb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gsgeumqsbb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gsgeumqsbb thead, #gsgeumqsbb tbody, #gsgeumqsbb tfoot, #gsgeumqsbb tr, #gsgeumqsbb td, #gsgeumqsbb th {\n  border-style: none;\n}\n\n#gsgeumqsbb p {\n  margin: 0;\n  padding: 0;\n}\n\n#gsgeumqsbb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 11px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gsgeumqsbb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gsgeumqsbb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gsgeumqsbb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gsgeumqsbb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gsgeumqsbb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsgeumqsbb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gsgeumqsbb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gsgeumqsbb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gsgeumqsbb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gsgeumqsbb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gsgeumqsbb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gsgeumqsbb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gsgeumqsbb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gsgeumqsbb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gsgeumqsbb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gsgeumqsbb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gsgeumqsbb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gsgeumqsbb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsgeumqsbb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gsgeumqsbb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gsgeumqsbb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gsgeumqsbb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsgeumqsbb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gsgeumqsbb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gsgeumqsbb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsgeumqsbb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsgeumqsbb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gsgeumqsbb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsgeumqsbb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gsgeumqsbb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsgeumqsbb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gsgeumqsbb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsgeumqsbb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gsgeumqsbb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsgeumqsbb .gt_left {\n  text-align: left;\n}\n\n#gsgeumqsbb .gt_center {\n  text-align: center;\n}\n\n#gsgeumqsbb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gsgeumqsbb .gt_font_normal {\n  font-weight: normal;\n}\n\n#gsgeumqsbb .gt_font_bold {\n  font-weight: bold;\n}\n\n#gsgeumqsbb .gt_font_italic {\n  font-style: italic;\n}\n\n#gsgeumqsbb .gt_super {\n  font-size: 65%;\n}\n\n#gsgeumqsbb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gsgeumqsbb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gsgeumqsbb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gsgeumqsbb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gsgeumqsbb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gsgeumqsbb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gsgeumqsbb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gsgeumqsbb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gsgeumqsbb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"setup_zar\">Setup (R, one-off)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"op_zar\">Operating (R/yr)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"setup_param\">CSV: setup</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"op_param\">CSV: operating</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Option 2 — PIH dashboard + MVD (+ AfriTox harmonisation)</th>\n<td headers=\"stub_1_1 setup_zar\" class=\"gt_row gt_right\">40,000</td>\n<td headers=\"stub_1_1 op_zar\" class=\"gt_row gt_right\">82,000</td>\n<td headers=\"stub_1_1 setup_param\" class=\"gt_row gt_left\">c_S1_PIH_MVD_setup</td>\n<td headers=\"stub_1_1 op_param\" class=\"gt_row gt_left\">c_S1_PIH_MVD_op</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Option 1 — BChE auto-notification</th>\n<td headers=\"stub_1_2 setup_zar\" class=\"gt_row gt_right\">200,000</td>\n<td headers=\"stub_1_2 op_zar\" class=\"gt_row gt_right\">55,000</td>\n<td headers=\"stub_1_2 setup_param\" class=\"gt_row gt_left\">c_S2_BChE_autonotify_setup</td>\n<td headers=\"stub_1_2 op_param\" class=\"gt_row gt_left\">c_S2_BChE_autonotify_op</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Surveillance MVP (Option 1 + Option 2)</th>\n<td headers=\"stub_1_3 setup_zar\" class=\"gt_row gt_right\">240,000</td>\n<td headers=\"stub_1_3 op_zar\" class=\"gt_row gt_right\">137,000</td>\n<td headers=\"stub_1_3 setup_param\" class=\"gt_row gt_left\">c_surv_MVP_setup</td>\n<td headers=\"stub_1_3 op_param\" class=\"gt_row gt_left\">c_surv_MVP_op</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\">S0 — NHLS-NMC IT feed (now operational)</th>\n<td headers=\"stub_1_4 setup_zar\" class=\"gt_row gt_right\">80,000</td>\n<td headers=\"stub_1_4 op_zar\" class=\"gt_row gt_right\">60,000</td>\n<td headers=\"stub_1_4 setup_param\" class=\"gt_row gt_left\">c_S0_NHLS_NMC_feed_setup</td>\n<td headers=\"stub_1_4 op_param\" class=\"gt_row gt_left\">c_S0_NHLS_NMC_feed_op</td></tr>\n    <tr><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Option 3 — community layer (sensitivity, lo)</th>\n<td headers=\"stub_1_5 setup_zar\" class=\"gt_row gt_right\">1,000,000</td>\n<td headers=\"stub_1_5 op_zar\" class=\"gt_row gt_right\">800,000</td>\n<td headers=\"stub_1_5 setup_param\" class=\"gt_row gt_left\">c_S1b_setup_lo</td>\n<td headers=\"stub_1_5 op_param\" class=\"gt_row gt_left\">c_S1b_op_lo</td></tr>\n    <tr><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Option 3 — community layer (sensitivity, mid)</th>\n<td headers=\"stub_1_6 setup_zar\" class=\"gt_row gt_right\">2,000,000</td>\n<td headers=\"stub_1_6 op_zar\" class=\"gt_row gt_right\">1,500,000</td>\n<td headers=\"stub_1_6 setup_param\" class=\"gt_row gt_left\">c_S1b_setup_mid</td>\n<td headers=\"stub_1_6 op_param\" class=\"gt_row gt_left\">c_S1b_op_mid</td></tr>\n    <tr><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Option 3 — community layer (sensitivity, hi)</th>\n<td headers=\"stub_1_7 setup_zar\" class=\"gt_row gt_right\">3,500,000</td>\n<td headers=\"stub_1_7 op_zar\" class=\"gt_row gt_right\">2,500,000</td>\n<td headers=\"stub_1_7 setup_param\" class=\"gt_row gt_left\">c_S1b_setup_hi</td>\n<td headers=\"stub_1_7 op_param\" class=\"gt_row gt_left\">c_S1b_op_hi</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n:::\n\n**Headline read.** The status-quo surveillance system already costs roughly **R2,833,206/yr** in personnel + pesticide-allocated system spend across NMC, PIH, and NHLS BChE — borne almost entirely by NDoH, NHLS, and Stellenbosch FoMHS rather than appearing as a line item. Against that base, the **Surveillance MVP (Option 1 + Option 2) adds only R137,000/yr** — a **4.8% uplift on current spend** for a **+14.1 pp** jump in P_detect.\n\n## 8. Implementation considerations\n\n| Component | Lead agency | Year-1 cost | Critical path |\n|:----------|:------------|------------:|:--------------|\n| Option 2 — PIH dashboard | PIH (Tygerberg) + NICD | 82,000 | Daily extract + hosting; MVD workshop |\n| Option 1 — BChE auto-notify | NHLS LIS team | 55,000 | LIS rule configuration; QA review |\n| Option 5 — Sentinel toxicology | NHLS clinical chemistry + sentinel hospital | R1,200,000 pilot | Lab method validation; sample logistics |\n| Option 3 — Community layer (Phase 2) *(pilot: FS + Gauteng; commission after Month 6 MVP review)* | NICD + provincial DoH EHPs | Pilot: R1M setup + R0.8M/yr; national: R3.5M setup + R2.5M/yr | CHW two-tier triage training, mobile checklist app, EHP call-back protocol, QA pipeline |\n\n**Privacy & legal.** The PIH-to-NMC MVD feed transmits personal health information (age-band, sex, geography, clinical data) and must use a **secure, authenticated HTTPS/TLS API** — no plaintext or email transmission. De-identification before transmission is mandatory (age-band not exact age; province/district not street address; no name or phone number; see Appendix A2). The NHLS BChE auto-notify feed transmits result-level data with patient identifiers to NMC, consistent with the existing NMC notification pathway, and must use the same secure HL7-over-TLS channel. Both flows are POPIA-compliant under existing Section 90 NHA authority. **No new legislation required.**\n\n**Risks.** (i) Low BChE testing uptake by clinicians — Option 1 fires only on tests ordered. (ii) Data-quality drift if facility metadata is incomplete. (iii) Capacity bottleneck at provincial response level — the [Coordination brief](coordination_policy.qmd) addresses this.\n\n## 9. Recommended next step\n\n**Adopt the Surveillance MVP (Option 1 + Option 2) and pilot in 3 provinces (Gauteng, Western Cape, KZN) for 6 months.** Approximate pilot budget: **~R137,000 operating** (NHLS–NMC IT feed is now operational). Lead agency: NICD as national coordinator.\n\n- **Weeks 1–2:** Option 2 PIH dashboard live; Option 1 BChE LIS configuration begins.\n- **Months 1–3:** Option 2 MVD workshop with PIH finalised; Option 1 BChE auto-notify QA review completed.\n- **Month 6:** Evaluate against (a) completeness of NHLS severe results in NMC and (b) signal-to-investigation latency.\n- **Month 9:** Add Option 5 sentinel toxicology site, funded from a separate research-surveillance stream.\n- **Month 12:** Review MVP geographic distribution. If ≥40% of severe cases originate in low-facility-access districts, commission the Option 3 Phase 2 pilot (Free State + Gauteng; ~R1M setup + R0.8M/yr operating).\n\nThe coordination side — how NICD, EHPs, DALRRD, and provincial response teams act on the improved signal — is in the [Coordination brief](coordination_policy.qmd). The product-specific regulatory action Option 5 makes possible is in the [Terbufos brief](terbufos_policy.qmd).\n\n---\n\n::: {.footer-cta}\n**Companion briefs:** [Coordination](coordination_policy.qmd) · [Terbufos restriction](terbufos_policy.qmd) · [Decision Model](decision_model.qmd) · [Costing Analysis](costing_analysis.qmd)\n\n**Technical appendices:** [A — Surveillance decision analysis](../analysis_report_v2.qmd) · [D — Sentinel toxicology (Option 5 deep dive)](surveillance_concept_note.qmd)\n\n**Appendices (this brief):** [Appendix A — MVD specifications (NMC + PIH)](#sec-mvd)\n:::\n\n---\n\n## Appendix A — Minimum Viable Dataset (MVD) specifications {#sec-mvd}\n\n### A1. NMC MVD — required fields for PIH-to-NMC structured feed\n\nThe table below specifies the **Minimum Viable Dataset** for ingesting PIH clinician-initiated calls into the National Microbiology and Communicable Disease Notification (NMC) system as a structured surveillance stream. These fields must be captured at the point of PIH call (what the *caller reports*) and confirmed/updated by the notifying clinician (what the clinician *confirms*). The pesticide-type and circumstances classification is drawn from the existing NMC notification form; the MVD mandates their structured capture for every pesticide-poisoning case.\n\n::: {.callout-note appearance=\"minimal\"}\n**Agent-name capture is mandatory.** Both PIH and NMC must record the **AfriTox product name** for every case. NMC should add a structured agent drop-down (pesticide class → active ingredient → AfriTox product name) to the NDoH-hosted notification form to make this reciprocal with PIH. Cases with agent \"unknown\" are acceptable (do not exclude), but the field must be present.\n:::\n\n**Pesticide type (structured drop-down — mandatory)**\n\n| Code | Pesticide type | Example active ingredients |\n|:-----|:--------------|:--------------------------|\n| OPC  | Organophosphates | Chlorpyrifos, dimethoate, profenofos |\n| CAR  | Carbamates | Aldicarb, methomyl, carbofuran |\n| PYR  | Pyrethroids | Cypermethrin, deltamethrin, permethrin |\n| PAR  | Paraquat & Diquat | Paraquat dichloride, diquat dibromide |\n| PHO  | Phosphine & Phosphides | Aluminium phosphide, zinc phosphide |\n| NEO  | Neonicotinoid Insecticides | Imidacloprid, thiamethoxam |\n| ORG  | Organochlorines | DDT, endosulfan, lindane |\n| CPH  | Chlorophenoxy Herbicides | 2,4-D, MCPA, triclopyr |\n| GLY  | Glyphosates | Glyphosate-IPA, glyphosate-ammonium |\n| COU  | Coumarin Rodenticides | Brodifacoum, bromadiolone, chlorophacinone |\n| FOR  | Formamidines | Amitraz, chlordimeform |\n| FUN  | Fungicides — Unspecified | — |\n| HRB  | Herbicides — Unspecified | — |\n| INS  | Insecticides — Unspecified | — |\n| DEE  | Diethyl-m-toluamide (DEET) | DEET |\n| AFX  | Aflatoxin | Aflatoxin B1/B2/G1/G2 |\n| NAP  | Naphthalene (marbles) | Naphthalene |\n| OTH  | Other | (free text required) |\n| UNK  | Unknown | — |\n\n: NMC pesticide-type classification. Source: existing NMC notification form. AfriTox product-name lookup linked to each class at data entry. {#tbl-mvd-pesticide-type .striped .hover}\n\n**Circumstances / intent (structured drop-down — mandatory)**\n\n| Code | Circumstance | ICD-10 intent mapping |\n|:-----|:------------|:----------------------|\n| UI-OCC | Unintentional — Occupational | X48 (farm, pest control, industrial) |\n| UI-DOM | Unintentional — Domestic | X40–X44 |\n| INT-SH | Intentional — Self-harm | X60–X69 |\n| INT-AH | Intentional — Assault/Homicide | X85–X90 |\n| ENV-DR | Environmental / Drift | X48 (environmental context) |\n| ACC-CN | Accidental contamination (food/water) | X49 |\n| UNK-UI | Unknown / Under investigation | — |\n\n: NMC circumstances/intent classification. Source: existing NMC notification form. Must be captured at both PIH call (caller-reported) and NMC notification (clinician-confirmed); these may differ and both values should be retained. {#tbl-mvd-circumstances .striped .hover}\n\n**Remaining mandatory MVD fields for NMC notification**\n\n| Field | Format | Notes |\n|:------|:-------|:------|\n| Case date (date of exposure / presentation) | ISO 8601 (YYYY-MM-DD) | Date of poisoning event or first clinical presentation |\n| Facility / point of care | Facility NHIS code | Or \"PIH referral\" if never attended facility |\n| Province | 2-letter code (e.g. WC, GP, FS) | Province of exposure, not of facility |\n| District | LIM-code or free text | For geographic clustering analysis |\n| Outcome at notification | Survived / Died / Unknown | MUST be updated if outcome changes |\n| AfriTox product name | Free text + drop-down lookup | Mandatory field; \"unknown\" is valid if product unidentified |\n| Notification source | NMC-direct / PIH-MVD / NHLS-autonotify | Tracks which stream generated the case |\n\n: MVD — additional mandatory fields. These are the minimum set required to (a) link across streams, (b) support geographic clustering, and (c) support product-specific attribution. Fields marked \"unknown\" are acceptable; empty/null is not. {#tbl-mvd-core .striped .hover}\n\n---\n\n### A2. PIH MVD — required fields including demographic variables\n\nPIH captures call data in its existing Toxicology Management System (TMS). The following fields must be structured (coded, not free-text) in the PIH-to-NMC MVD feed to ensure the data are surveillance-ready. **Demographic variables are mandatory** — they are the primary tool for detecting vulnerable sub-populations (occupational exposure in farm workers, paediatric accidental ingestion, gender asymmetry in intentional self-harm) and for geographic clustering.\n\n| Domain | Field | Format | Rationale |\n|:-------|:------|:-------|:---------|\n| **Demographics** | Age | Integer (years) or age-band (0–4, 5–14, 15–24, 25–34, 35–49, 50–64, ≥65) | Paediatric vs. adult exposure patterns differ; required for burden modelling |\n| **Demographics** | Sex | M / F / Unknown | Gender asymmetry in intentional self-harm is a known signal |\n| **Demographics** | Caller type | Patient / Clinician / Caregiver / Other | Distinguishes clinician-initiated (surveillance-relevant) from lay calls |\n| **Demographics** | Occupation (if stated) | Free text + coded: farm worker / pesticide applicator / domestic worker / child / other / unknown | Occupational exposure is systematically under-identified |\n| **Geography** | Province of caller | 2-letter code | Derived from caller area code or stated by caller |\n| **Geography** | District (if known) | LIM-code or free text | Optional but captures rural/urban signal |\n| **Exposure** | Pesticide type | NMC drop-down (see A1) | Must align with NMC classification for linkage |\n| **Exposure** | AfriTox product name | Free text + drop-down lookup | Mandatory; \"unknown\" valid |\n| **Exposure** | Route | Ingestion / Dermal / Inhalation / Ocular / Unknown | Route influences clinical management and surveillance signal |\n| **Circumstances** | Intent | NMC circumstance codes (see A1) | Caller-reported; may be updated by treating clinician |\n| **Clinical** | Severity (caller-assessed) | Mild / Moderate / Severe / Unknown | PSS (Poisoning Severity Score) if TMS supports it |\n| **Clinical** | Referred to facility | Yes / No / Unknown | Links call record to potential NMC notification |\n| **Linkage** | NMC notification number | Free text (if referred and notified) | Enables de-duplicated case linking across PIH + NMC streams |\n| **System** | Call date and time | ISO 8601 (YYYY-MM-DDTHH:MM) | Required for temporal clustering and latency audit |\n| **System** | TMS call ID | Alphanumeric | Internal identifier; retained for audit; not transmitted externally |\n\n: PIH MVD — full field specification including demographic variables. Demographic fields (age, sex, caller type, occupation) are mandatory for all calls; a structured unknown code is required if data are not available — blank fields will be rejected in the NMC ingest pipeline. {#tbl-pih-mvd .striped .hover}\n\n::: {.callout-note appearance=\"minimal\"}\n**POPIA compliance and secure transmission.** All PIH-to-NMC transmissions must be de-identified before transmission: no name, phone number, or exact address. Age-band (not exact age), province/district (not street address), and anonymised TMS call ID are sufficient for surveillance linkage and comply with Section 90 of the National Health Act (2003) and POPIA. Exact age may be retained internally within PIH TMS for clinical purposes and transmitted as age-band only.\n\nDe-identified health data still constitutes personal information under POPIA. The PIH-to-NMC feed **must be implemented as a secure HTTPS/TLS API with mutual authentication** (client certificate or token-based) between the PIH TMS and the NMC ingest endpoint. Transmission over email, FTP, or unencrypted HTTP is not acceptable. The MVD ingest pipeline (line item 4 in the Option 2 operating cost) includes the cost of maintaining this secure channel; the one-off setup cost (`c_S1_PIH_MVD_setup` = R40,000) must include API security configuration and penetration testing as a go-live requirement.\n:::\n\n::: {.callout-tip appearance=\"minimal\"}\n**AfriTox agent-name harmonisation.** Both PIH (TMS) and NMC (notification form) must use the same AfriTox product-name controlled vocabulary so product-level attribution is consistent across streams. The Option 2 MVD workshop (Months 1–3) should produce a shared AfriTox lookup table embedded in both systems — a single workshop yields cross-stream agent attribution at scale.\n:::\n",
    "supporting": [
      "surveillance_policy_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}