<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="D2P Project Team">
<meta name="dcterms.date" content="2025-09-05">

<title>Fixing What We Can’t See – D2P Project</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-22206e84c2e6f955c0d8fc54fe8645d2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">D2P Project</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../posts.html"> 
<span class="menu-text">Policy Briefs</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-technical--misc" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Technical &amp; Misc</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-technical--misc">    
        <li>
    <a class="dropdown-item" href="../posts/overall_policy_model_v3.html">
 <span class="dropdown-text">Overall Policy Model</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../posts/decision_model.html">
 <span class="dropdown-text">Decision Tree Model</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../posts/costing_analysis.html">
 <span class="dropdown-text">Costing Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../parameters_hub.html">
 <span class="dropdown-text">Parameters Hub</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../parameter_playground.html">
 <span class="dropdown-text">Parameter Playground</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../glossary.html">
 <span class="dropdown-text">Glossary</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../analysis_report_v2.html">
 <span class="dropdown-text">Appendix A — Surveillance (decision analysis)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../technical_appendix_coordination.html">
 <span class="dropdown-text">Appendix B — Coordination (joint-probability model)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../technical_appendix_terbufos.html">
 <span class="dropdown-text">Appendix C — Terbufos (bracketed deaths averted)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../posts/surveillance_concept_note.html">
 <span class="dropdown-text">Appendix D — Sentinel toxicology (live-patient testing)</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:contact@example.com"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#the-problem" id="toc-the-problem" class="nav-link active" data-scroll-target="#the-problem">The Problem</a></li>
  <li><a href="#root-cause" id="toc-root-cause" class="nav-link" data-scroll-target="#root-cause">Root Cause</a></li>
  <li><a href="#recommended-solution-the-surveillance-mvp" id="toc-recommended-solution-the-surveillance-mvp" class="nav-link" data-scroll-target="#recommended-solution-the-surveillance-mvp">Recommended Solution: The Surveillance MVP</a></li>
  <li><a href="#feasibility" id="toc-feasibility" class="nav-link" data-scroll-target="#feasibility">Feasibility</a></li>
  <li><a href="#how-this-connects-to-coordination-and-regulatory-reform" id="toc-how-this-connects-to-coordination-and-regulatory-reform" class="nav-link" data-scroll-target="#how-this-connects-to-coordination-and-regulatory-reform">How This Connects to Coordination and Regulatory Reform</a></li>
  <li><a href="#scope-and-completeness" id="toc-scope-and-completeness" class="nav-link" data-scroll-target="#scope-and-completeness">Scope and Completeness</a></li>
  <li><a href="#recommendation" id="toc-recommendation" class="nav-link" data-scroll-target="#recommendation">Recommendation</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Fixing What We Can’t See</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">A policy brief for investing in automated, multi-source pesticide poisoning surveillance in South Africa</p>
  <div class="quarto-categories">
    <div class="quarto-category">policy</div>
    <div class="quarto-category">surveillance</div>
    <div class="quarto-category">brief</div>
    <div class="quarto-category">decision-makers</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>D2P Project Team </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 5, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 17, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Key Messages
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>South Africa detects <strong>fewer than 1 in 20</strong> pesticide poisoning cases. An estimated <strong>20,960 cases</strong> and <strong>2,620 deaths</strong> occur annually — costing <strong>R2.34 billion</strong> — yet only 1,013 reach the NMC surveillance system.</li>
<li><strong>Recommendation: adopt the Surveillance MVP</strong> (BChE auto-notification + PIH Minimum Viable Dataset) — <strong>R137,000/year operating cost</strong>, lifting detection from 5% to 19% of true cases within 12 weeks.</li>
<li>Without improved surveillance, neither the coordination response nor the recently gazetted terbufos ban can be measured or enforced with evidence.</li>
</ul>
</div>
</div>
<section id="the-problem" class="level2">
<h2 class="anchored" data-anchor-id="the-problem">The Problem</h2>
<p>South Africa’s pesticide poisoning surveillance system is fragmented. Three data streams — the Notifiable Medical Conditions system (NMC), the NHLS butyrylcholinesterase (BChE) laboratory, and the Poisons Information Helpline (PIH) — each see a fraction of the burden. None sees the whole. They do not talk to each other.</p>
<p><strong>The numbers:</strong></p>
<table class="table-striped caption-top table">
<caption>All values from <a href="../amua_import_parameters_v4.csv"><code>amua_import_parameters_v4.csv</code></a>.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Indicator</th>
<th style="text-align: right;">Value</th>
<th style="text-align: left;">Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Annual deaths</td>
<td style="text-align: right;"><strong>2,620</strong></td>
<td style="text-align: left;">StatsSA MACOD 2023 (X40–X49)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Estimated true cases/year</td>
<td style="text-align: right;"><strong>20,960</strong></td>
<td style="text-align: left;">Deaths ÷ 12.5% CFR</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NMC notifications (detected)</td>
<td style="text-align: right;"><strong>1,013 (4.8%)</strong></td>
<td style="text-align: left;">NICD NMC 2023</td>
</tr>
<tr class="even">
<td style="text-align: left;">NHLS severe BChE results (unlinked)</td>
<td style="text-align: right;"><strong>1,779</strong></td>
<td style="text-align: left;">NHLS LIS 2023</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PIH clinician calls (unlinked)</td>
<td style="text-align: right;"><strong>1,158</strong></td>
<td style="text-align: left;">PIH Tygerberg 2023</td>
</tr>
</tbody>
</table>
<p><strong>The consequence:</strong> decision-makers act on the visible 1,013 notifications while ~95% of the burden remains invisible. The response chain cannot prioritise what it cannot see. The recently gazetted terbufos ban (8 May 2026) cannot be evaluated without knowing whether poisoning incidence actually falls.</p>
</section>
<section id="root-cause" class="level2">
<h2 class="anchored" data-anchor-id="root-cause">Root Cause</h2>
<p>The under-detection is <strong>executional, not legislative</strong>. Section 90 of the National Health Act (2003) and existing NMC regulations already authorise the necessary data flows. Three fixable gaps remain:</p>
<ol type="1">
<li><strong>NHLS severe BChE results do not trigger a notification.</strong> The NHLS–NMC IT feed is operational, but no severity-threshold rule fires an alert.</li>
<li><strong>PIH consultations are not used for surveillance.</strong> ~1,158 clinician calls/year hold exposure, geography, and agent data — none enters the surveillance system.</li>
<li><strong>No structured agent-name capture.</strong> Without a consistent AfriTox product-name field across PIH and NMC, product-specific patterns (e.g.&nbsp;terbufos clusters) are invisible.</li>
</ol>
</section>
<section id="recommended-solution-the-surveillance-mvp" class="level2">
<h2 class="anchored" data-anchor-id="recommended-solution-the-surveillance-mvp">Recommended Solution: The Surveillance MVP</h2>
<p>Combine two low-cost, IT-configuration investments that build on existing infrastructure:</p>
<section id="option-1-bche-auto-notification" class="level3">
<h3 class="anchored" data-anchor-id="option-1-bche-auto-notification">Option 1 — BChE auto-notification</h3>
<p>Configure the NHLS LIS to auto-notify NICD when a BChE result shows severe inhibition (&lt; 10% of normal). <strong>No new test, no new reagent contract</strong> — only an IT rule on 10,626 tests already performed each year.</p>
<ul>
<li><strong>Setup:</strong> R200,000 (one-off)</li>
<li><strong>Operating:</strong> R55,000/year</li>
<li><strong>Detection uplift:</strong> +8.5 percentage points</li>
<li><strong>Delivery:</strong> 2–4 weeks</li>
</ul>
</section>
<section id="option-2-pih-dashboard-minimum-viable-dataset" class="level3">
<h3 class="anchored" data-anchor-id="option-2-pih-dashboard-minimum-viable-dataset">Option 2 — PIH dashboard + Minimum Viable Dataset</h3>
<p>PIH publishes a live dashboard (days); PIH and NICD agree a structured MVD so clinician calls enter NMC (3–9 months). Mandatory AfriTox agent-name field enables product-specific attribution across both streams.</p>
<ul>
<li><strong>Setup:</strong> R40,000 (one-off)</li>
<li><strong>Operating:</strong> R82,000/year</li>
<li><strong>Detection uplift:</strong> +5.6 percentage points</li>
<li><strong>Delivery:</strong> dashboard in 1–2 weeks; MVD integration in 3–9 months</li>
</ul>
</section>
<section id="combined-the-mvp" class="level3">
<h3 class="anchored" data-anchor-id="combined-the-mvp">Combined (the MVP)</h3>
<table class="table-striped caption-top table">
<caption>12-week delivery. No new headcount. No new legislation.</caption>
<colgroup>
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 24%">
<col style="width: 18%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Setup</th>
<th style="text-align: right;">Operating/yr</th>
<th style="text-align: center;">P<sub>detect</sub></th>
<th style="text-align: center;">Uplift vs.&nbsp;status quo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Surveillance MVP</strong></td>
<td style="text-align: right;"><strong>R240,000</strong></td>
<td style="text-align: right;"><strong>R137,000</strong></td>
<td style="text-align: center;"><strong>18.9%</strong></td>
<td style="text-align: center;"><strong>+14.1 pp (~4× improvement)</strong></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="feasibility" class="level2">
<h2 class="anchored" data-anchor-id="feasibility">Feasibility</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimension</th>
<th style="text-align: left;">Assessment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Political</strong></td>
<td style="text-align: left;">High. Aligns with NDoH NMC modernisation agenda; Minister has publicly committed to surveillance improvement.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Operational</strong></td>
<td style="text-align: left;">High. Both options use existing IT infrastructure (NHLS LIS, PIH TMS, NMC platform). NHLS–NMC feed already operational.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Financial</strong></td>
<td style="text-align: left;">High. R137,000/year is a 45.7% uplift on current surveillance spend — absorbable within existing budgets.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Legal</strong></td>
<td style="text-align: left;">High. Section 90 NHA + NMC regulations already authorise all required data flows. No new legislation.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Public health impact</strong></td>
<td style="text-align: left;">Moderate (necessary but not sufficient). Detection enables action but does not itself avert deaths — that requires the coordination response.</td>
</tr>
</tbody>
</table>
</section>
<section id="how-this-connects-to-coordination-and-regulatory-reform" class="level2">
<h2 class="anchored" data-anchor-id="how-this-connects-to-coordination-and-regulatory-reform">How This Connects to Coordination and Regulatory Reform</h2>
<p>Surveillance is <strong>step one</strong> of a three-part system:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    S["1. Surveillance MVP&lt;br/&gt;&lt;b&gt;Detect&lt;/b&gt;&lt;br/&gt;~R137k/yr"] --&gt; C["2. Coordination&lt;br/&gt;&lt;b&gt;Act&lt;/b&gt;&lt;br/&gt;~R145k/yr"]
    C --&gt; R["3. Regulatory action&lt;br/&gt;&lt;b&gt;Restrict&lt;/b&gt;&lt;br/&gt;(terbufos ban gazetted)"]
    R -.Measure impact.-&gt; S

    style S fill:#cce5ff,stroke:#333,stroke-width:2px
    style C fill:#d4edda,stroke:#333
    style R fill:#ffd9b3,stroke:#cc8800
</pre>
</div>
<p></p><figcaption> The surveillance signal feeds the coordination response, which feeds product-specific regulation. Each layer depends on the one before it.</figcaption> </figure><p></p>
</div>
</div>
</div>
<p><strong>Coordination</strong> (companion brief): The NMC–EHP–DALRRD response loop is currently broken — ~99% of notifications end without a recorded investigation or regulatory follow-up. A Coordination Full Package (~R145,000/year, no new legislation) mandates a closed-loop workflow: every notification triggers an EHP investigation recorded on NMC, a structured DALRRD referral, and clinician feedback. At base-case response efficacy, this averts ~957 deaths/year.</p>
<p><strong>Terbufos ban</strong> (gazetted 8 May 2026): Agriculture Minister Steenhuisen banned all terbufos-containing products under Act 36 of 1947. Without surveillance, it is impossible to confirm whether the ban reduces poisoning incidence or whether a more-toxic substitute enters the informal market. The MVP provides the measurement infrastructure for the ban’s 24-month evaluation gate.</p>
</section>
<section id="scope-and-completeness" class="level2">
<h2 class="anchored" data-anchor-id="scope-and-completeness">Scope and Completeness</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 39%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Element</th>
<th style="text-align: left;">Specification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Scope</strong></td>
<td style="text-align: left;">All acute pesticide poisoning cases presenting to facilities served by NHLS BChE testing and/or PIH consultation. National roll-out; 3-province pilot recommended (GP, WC, KZN).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Roles &amp; responsibilities</strong></td>
<td style="text-align: left;">NHLS owns the BChE auto-notify LIS rule. PIH (Tygerberg) owns the dashboard and MVD extract. NICD coordinates the NMC ingest and reconciliation. NDoH is the accountable owner.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Compliance &amp; enforcement</strong></td>
<td style="text-align: left;">Voluntary adoption (no new mandate required). KPI: % of NHLS severe results appearing in NMC within 24 hours; % of PIH calls with MVD completeness ≥ 80%.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Reporting &amp; documentation</strong></td>
<td style="text-align: left;">Monthly reconciliation report (NHLS→NMC match rate; PIH MVD completeness). Quarterly report to MAC on P<sub>detect</sub> trend.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Resources</strong></td>
<td style="text-align: left;">Setup R240,000 (one-off); operating R137,000/year. No new headcount; fractional FTE allocations from existing NICD, NHLS, and PIH posts.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Timelines</strong></td>
<td style="text-align: left;">Weeks 1–2: PIH dashboard live. Weeks 2–4: BChE LIS rule configured. Months 1–3: MVD finalised. Month 6: pilot evaluation. Month 12: Phase 2 decision (community layer).</td>
</tr>
</tbody>
</table>
</section>
<section id="recommendation" class="level2">
<h2 class="anchored" data-anchor-id="recommendation">Recommendation</h2>
<p><strong>Adopt the Surveillance MVP (Option 1 + Option 2) and pilot in Gauteng, Western Cape, and KwaZulu-Natal for 6 months.</strong></p>
<p>Next steps:</p>
<ol type="1">
<li><strong>Immediate (Weeks 1–4):</strong> NHLS configures the BChE severity-threshold rule; PIH deploys the dashboard.</li>
<li><strong>Short term (Months 1–3):</strong> PIH–NICD MVD workshop; AfriTox agent-name harmonisation.</li>
<li><strong>Month 6:</strong> Evaluate pilot against completeness of NHLS results in NMC and signal-to-investigation latency.</li>
<li><strong>Month 9:</strong> Commission sentinel toxicology site (Option 5, research-funded — provides the agent-attribution evidence base for product-specific regulation).</li>
<li><strong>Month 12:</strong> If ≥40% of severe cases originate in low-facility-access districts, commission the community-layer pilot (Option 3, Phase 2).</li>
</ol>
<p><strong>Hand off to <code>d2p-pressure-tester</code></strong> for full adversarial review before submission to MAC.</p>
<hr>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Maintainability
</div>
</div>
<div class="callout-body-container callout-body">
<p>This brief pulls all numerical claims from <a href="../amua_import_parameters_v4.csv"><code>amua_import_parameters_v4.csv</code></a> at render time. To update a figure: edit the CSV cell, re-render with <code>quarto render posts/surveillance_brief.qmd</code>. No inline numbers to chase.</p>
<p><strong>Related documents:</strong> <a href="../posts/surveillance_policy.html">Detailed surveillance analysis</a> · <a href="../posts/coordination_policy.html">Coordination brief</a> · <a href="../posts/terbufos_policy.html">Terbufos brief</a> · <a href="../parameters_hub.html">Parameters Hub</a></p>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:http:|https:)\/\/(?:[^\/]*\.)?your-site-url\.com|^(?!http)");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Fixing What We Can't See"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "A policy brief for investing in automated, multi-source pesticide poisoning surveillance in South Africa"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "D2P Project Team"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2025-09-05"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="an">date-modified:</span><span class="co"> today</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [policy, surveillance, brief, decision-makers]</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 2</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: false</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Canonical parameters (single source of truth) ---</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"../amua_import_parameters_v4.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>pick <span class="ot">&lt;-</span> <span class="cf">function</span>(name) {</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> raw <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(Name <span class="sc">==</span> name) <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">pull</span>(Expression)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(v) <span class="sc">==</span> <span class="dv">0</span>) <span class="cn">NA_character_</span> <span class="cf">else</span> v[<span class="dv">1</span>]</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>zar <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.numeric</span>(x))</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.na</span>(n)) <span class="fu">return</span>(x)</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (n <span class="sc">&gt;=</span> <span class="fl">1e9</span>) <span class="fu">sprintf</span>(<span class="st">"R%.2f billion"</span>, n <span class="sc">/</span> <span class="fl">1e9</span>)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span> <span class="cf">if</span> (n <span class="sc">&gt;=</span> <span class="fl">1e6</span>) <span class="fu">sprintf</span>(<span class="st">"R%.1f million"</span>, n <span class="sc">/</span> <span class="fl">1e6</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span> <span class="fu">paste0</span>(<span class="st">"R"</span>, <span class="fu">format</span>(n, <span class="at">big.mark =</span> <span class="st">","</span>, <span class="at">scientific =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Key figures</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>n_deaths   <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">pick</span>(<span class="st">"n_deaths_headline"</span>))</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>n_true     <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">pick</span>(<span class="st">"n_true_burden_from_statssa_mid"</span>))</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>n_nmc      <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">pick</span>(<span class="st">"n_nmc_annual"</span>))</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>n_nhls     <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">pick</span>(<span class="st">"n_nhls_severe_annual"</span>))</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>n_pih      <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">pick</span>(<span class="st">"n_pih_annual"</span>))</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>burden     <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">pick</span>(<span class="st">"C_burden_total_headline"</span>))</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>d_sq       <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">pick</span>(<span class="st">"d_status_quo"</span>))</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>d_mvp      <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">pick</span>(<span class="st">"d_surveillance_mvp"</span>))</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>c_mvp_op   <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">pick</span>(<span class="st">"c_surv_MVP_op"</span>))</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>c_mvp_setup<span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">pick</span>(<span class="st">"c_surv_MVP_setup"</span>))</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>::: {.callout-important icon=false}</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key Messages</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>South Africa detects **fewer than 1 in 20** pesticide poisoning cases. An estimated **`r scales::comma(n_true)` cases** and **`r scales::comma(n_deaths)` deaths** occur annually — costing **`r zar(burden)`** — yet only <span class="in">`r scales::comma(n_nmc)`</span> reach the NMC surveillance system.</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Recommendation: adopt the Surveillance MVP** (BChE auto-notification + PIH Minimum Viable Dataset) — **`r zar(c_mvp_op)`/year operating cost**, lifting detection from <span class="in">`r sprintf("%.0f%%", d_sq*100)`</span> to <span class="in">`r sprintf("%.0f%%", d_mvp*100)`</span> of true cases within 12 weeks.</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Without improved surveillance, neither the coordination response nor the recently gazetted terbufos ban can be measured or enforced with evidence.</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Problem</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>South Africa's pesticide poisoning surveillance system is fragmented. Three data streams — the Notifiable Medical Conditions system (NMC), the NHLS butyrylcholinesterase (BChE) laboratory, and the Poisons Information Helpline (PIH) — each see a fraction of the burden. None sees the whole. They do not talk to each other.</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>**The numbers:**</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Indicator <span class="pp">|</span> Value <span class="pp">|</span> Source <span class="pp">|</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="pp">|:----------|------:|:-------|</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Annual deaths <span class="pp">|</span> **`r scales::comma(n_deaths)`** <span class="pp">|</span> StatsSA MACOD 2023 (X40–X49) <span class="pp">|</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Estimated true cases/year <span class="pp">|</span> **`r scales::comma(n_true)`** <span class="pp">|</span> Deaths ÷ 12.5% CFR <span class="pp">|</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> NMC notifications (detected) <span class="pp">|</span> **`r scales::comma(n_nmc)` (`r sprintf("%.1f%%", d_sq*100)`)** <span class="pp">|</span> NICD NMC 2023 <span class="pp">|</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> NHLS severe BChE results (unlinked) <span class="pp">|</span> **`r scales::comma(n_nhls)`** <span class="pp">|</span> NHLS LIS 2023 <span class="pp">|</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PIH clinician calls (unlinked) <span class="pp">|</span> **`r scales::comma(n_pih)`** <span class="pp">|</span> PIH Tygerberg 2023 <span class="pp">|</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>: All values from <span class="co">[</span><span class="ot">`amua_import_parameters_v4.csv`</span><span class="co">](../amua_import_parameters_v4.csv)</span>. {.striped}</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>**The consequence:** decision-makers act on the visible <span class="in">`r scales::comma(n_nmc)`</span> notifications while ~95% of the burden remains invisible. The response chain cannot prioritise what it cannot see. The recently gazetted terbufos ban (8 May 2026) cannot be evaluated without knowing whether poisoning incidence actually falls.</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a><span class="fu">## Root Cause</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>The under-detection is **executional, not legislative**. Section 90 of the National Health Act (2003) and existing NMC regulations already authorise the necessary data flows. Three fixable gaps remain:</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**NHLS severe BChE results do not trigger a notification.** The NHLS–NMC IT feed is operational, but no severity-threshold rule fires an alert.</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**PIH consultations are not used for surveillance.** ~<span class="in">`r scales::comma(n_pih)`</span> clinician calls/year hold exposure, geography, and agent data — none enters the surveillance system.</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**No structured agent-name capture.** Without a consistent AfriTox product-name field across PIH and NMC, product-specific patterns (e.g. terbufos clusters) are invisible.</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="fu">## Recommended Solution: The Surveillance MVP</span></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>Combine two low-cost, IT-configuration investments that build on existing infrastructure:</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a><span class="fu">### Option 1 — BChE auto-notification</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>Configure the NHLS LIS to auto-notify NICD when a BChE result shows severe inhibition (&lt; 10% of normal). **No new test, no new reagent contract** — only an IT rule on <span class="in">`r scales::comma(as.numeric(pick("n_nhls_total_annual")))`</span> tests already performed each year.</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Setup:** <span class="in">`r zar(as.numeric(pick("c_S2_BChE_autonotify_setup")))`</span> (one-off)</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Operating:** <span class="in">`r zar(as.numeric(pick("c_S2_BChE_autonotify_op")))`</span>/year</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Detection uplift:** <span class="in">`r sprintf("+%.1f", (as.numeric(pick("d_S2_BChE_autonotify")) - d_sq) * 100)`</span> percentage points</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Delivery:** 2–4 weeks</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="fu">### Option 2 — PIH dashboard + Minimum Viable Dataset</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>PIH publishes a live dashboard (days); PIH and NICD agree a structured MVD so clinician calls enter NMC (3–9 months). Mandatory AfriTox agent-name field enables product-specific attribution across both streams.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Setup:** <span class="in">`r zar(as.numeric(pick("c_S1_PIH_MVD_setup")))`</span> (one-off)</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Operating:** <span class="in">`r zar(as.numeric(pick("c_S1_PIH_MVD_op")))`</span>/year</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Detection uplift:** <span class="in">`r sprintf("+%.1f", (as.numeric(pick("d_S1_PIH_MVD")) - d_sq) * 100)`</span> percentage points</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Delivery:** dashboard in 1–2 weeks; MVD integration in 3–9 months</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="fu">### Combined (the MVP)</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="pp">|</span> Setup <span class="pp">|</span> Operating/yr <span class="pp">|</span> P~detect~ <span class="pp">|</span> Uplift vs. status quo <span class="pp">|</span></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>:--<span class="pp">|------:|-------------:|:---------:|:---------------------:|</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Surveillance MVP** | **`r zar(c_mvp_setup)`** | **`r zar(c_mvp_op)`** | **`r sprintf("%.1f%%", d_mvp*100)`** | **`r sprintf("+%.1f pp", (d_mvp - d_sq)*100)` (~4× improvement)** <span class="pp">|</span></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>: 12-week delivery. No new headcount. No new legislation. {.striped}</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="fu">## Feasibility</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Dimension <span class="pp">|</span> Assessment <span class="pp">|</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a><span class="pp">|:----------|:-----------|</span></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Political** <span class="pp">|</span> High. Aligns with NDoH NMC modernisation agenda; Minister has publicly committed to surveillance improvement. <span class="pp">|</span></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Operational** <span class="pp">|</span> High. Both options use existing IT infrastructure (NHLS LIS, PIH TMS, NMC platform). NHLS–NMC feed already operational. <span class="pp">|</span></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Financial** <span class="pp">|</span> High. <span class="in">`r zar(c_mvp_op)`</span>/year is a <span class="in">`r sprintf("%.1f%%", 100 * c_mvp_op / sum(as.numeric(pick("c_status_quo_program"))))`</span> uplift on current surveillance spend — absorbable within existing budgets. <span class="pp">|</span></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Legal** <span class="pp">|</span> High. Section 90 NHA + NMC regulations already authorise all required data flows. No new legislation. <span class="pp">|</span></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Public health impact** <span class="pp">|</span> Moderate (necessary but not sufficient). Detection enables action but does not itself avert deaths — that requires the coordination response. <span class="pp">|</span></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="fu">## How This Connects to Coordination and Regulatory Reform</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>Surveillance is **step one** of a three-part system:</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{mermaid}</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>%%| fig-cap: <span class="ot">"</span><span class="st">The surveillance signal feeds the coordination response, which feeds product-specific regulation. Each layer depends on the one before it.</span><span class="ot">"</span></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>    S[<span class="ot">"</span><span class="st">1. Surveillance MVP&lt;br/&gt;&lt;b&gt;Detect&lt;/b&gt;&lt;br/&gt;~R137k/yr</span><span class="ot">"</span>] --&gt; C[<span class="ot">"</span><span class="st">2. Coordination&lt;br/&gt;&lt;b&gt;Act&lt;/b&gt;&lt;br/&gt;~R145k/yr</span><span class="ot">"</span>]</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>    C --&gt; R[<span class="ot">"</span><span class="st">3. Regulatory action&lt;br/&gt;&lt;b&gt;Restrict&lt;/b&gt;&lt;br/&gt;(terbufos ban gazetted)</span><span class="ot">"</span>]</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>    R -.Measure impact.-&gt; S</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>    style S fill:<span class="co">#cce5ff,stroke:#333,stroke-width:2px</span></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>    style C fill:<span class="co">#d4edda,stroke:#333</span></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>    style R fill:<span class="co">#ffd9b3,stroke:#cc8800</span></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>**Coordination** (companion brief): The NMC–EHP–DALRRD response loop is currently broken — ~99% of notifications end without a recorded investigation or regulatory follow-up. A Coordination Full Package (~R145,000/year, no new legislation) mandates a closed-loop workflow: every notification triggers an EHP investigation recorded on NMC, a structured DALRRD referral, and clinician feedback. At base-case response efficacy, this averts ~957 deaths/year.</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>**Terbufos ban** (gazetted 8 May 2026): Agriculture Minister Steenhuisen banned all terbufos-containing products under Act 36 of 1947. Without surveillance, it is impossible to confirm whether the ban reduces poisoning incidence or whether a more-toxic substitute enters the informal market. The MVP provides the measurement infrastructure for the ban's 24-month evaluation gate.</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="fu">## Scope and Completeness</span></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Element <span class="pp">|</span> Specification <span class="pp">|</span></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="pp">|:--------|:-------------|</span></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Scope** <span class="pp">|</span> All acute pesticide poisoning cases presenting to facilities served by NHLS BChE testing and/or PIH consultation. National roll-out; 3-province pilot recommended (GP, WC, KZN). <span class="pp">|</span></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Roles &amp; responsibilities** <span class="pp">|</span> NHLS owns the BChE auto-notify LIS rule. PIH (Tygerberg) owns the dashboard and MVD extract. NICD coordinates the NMC ingest and reconciliation. NDoH is the accountable owner. <span class="pp">|</span></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Compliance &amp; enforcement** <span class="pp">|</span> Voluntary adoption (no new mandate required). KPI: % of NHLS severe results appearing in NMC within 24 hours; % of PIH calls with MVD completeness ≥ 80%. <span class="pp">|</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Reporting &amp; documentation** <span class="pp">|</span> Monthly reconciliation report (NHLS→NMC match rate; PIH MVD completeness). Quarterly report to MAC on P~detect~ trend. <span class="pp">|</span></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Resources** <span class="pp">|</span> Setup <span class="in">`r zar(c_mvp_setup)`</span> (one-off); operating <span class="in">`r zar(c_mvp_op)`</span>/year. No new headcount; fractional FTE allocations from existing NICD, NHLS, and PIH posts. <span class="pp">|</span></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Timelines** <span class="pp">|</span> Weeks 1–2: PIH dashboard live. Weeks 2–4: BChE LIS rule configured. Months 1–3: MVD finalised. Month 6: pilot evaluation. Month 12: Phase 2 decision (community layer). <span class="pp">|</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="fu">## Recommendation</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>**Adopt the Surveillance MVP (Option 1 + Option 2) and pilot in Gauteng, Western Cape, and KwaZulu-Natal for 6 months.**</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>Next steps:</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Immediate (Weeks 1–4):** NHLS configures the BChE severity-threshold rule; PIH deploys the dashboard.</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Short term (Months 1–3):** PIH–NICD MVD workshop; AfriTox agent-name harmonisation.</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Month 6:** Evaluate pilot against completeness of NHLS results in NMC and signal-to-investigation latency.</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Month 9:** Commission sentinel toxicology site (Option 5, research-funded — provides the agent-attribution evidence base for product-specific regulation).</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Month 12:** If ≥40% of severe cases originate in low-facility-access districts, commission the community-layer pilot (Option 3, Phase 2).</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>**Hand off to `d2p-pressure-tester`** for full adversarial review before submission to MAC.</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>::: {.callout-note icon=false}</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="fu">## Maintainability</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>This brief pulls all numerical claims from <span class="co">[</span><span class="ot">`amua_import_parameters_v4.csv`</span><span class="co">](../amua_import_parameters_v4.csv)</span> at render time. To update a figure: edit the CSV cell, re-render with <span class="in">`quarto render posts/surveillance_brief.qmd`</span>. No inline numbers to chase.</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>**Related documents:** <span class="co">[</span><span class="ot">Detailed surveillance analysis</span><span class="co">](surveillance_policy.qmd)</span> · <span class="co">[</span><span class="ot">Coordination brief</span><span class="co">](coordination_policy.qmd)</span> · <span class="co">[</span><span class="ot">Terbufos brief</span><span class="co">](terbufos_policy.qmd)</span> · <span class="co">[</span><span class="ot">Parameters Hub</span><span class="co">](../parameters_hub.qmd)</span></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>:::</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 D2P Project Team</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="mailto:contact@example.com">
<p>Contact</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>