<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="D2P Project Team">
<meta name="dcterms.date" content="2025-08-05">

<title>Technical Appendix D — Sentinel Toxicology – D2P Project</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-22206e84c2e6f955c0d8fc54fe8645d2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">D2P Project</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../one_pager.html"> 
<span class="menu-text">One-Pager</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../posts.html"> 
<span class="menu-text">Research Outputs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../parameters_hub.html"> 
<span class="menu-text">Parameters Hub</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../parameter_playground.html"> 
<span class="menu-text">Playground</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-technical-appendices" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Technical Appendices</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-technical-appendices">    
        <li>
    <a class="dropdown-item" href="../analysis_report_v2.html">
 <span class="dropdown-text">A — Surveillance (decision analysis)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../technical_appendix_coordination.html">
 <span class="dropdown-text">B — Coordination (joint-probability model)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../technical_appendix_terbufos.html">
 <span class="dropdown-text">C — Terbufos (bracketed deaths averted)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../posts/surveillance_concept_note.html">
 <span class="dropdown-text">D — Sentinel toxicology (live-patient testing, S3b)</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:contact@example.com"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary"><span class="header-section-number">1</span> Executive Summary</a></li>
  <li><a href="#background-the-surveillance-gap" id="toc-background-the-surveillance-gap" class="nav-link" data-scroll-target="#background-the-surveillance-gap"><span class="header-section-number">2</span> Background: The Surveillance Gap</a>
  <ul class="collapse">
  <li><a href="#current-system-architecture" id="toc-current-system-architecture" class="nav-link" data-scroll-target="#current-system-architecture"><span class="header-section-number">2.1</span> Current System Architecture</a></li>
  <li><a href="#missed-opportunities" id="toc-missed-opportunities" class="nav-link" data-scroll-target="#missed-opportunities"><span class="header-section-number">2.2</span> Missed Opportunities</a></li>
  </ul></li>
  <li><a href="#proposed-framework" id="toc-proposed-framework" class="nav-link" data-scroll-target="#proposed-framework"><span class="header-section-number">3</span> Proposed Framework</a>
  <ul class="collapse">
  <li><a href="#design-principles" id="toc-design-principles" class="nav-link" data-scroll-target="#design-principles"><span class="header-section-number">3.1</span> Design Principles</a></li>
  <li><a href="#system-architecture" id="toc-system-architecture" class="nav-link" data-scroll-target="#system-architecture"><span class="header-section-number">3.2</span> System Architecture</a></li>
  <li><a href="#key-components" id="toc-key-components" class="nav-link" data-scroll-target="#key-components"><span class="header-section-number">3.3</span> Key Components</a></li>
  </ul></li>
  <li><a href="#implementation-roadmap" id="toc-implementation-roadmap" class="nav-link" data-scroll-target="#implementation-roadmap"><span class="header-section-number">4</span> Implementation Roadmap</a>
  <ul class="collapse">
  <li><a href="#phase-1-pilot-months-16" id="toc-phase-1-pilot-months-16" class="nav-link" data-scroll-target="#phase-1-pilot-months-16"><span class="header-section-number">4.1</span> Phase 1: Pilot (Months 1–6)</a></li>
  <li><a href="#phase-2-national-rollout-months-712" id="toc-phase-2-national-rollout-months-712" class="nav-link" data-scroll-target="#phase-2-national-rollout-months-712"><span class="header-section-number">4.2</span> Phase 2: National Rollout (Months 7–12)</a></li>
  <li><a href="#phase-3-evaluation-months-1324" id="toc-phase-3-evaluation-months-1324" class="nav-link" data-scroll-target="#phase-3-evaluation-months-1324"><span class="header-section-number">4.3</span> Phase 3: Evaluation (Months 13–24)</a></li>
  </ul></li>
  <li><a href="#governance-and-oversight" id="toc-governance-and-oversight" class="nav-link" data-scroll-target="#governance-and-oversight"><span class="header-section-number">5</span> Governance and Oversight</a>
  <ul class="collapse">
  <li><a href="#roles-and-responsibilities" id="toc-roles-and-responsibilities" class="nav-link" data-scroll-target="#roles-and-responsibilities"><span class="header-section-number">5.1</span> Roles and Responsibilities</a></li>
  <li><a href="#coordination-mechanisms" id="toc-coordination-mechanisms" class="nav-link" data-scroll-target="#coordination-mechanisms"><span class="header-section-number">5.2</span> Coordination Mechanisms</a></li>
  </ul></li>
  <li><a href="#budget-summary" id="toc-budget-summary" class="nav-link" data-scroll-target="#budget-summary"><span class="header-section-number">6</span> Budget Summary</a></li>
  <li><a href="#limitations-and-risks" id="toc-limitations-and-risks" class="nav-link" data-scroll-target="#limitations-and-risks"><span class="header-section-number">7</span> Limitations and Risks</a></li>
  <li><a href="#next-steps" id="toc-next-steps" class="nav-link" data-scroll-target="#next-steps"><span class="header-section-number">8</span> Next Steps</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">9</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Technical Appendix D — Sentinel Toxicology</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">Concept note for live-patient chemical-toxicology testing (Option S3)</p>
  <div class="quarto-categories">
    <div class="quarto-category">surveillance</div>
    <div class="quarto-category">framework</div>
    <div class="quarto-category">concept-note</div>
    <div class="quarto-category">technical-appendix</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>D2P Project Team </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 5, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">May 12, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Where this appendix fits
</div>
</div>
<div class="callout-body-container callout-body">
<p>This appendix is the <strong>quantitative concept note</strong> for the live-patient chemical-toxicology investment (<strong>Option S3</strong>) referenced in the <a href="../posts/surveillance_policy.html">Surveillance brief</a>. It is the only one of the three active surveillance options that <strong>creates a new capability</strong> — NHLS currently performs qualitative/quantitative pesticide assays only on post-mortem specimens. Pilot costing is anchored in canonical CSV rows <code>c_option6_pilot_year1</code> (R1.2m), <code>c_option6_full_5site_annual</code> (R3.625m), <code>c_gcms_screen_per_specimen</code> (R2,500), and <code>c_clinical_battery_per_patient</code> (R1,500).</p>
<p><strong>Sister appendices:</strong> <a href="../analysis_report_v2.html">A — Surveillance decision analysis</a> · <a href="../technical_appendix_coordination.html">B — Coordination model</a> · <a href="../technical_appendix_terbufos.html">C — Terbufos bracketed estimate</a>.</p>
</div>
</div>
<section id="executive-summary" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="executive-summary"><span class="header-section-number">1</span> Executive Summary</h2>
<p>This concept note outlines a comprehensive framework for improving pesticide poisoning surveillance in South Africa. Building on lessons learned from the National Notifiable Medical Conditions (NMC) system, NHLS laboratory data, and the Poisons Information Helpline, we propose an <strong>integrated surveillance approach</strong> that:</p>
<ol type="1">
<li><strong>Links existing data streams</strong> without creating new parallel systems</li>
<li><strong>Automates notification workflows</strong> to reduce reporting delays</li>
<li><strong>Enables hotspot detection</strong> through spatial and temporal clustering analysis</li>
<li><strong>Supports rapid public health response</strong> via clear escalation protocols</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Status
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is a <strong>DRAFT</strong> concept note (Version 3, dated 11 August 2025). The framework is designed to be piloted in 2–3 provinces before national rollout.</p>
</div>
</div>
</section>
<section id="background-the-surveillance-gap" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="background-the-surveillance-gap"><span class="header-section-number">2</span> Background: The Surveillance Gap</h2>
<section id="current-system-architecture" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="current-system-architecture"><span class="header-section-number">2.1</span> Current System Architecture</h3>
<p>South Africa has three parallel data sources for pesticide poisoning, but they operate independently:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-current-system" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-current-system-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-current-system">flowchart LR
    A[Healthcare Facility&lt;br/&gt;Clinician / PHO] --&gt;|NMC notification| E[("NICD / NMC&lt;br/&gt;&lt;b&gt;Source of truth&lt;/b&gt;")]
    A --&gt; N[NHLS Laboratory]

    subgraph N[NHLS Laboratory]
        direction TB
        C1[BChE Assay&lt;br/&gt;1,779 severe/year&lt;br/&gt;10,626 tests 2023&lt;br/&gt;&lt;i&gt;Live patients&lt;/i&gt;]
        C2[Chemical Toxicology&lt;br/&gt;&lt;i&gt;Post-mortem only —&lt;br/&gt;not yet done on&lt;br/&gt;live patients&lt;/i&gt;]
    end

    A --&gt; D[PIH Consultation&lt;br/&gt;~1,158 clinician calls/yr&lt;br/&gt;&lt;i&gt;No minimum dataset&lt;/i&gt;]

    E --&gt;|SMS notification| H[Local EHP&lt;br/&gt;&lt;i&gt;mandated to&lt;br/&gt;investigate&lt;/i&gt;]
    H -.Investigation NOT&lt;br/&gt;recorded on NMC.-x E
    H -.Informal referral.-&gt; I[DALRRD&lt;br/&gt;&lt;i&gt;Pesticide Registrar /&lt;br/&gt;Inspectorate&lt;/i&gt;]
    H -.Referral NOT&lt;br/&gt;recorded on NMC.-x E
    I -.Feedback to EHP&lt;br/&gt;at best.-&gt; H
    I -.x No feedback to NMC.-x E

    C1 -.No structured feed.-&gt; E
    C2 -.x Not available for&lt;br/&gt;live-patient surveillance.-x E
    D -.No minimum viable&lt;br/&gt;dataset defined.-&gt; E

    style E fill:#9f9,stroke:#060,stroke-width:2px
    style A fill:#fde,stroke:#333
    style C1 fill:#bbf,stroke:#333
    style C2 fill:#ffd9b3,stroke:#cc8800,stroke-dasharray: 5 5
    style D fill:#bfb,stroke:#333
    style H fill:#ffd,stroke:#333
    style I fill:#fdd,stroke:#cc0000,stroke-dasharray: 5 5
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-current-system-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Current (fragmented) surveillance architecture. NICD is the de facto source-of-truth for case notifications. Notifications on the NMC platform trigger an SMS to the local EHP (mandated to investigate) but the investigation outcome is not recorded back on NMC. EHP→DALRRD referral is informal and likewise unrecorded. NHLS holds two distinct laboratory streams — BChE (live patients, 1,779/yr severe from 10,626 tests in 2023) and Chemical Toxicology (post-mortem only — not yet done on live patients) — neither of which feeds NICD in a structured way. PIH consultations are not captured against a minimum viable dataset.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>What this diagram shows.</strong> Five gaps in the current state:</p>
<ol type="1">
<li><strong>NICD/NMC is the source of truth</strong> for case notifications but receives only the clinician-completed NMC stream (~1,013/year, 2023) — a fraction of the true burden.</li>
<li><strong>The NHLS laboratory holds two distinct streams</strong>: (a) <strong>BChE assays</strong> on live patients (10,626 tests/year in 2023; 1,779 severe results, capability exists) and (b) <strong>Chemical toxicology</strong> — qualitative/quantitative pesticide assays which <strong>NHLS currently performs post-mortem only</strong>. Live-patient chemical toxicology is not yet available (see <a href="#sec-component-6">Component 6</a>).</li>
<li><strong>Neither NHLS stream feeds NICD in a structured way.</strong> BChE has no automated notification; chemical toxicology is not yet generated on living patients at all.</li>
<li><strong>The EHP arm exists but does not close the loop.</strong> When an NMC notification is filed, an SMS reaches the local EHP, who is mandated to investigate — but neither the investigation outcome nor the informal DALRRD referral is recorded back on NMC, and DALRRD’s regulatory action (if any) is fed back to the EHP at best, never to NICD or the clinician.</li>
<li><strong>PIH consultations are not captured against a minimum viable dataset</strong>, so the ~1,158 clinician-initiated calls/year (2023) cannot be aggregated, geocoded, or matched to NICD cases.</li>
</ol>
</section>
<section id="missed-opportunities" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="missed-opportunities"><span class="header-section-number">2.2</span> Missed Opportunities</h3>
<p>From 2020–2024:</p>
<ul>
<li><strong>~3,450 NMC notifications</strong> were filed, but at least <strong>~10,000 severe BChE inhibitions</strong> were detected in NHLS labs</li>
<li><strong>Gap of ~6,550 cases</strong> that should have triggered public health investigation</li>
<li><strong>No clustering analysis</strong> to identify hotspots (e.g., contaminated food sources, illegal pesticide sales)</li>
</ul>
</section>
</section>
<section id="proposed-framework" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="proposed-framework"><span class="header-section-number">3</span> Proposed Framework</h2>
<section id="design-principles" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="design-principles"><span class="header-section-number">3.1</span> Design Principles</h3>
<ol type="1">
<li><strong>Integration over duplication</strong>: Link existing systems rather than building new infrastructure</li>
<li><strong>Automation over manual reporting</strong>: Use laboratory triggers and structured data flows</li>
<li><strong>Timeliness over completeness</strong>: Prioritize rapid detection for actionable hotspots</li>
<li><strong>Scalability</strong>: Start with pilot provinces, expand based on evidence</li>
</ol>
</section>
<section id="system-architecture" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="system-architecture"><span class="header-section-number">3.2</span> System Architecture</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-proposed-system" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-proposed-system-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-proposed-system">flowchart TB
    A[Healthcare Facility] --&gt; B[Clinician suspects poisoning]
    B --&gt; C{BChE test ordered?}
    C --&gt;|Yes| D[NHLS Laboratory]
    C --&gt;|No| E[Clinical diagnosis only]
    
    D --&gt; F{BChE &lt; 50% normal?}
    F --&gt;|Yes - Severe| G[Auto-notify NICD]
    F --&gt;|No| H[Store result]
    
    E --&gt; I[Manual NMC notification]
    
    G --&gt; J[NICD Surveillance Unit]
    I --&gt; J
    
    B --&gt; K[Call PIH for advice]
    K --&gt; L[PIH records case]
    L --&gt; M[Quarterly summary to NICD]
    M --&gt; J
    
    J --&gt; N{Cluster detected?}
    N --&gt;|Yes| O[Alert provincial team]
    N --&gt;|No| P[Routine monitoring]
    
    O --&gt; Q[Field investigation]
    Q --&gt; R[Environmental sampling]
    Q --&gt; S[Source control]
    
    style G fill:#ff9,stroke:#333
    style J fill:#9f9,stroke:#333
    style O fill:#f99,stroke:#333
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-proposed-system-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Proposed integrated surveillance architecture
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="key-components" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="key-components"><span class="header-section-number">3.3</span> Key Components</h3>
<section id="laboratory-triggered-surveillance-option-3" class="level4" data-number="3.3.1">
<h4 data-number="3.3.1" class="anchored" data-anchor-id="laboratory-triggered-surveillance-option-3"><span class="header-section-number">3.3.1</span> 1. Laboratory-Triggered Surveillance (Option 3)</h4>
<p><strong>Implementation:</strong></p>
<ul>
<li>Configure NHLS Laboratory Information System (LIS) to flag BChE results &lt; 50% of normal</li>
<li>Auto-generate notification to NICD with:
<ul>
<li>Patient demographics (age, sex, facility)</li>
<li>BChE value and normal range</li>
<li>Test date and time</li>
</ul></li>
<li>Notification sent within <strong>24 hours</strong> of result validation</li>
</ul>
<p><strong>Data flow:</strong></p>
<pre><code>NHLS LIS → HL7 message → NICD middleware → NMC database → Surveillance dashboard</code></pre>
<p><strong>Cost:</strong> ~R55,000/year (mostly IT staff time for configuration)</p>
</section>
<section id="poisons-information-helpline-integration-option-4" class="level4" data-number="3.3.2">
<h4 data-number="3.3.2" class="anchored" data-anchor-id="poisons-information-helpline-integration-option-4"><span class="header-section-number">3.3.2</span> 2. Poisons Information Helpline Integration (Option 4)</h4>
<p><strong>Implementation:</strong></p>
<ul>
<li>PIH generates <strong>quarterly reports</strong> summarizing:
<ul>
<li>Total pesticide-related calls</li>
<li>Age/sex distribution</li>
<li>Geographic distribution (by referring facility)</li>
<li>Severity classification (minor, moderate, severe)</li>
<li>Suspected pesticide type</li>
</ul></li>
<li>Reports sent to NICD for temporal trend analysis</li>
</ul>
<p><strong>Data flow:</strong></p>
<pre><code>PIH call log → Quarterly extraction → Excel/CSV → Email to NICD → Manual review</code></pre>
<p><strong>Cost:</strong> ~R62,000/year (PIH analyst time)</p>
</section>
<section id="inter-agency-data-sharing-options-12" class="level4" data-number="3.3.3">
<h4 data-number="3.3.3" class="anchored" data-anchor-id="inter-agency-data-sharing-options-12"><span class="header-section-number">3.3.3</span> 3. Inter-Agency Data Sharing (Options 1–2)</h4>
<p><strong>Implementation:</strong></p>
<ul>
<li>Formalize Memoranda of Understanding (MOUs) between:
<ul>
<li>NICD ↔︎ NHLS (laboratory data sharing)</li>
<li>NICD ↔︎ PIH (clinical toxicology data)</li>
<li>NICD ↔︎ DALRRD (pesticide registration and use data)</li>
<li>NICD ↔︎ SAPS (forensic toxicology for intentional poisonings)</li>
</ul></li>
<li>Establish <strong>data governance framework</strong>:
<ul>
<li>What data are shared (minimum dataset)</li>
<li>How often (weekly, monthly, on-demand)</li>
<li>Privacy safeguards (de-identification, access controls)</li>
</ul></li>
</ul>
<p><strong>Legal basis:</strong> Section 90 of the National Health Act (2003) allows inter-agency sharing for public health purposes</p>
<p><strong>Cost:</strong> ~R80,000/year (legal review, MOU development, ongoing liaison)</p>
</section>
<section id="hotspot-detection-algorithm" class="level4" data-number="3.3.4">
<h4 data-number="3.3.4" class="anchored" data-anchor-id="hotspot-detection-algorithm"><span class="header-section-number">3.3.4</span> 4. Hotspot Detection Algorithm</h4>
<p><strong>Method:</strong></p>
<p>Use <strong>space-time permutation scan statistic</strong> (SaTScan software) to detect clusters of:</p>
<ul>
<li>Higher-than-expected case counts</li>
<li>In defined geographic areas (district or sub-district level)</li>
<li>Within defined time windows (2-week rolling window)</li>
</ul>
<p><strong>Implementation:</strong></p>
<ul>
<li>Run weekly on aggregated case data (NMC + BChE auto-notifications + PIH reports)</li>
<li>Generate alerts when:
<ul>
<li>Relative risk &gt; 2.0 (cluster has 2× expected cases)</li>
<li>P-value &lt; 0.05</li>
<li>Cluster includes ≥3 cases</li>
</ul></li>
</ul>
<p><strong>Response protocol:</strong></p>
<ol type="1">
<li>Alert sent to provincial surveillance officer</li>
<li>Officer reviews cluster for plausibility (ruling out data artifacts)</li>
<li>If plausible, initiate field investigation within <strong>72 hours</strong></li>
</ol>
<p><strong>Cost:</strong> Included in Option 5 (~R40,000/year for analyst time)</p>
</section>
</section>
</section>
<section id="implementation-roadmap" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="implementation-roadmap"><span class="header-section-number">4</span> Implementation Roadmap</h2>
<section id="phase-1-pilot-months-16" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="phase-1-pilot-months-16"><span class="header-section-number">4.1</span> Phase 1: Pilot (Months 1–6)</h3>
<p><strong>Pilot provinces:</strong> Gauteng, Western Cape, KwaZulu-Natal</p>
<p><strong>Activities:</strong></p>
<ol type="1">
<li>Configure NHLS auto-notifications for pilot provinces</li>
<li>Establish PIH quarterly reporting workflow</li>
<li>Train provincial surveillance officers on hotspot response</li>
<li>Develop standard operating procedures (SOPs)</li>
</ol>
<p><strong>Milestones:</strong></p>
<ul>
<li>Month 2: First auto-notification sent</li>
<li>Month 3: First PIH quarterly report delivered</li>
<li>Month 4: First cluster alert (if any)</li>
<li>Month 6: Pilot evaluation and refinement</li>
</ul>
</section>
<section id="phase-2-national-rollout-months-712" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="phase-2-national-rollout-months-712"><span class="header-section-number">4.2</span> Phase 2: National Rollout (Months 7–12)</h3>
<p><strong>Activities:</strong></p>
<ol type="1">
<li>Expand NHLS auto-notifications to all provinces</li>
<li>Finalize MOUs for inter-agency data sharing</li>
<li>Deploy SaTScan algorithm for weekly cluster detection</li>
<li>Conduct national training for provincial teams</li>
</ol>
<p><strong>Milestones:</strong></p>
<ul>
<li>Month 9: All provinces receiving auto-notifications</li>
<li>Month 10: First national clustering analysis</li>
<li>Month 12: System fully operational</li>
</ul>
</section>
<section id="phase-3-evaluation-months-1324" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="phase-3-evaluation-months-1324"><span class="header-section-number">4.3</span> Phase 3: Evaluation (Months 13–24)</h3>
<p><strong>Metrics:</strong></p>
<ol type="1">
<li><strong>Timeliness</strong>: Median time from exposure to notification</li>
<li><strong>Completeness</strong>: % of severe BChE inhibitions with corresponding NMC notifications</li>
<li><strong>Sensitivity</strong>: % of known outbreaks detected by cluster algorithm</li>
<li><strong>Response</strong>: % of clusters investigated within 72 hours</li>
<li><strong>Impact</strong>: Change in hospitalization rates in hotspot areas</li>
</ol>
</section>
</section>
<section id="governance-and-oversight" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="governance-and-oversight"><span class="header-section-number">5</span> Governance and Oversight</h2>
<section id="roles-and-responsibilities" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="roles-and-responsibilities"><span class="header-section-number">5.1</span> Roles and Responsibilities</h3>
<table class="table-striped caption-top table">
<caption>Agency roles in the proposed framework</caption>
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Agency</th>
<th style="text-align: left;">Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>NICD</strong></td>
<td style="text-align: left;">Lead surveillance agency; cluster detection; national coordination</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>NHLS</strong></td>
<td style="text-align: left;">Laboratory testing; auto-notification configuration; quality assurance</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>PIH</strong></td>
<td style="text-align: left;">Clinical toxicology advice; quarterly reporting</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Provincial DoH</strong></td>
<td style="text-align: left;">Field investigation; source control; environmental sampling</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>DALRRD</strong></td>
<td style="text-align: left;">Pesticide registration data; agricultural extension liaison</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>SAPS Forensics</strong></td>
<td style="text-align: left;">Intentional poisoning investigations; evidence collection</td>
</tr>
</tbody>
</table>
</section>
<section id="coordination-mechanisms" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="coordination-mechanisms"><span class="header-section-number">5.2</span> Coordination Mechanisms</h3>
<ol type="1">
<li><strong>Quarterly steering committee meetings</strong> (NICD, NHLS, PIH, provincial representatives)</li>
<li><strong>Monthly technical working group calls</strong> (analysts and IT staff)</li>
<li><strong>Annual review and planning workshop</strong></li>
</ol>
</section>
</section>
<section id="budget-summary" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="budget-summary"><span class="header-section-number">6</span> Budget Summary</h2>
<table class="table-striped table-hover caption-top table">
<caption>Estimated annual costs for integrated surveillance framework</caption>
<colgroup>
<col style="width: 29%">
<col style="width: 51%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: right;">Annual Cost (ZAR)</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NHLS auto-notifications</td>
<td style="text-align: right;">55,000</td>
<td style="text-align: left;">IT staff time for LIS configuration</td>
</tr>
<tr class="even">
<td style="text-align: left;">PIH quarterly reports</td>
<td style="text-align: right;">62,000</td>
<td style="text-align: left;">Analyst time for data extraction</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inter-agency MOUs</td>
<td style="text-align: right;">80,000</td>
<td style="text-align: left;">Legal review and liaison</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster detection</td>
<td style="text-align: right;">40,000</td>
<td style="text-align: left;">Analyst time for SaTScan runs</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total (Full Package)</strong></td>
<td style="text-align: right;"><strong>237,000</strong></td>
<td style="text-align: left;"><strong>All four options combined</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="limitations-and-risks" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="limitations-and-risks"><span class="header-section-number">7</span> Limitations and Risks</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Key Assumptions
</div>
</div>
<div class="callout-body-container callout-body">
<p>This framework assumes:</p>
<ol type="1">
<li><strong>NHLS LIS can be configured</strong> for auto-notifications (confirmed as technically feasible)</li>
<li><strong>PIH has capacity</strong> to generate quarterly reports (requires dedicated analyst time)</li>
<li><strong>Provincial teams have resources</strong> for field investigations (may require additional funding)</li>
<li><strong>Legal basis is sufficient</strong> — no new legislation required (confirmed by legal review)</li>
</ol>
<p><strong>Risks:</strong></p>
<ul>
<li><strong>Low uptake of BChE testing</strong>: If clinicians don’t order tests, laboratory triggers won’t fire</li>
<li><strong>Data quality issues</strong>: Incomplete or incorrect demographic data may hinder hotspot detection</li>
<li><strong>Response capacity constraints</strong>: Provincial teams may lack vehicles, sampling equipment, or staff time</li>
</ul>
</div>
</div>
</section>
<section id="next-steps" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="next-steps"><span class="header-section-number">8</span> Next Steps</h2>
<ol type="1">
<li><strong>Secure funding</strong> for pilot phase (~R120,000 for 6 months)</li>
<li><strong>Finalize MOUs</strong> with NHLS and PIH (Month 1)</li>
<li><strong>Configure NHLS auto-notifications</strong> for pilot provinces (Months 1–2)</li>
<li><strong>Train provincial surveillance officers</strong> (Month 2)</li>
<li><strong>Launch pilot</strong> (Month 3)</li>
<li><strong>Evaluate and refine</strong> (Month 6)</li>
</ol>
<hr>
</section>
<section id="references" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="references"><span class="header-section-number">9</span> References</h2>
<ol type="1">
<li>National Institute for Communicable Diseases. <em>National Notifiable Medical Conditions Surveillance System Annual Report 2020–2024.</em></li>
<li>NHLS Laboratory Information Services. <em>Butyrylcholinesterase Testing Data 2020–2024.</em></li>
<li>Red Cross War Memorial Children’s Hospital. <em>Poisons Information Helpline Annual Report 2019.</em></li>
<li>Kulldorff M. <em>SaTScan User Guide for Version 10.0.</em> 2021.</li>
<li>National Health Act No.&nbsp;61 of 2003, Section 90 (Inter-Agency Data Sharing for Public Health).</li>
</ol>
<hr>
<div class="footer-cta">
<p><strong>Download the full concept note:</strong> <a href="../Pesticide_Poisoning_Surveillance_Concept_Note_DRAFT_3_11082025_LL_BB05092025.docx">Pesticide_Poisoning_Surveillance_Concept_Note_DRAFT_3.docx</a></p>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:http:|https:)\/\/(?:[^\/]*\.)?your-site-url\.com|^(?!http)");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Technical Appendix D — Sentinel Toxicology"</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Concept note for live-patient chemical-toxicology testing (Option S3)"</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "D2P Project Team"</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2025-08-05"</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="an">date-modified:</span><span class="co"> today</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [surveillance, framework, concept-note, technical-appendix]</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="fu">## Where this appendix fits</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>This appendix is the **quantitative concept note** for the live-patient chemical-toxicology investment (**Option S3**) referenced in the [Surveillance brief](surveillance_policy.qmd). It is the only one of the three active surveillance options that **creates a new capability** — NHLS currently performs qualitative/quantitative pesticide assays only on post-mortem specimens. Pilot costing is anchored in canonical CSV rows <span class="in">`c_option6_pilot_year1`</span> (R1.2m), <span class="in">`c_option6_full_5site_annual`</span> (R3.625m), <span class="in">`c_gcms_screen_per_specimen`</span> (R2,500), and <span class="in">`c_clinical_battery_per_patient`</span> (R1,500).</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>**Sister appendices:** <span class="co">[</span><span class="ot">A — Surveillance decision analysis</span><span class="co">](../analysis_report_v2.qmd)</span> · <span class="co">[</span><span class="ot">B — Coordination model</span><span class="co">](../technical_appendix_coordination.qmd)</span> · <span class="co">[</span><span class="ot">C — Terbufos bracketed estimate</span><span class="co">](../technical_appendix_terbufos.qmd)</span>.</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="fu">## Executive Summary</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>This concept note outlines a comprehensive framework for improving pesticide poisoning surveillance in South Africa. Building on lessons learned from the National Notifiable Medical Conditions (NMC) system, NHLS laboratory data, and the Poisons Information Helpline, we propose an **integrated surveillance approach** that:</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Links existing data streams** without creating new parallel systems</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Automates notification workflows** to reduce reporting delays</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Enables hotspot detection** through spatial and temporal clustering analysis</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Supports rapid public health response** via clear escalation protocols</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="fu">## Status</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>This is a **DRAFT** concept note (Version 3, dated 11 August 2025). The framework is designed to be piloted in 2–3 provinces before national rollout.</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a><span class="fu">## Background: The Surveillance Gap</span></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a><span class="fu">### Current System Architecture</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>South Africa has three parallel data sources for pesticide poisoning, but they operate independently:</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a><span class="in">```{mermaid}</span></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>%%| label: fig-current-<span class="fu">system</span></span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>%%| fig-cap: <span class="ot">"</span><span class="st">Current (fragmented) surveillance architecture. NICD is the de facto source-of-truth for case notifications. Notifications on the NMC platform trigger an SMS to the local EHP (mandated to investigate) but the investigation outcome is not recorded back on NMC. EHP→DALRRD referral is informal and likewise unrecorded. NHLS holds two distinct laboratory streams — BChE (live patients, 1,779/yr severe from 10,626 tests in 2023) and Chemical Toxicology (post-mortem only — not yet done on live patients) — neither of which feeds NICD in a structured way. PIH consultations are not captured against a minimum viable dataset.</span><span class="ot">"</span></span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>    A[Healthcare Facility&lt;br/&gt;Clinician / PHO] --&gt;|NMC notification| E[(<span class="ot">"</span><span class="st">NICD / NMC&lt;br/&gt;&lt;b&gt;Source of truth&lt;/b&gt;</span><span class="ot">"</span>)]</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>    A --&gt; N[NHLS Laboratory]</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>    subgraph N[NHLS Laboratory]</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>        direction TB</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>        C1[BChE Assay&lt;br/&gt;<span class="dv">1</span>,<span class="dv">779</span> severe/year&lt;br/&gt;<span class="dv">10</span>,<span class="dv">626</span> tests <span class="dv">2023</span>&lt;br/&gt;&lt;i&gt;Live patients&lt;/i&gt;]</span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>        C2[Chemical Toxicology&lt;br/&gt;&lt;i&gt;Post-mortem only —&lt;br/&gt;<span class="ot">not</span> yet done on&lt;br/&gt;live patients&lt;/i&gt;]</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>    end</span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>    A --&gt; D[PIH Consultation&lt;br/&gt;~<span class="dv">1</span>,<span class="dv">158</span> clinician calls/yr&lt;br/&gt;&lt;i&gt;No minimum dataset&lt;/i&gt;]</span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a>    E --&gt;|SMS notification| H[Local EHP&lt;br/&gt;&lt;i&gt;mandated to&lt;br/&gt;investigate&lt;/i&gt;]</span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a>    H -.Investigation NOT&lt;br/&gt;recorded on NMC.<span class="ot">-x</span> E</span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>    H -.Informal referral.-&gt; I[DALRRD&lt;br/&gt;&lt;i&gt;Pesticide Registrar /&lt;br/&gt;Inspectorate&lt;/i&gt;]</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a>    H -.Referral NOT&lt;br/&gt;recorded on NMC.<span class="ot">-x</span> E</span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a>    I -.Feedback to EHP&lt;br/&gt;at best.-&gt; H</span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a>    I -.x No feedback to NMC.<span class="ot">-x</span> E</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a>    C1 -.No structured feed.-&gt; E</span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a>    C2 -.x Not available <span class="cf">for</span>&lt;br/&gt;live-patient surveillance.<span class="ot">-x</span> E</span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a>    D -.No minimum viable&lt;br/&gt;dataset <span class="fu">defined</span>.-&gt; E</span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a>    style E fill:<span class="co">#9f9,stroke:#060,stroke-width:2px</span></span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a>    style A fill:<span class="co">#fde,stroke:#333</span></span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a>    style C1 fill:<span class="co">#bbf,stroke:#333</span></span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a>    style C2 fill:<span class="co">#ffd9b3,stroke:#cc8800,stroke-dasharray: 5 5</span></span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a>    style D fill:<span class="co">#bfb,stroke:#333</span></span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a>    style H fill:<span class="co">#ffd,stroke:#333</span></span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a>    style I fill:<span class="co">#fdd,stroke:#cc0000,stroke-dasharray: 5 5</span></span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-81"><a href="#cb3-81" aria-hidden="true" tabindex="-1"></a>**What this diagram shows.** Five gaps in the current state:</span>
<span id="cb3-82"><a href="#cb3-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-83"><a href="#cb3-83" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**NICD/NMC is the source of truth** for case notifications but receives only the clinician-completed NMC stream (~1,013/year, 2023) — a fraction of the true burden.</span>
<span id="cb3-84"><a href="#cb3-84" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**The NHLS laboratory holds two distinct streams**: (a) **BChE assays** on live patients (10,626 tests/year in 2023; 1,779 severe results, capability exists) and (b) **Chemical toxicology** — qualitative/quantitative pesticide assays which **NHLS currently performs post-mortem only**. Live-patient chemical toxicology is not yet available (see <span class="co">[</span><span class="ot">Component 6</span><span class="co">](#sec-component-6)</span>).</span>
<span id="cb3-85"><a href="#cb3-85" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Neither NHLS stream feeds NICD in a structured way.** BChE has no automated notification; chemical toxicology is not yet generated on living patients at all.</span>
<span id="cb3-86"><a href="#cb3-86" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**The EHP arm exists but does not close the loop.** When an NMC notification is filed, an SMS reaches the local EHP, who is mandated to investigate — but neither the investigation outcome nor the informal DALRRD referral is recorded back on NMC, and DALRRD's regulatory action (if any) is fed back to the EHP at best, never to NICD or the clinician.</span>
<span id="cb3-87"><a href="#cb3-87" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**PIH consultations are not captured against a minimum viable dataset**, so the ~1,158 clinician-initiated calls/year (2023) cannot be aggregated, geocoded, or matched to NICD cases.</span>
<span id="cb3-88"><a href="#cb3-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-89"><a href="#cb3-89" aria-hidden="true" tabindex="-1"></a><span class="fu">### Missed Opportunities</span></span>
<span id="cb3-90"><a href="#cb3-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-91"><a href="#cb3-91" aria-hidden="true" tabindex="-1"></a>From 2020–2024:</span>
<span id="cb3-92"><a href="#cb3-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-93"><a href="#cb3-93" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**~3,450 NMC notifications** were filed, but at least **~10,000 severe BChE inhibitions** were detected in NHLS labs</span>
<span id="cb3-94"><a href="#cb3-94" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Gap of ~6,550 cases** that should have triggered public health investigation</span>
<span id="cb3-95"><a href="#cb3-95" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**No clustering analysis** to identify hotspots (e.g., contaminated food sources, illegal pesticide sales)</span>
<span id="cb3-96"><a href="#cb3-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-97"><a href="#cb3-97" aria-hidden="true" tabindex="-1"></a><span class="fu">## Proposed Framework</span></span>
<span id="cb3-98"><a href="#cb3-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-99"><a href="#cb3-99" aria-hidden="true" tabindex="-1"></a><span class="fu">### Design Principles</span></span>
<span id="cb3-100"><a href="#cb3-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-101"><a href="#cb3-101" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Integration over duplication**: Link existing systems rather than building new infrastructure</span>
<span id="cb3-102"><a href="#cb3-102" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Automation over manual reporting**: Use laboratory triggers and structured data flows</span>
<span id="cb3-103"><a href="#cb3-103" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Timeliness over completeness**: Prioritize rapid detection for actionable hotspots</span>
<span id="cb3-104"><a href="#cb3-104" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Scalability**: Start with pilot provinces, expand based on evidence</span>
<span id="cb3-105"><a href="#cb3-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-106"><a href="#cb3-106" aria-hidden="true" tabindex="-1"></a><span class="fu">### System Architecture</span></span>
<span id="cb3-107"><a href="#cb3-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-110"><a href="#cb3-110" aria-hidden="true" tabindex="-1"></a><span class="in">```{mermaid}</span></span>
<span id="cb3-111"><a href="#cb3-111" aria-hidden="true" tabindex="-1"></a>%%| label: fig-proposed-<span class="fu">system</span></span>
<span id="cb3-112"><a href="#cb3-112" aria-hidden="true" tabindex="-1"></a>%%| fig-cap: <span class="ot">"</span><span class="st">Proposed integrated surveillance architecture</span><span class="ot">"</span></span>
<span id="cb3-113"><a href="#cb3-113" aria-hidden="true" tabindex="-1"></a>flowchart TB</span>
<span id="cb3-114"><a href="#cb3-114" aria-hidden="true" tabindex="-1"></a>    A[Healthcare Facility] --&gt; B[Clinician suspects poisoning]</span>
<span id="cb3-115"><a href="#cb3-115" aria-hidden="true" tabindex="-1"></a>    B --&gt; C{BChE test ordered?}</span>
<span id="cb3-116"><a href="#cb3-116" aria-hidden="true" tabindex="-1"></a>    C --&gt;|Yes| D[NHLS Laboratory]</span>
<span id="cb3-117"><a href="#cb3-117" aria-hidden="true" tabindex="-1"></a>    C --&gt;|No| E[Clinical diagnosis only]</span>
<span id="cb3-118"><a href="#cb3-118" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-119"><a href="#cb3-119" aria-hidden="true" tabindex="-1"></a>    D --&gt; F{BChE &lt; <span class="dv">50</span>% normal?}</span>
<span id="cb3-120"><a href="#cb3-120" aria-hidden="true" tabindex="-1"></a>    F --&gt;|Yes - Severe| G[Auto-notify NICD]</span>
<span id="cb3-121"><a href="#cb3-121" aria-hidden="true" tabindex="-1"></a>    F --&gt;|No| H[Store result]</span>
<span id="cb3-122"><a href="#cb3-122" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-123"><a href="#cb3-123" aria-hidden="true" tabindex="-1"></a>    E --&gt; I[Manual NMC notification]</span>
<span id="cb3-124"><a href="#cb3-124" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-125"><a href="#cb3-125" aria-hidden="true" tabindex="-1"></a>    G --&gt; J[NICD Surveillance Unit]</span>
<span id="cb3-126"><a href="#cb3-126" aria-hidden="true" tabindex="-1"></a>    I --&gt; J</span>
<span id="cb3-127"><a href="#cb3-127" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-128"><a href="#cb3-128" aria-hidden="true" tabindex="-1"></a>    B --&gt; K[Call PIH <span class="cf">for</span> advice]</span>
<span id="cb3-129"><a href="#cb3-129" aria-hidden="true" tabindex="-1"></a>    K --&gt; L[PIH records case]</span>
<span id="cb3-130"><a href="#cb3-130" aria-hidden="true" tabindex="-1"></a>    L --&gt; M[Quarterly summary to NICD]</span>
<span id="cb3-131"><a href="#cb3-131" aria-hidden="true" tabindex="-1"></a>    M --&gt; J</span>
<span id="cb3-132"><a href="#cb3-132" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-133"><a href="#cb3-133" aria-hidden="true" tabindex="-1"></a>    J --&gt; N{Cluster detected?}</span>
<span id="cb3-134"><a href="#cb3-134" aria-hidden="true" tabindex="-1"></a>    N --&gt;|Yes| O[Alert provincial team]</span>
<span id="cb3-135"><a href="#cb3-135" aria-hidden="true" tabindex="-1"></a>    N --&gt;|No| P[Routine monitoring]</span>
<span id="cb3-136"><a href="#cb3-136" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-137"><a href="#cb3-137" aria-hidden="true" tabindex="-1"></a>    O --&gt; Q[Field investigation]</span>
<span id="cb3-138"><a href="#cb3-138" aria-hidden="true" tabindex="-1"></a>    Q --&gt; R[Environmental sampling]</span>
<span id="cb3-139"><a href="#cb3-139" aria-hidden="true" tabindex="-1"></a>    Q --&gt; S[Source control]</span>
<span id="cb3-140"><a href="#cb3-140" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-141"><a href="#cb3-141" aria-hidden="true" tabindex="-1"></a>    style G fill:<span class="co">#ff9,stroke:#333</span></span>
<span id="cb3-142"><a href="#cb3-142" aria-hidden="true" tabindex="-1"></a>    style J fill:<span class="co">#9f9,stroke:#333</span></span>
<span id="cb3-143"><a href="#cb3-143" aria-hidden="true" tabindex="-1"></a>    style O fill:<span class="co">#f99,stroke:#333</span></span>
<span id="cb3-144"><a href="#cb3-144" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-145"><a href="#cb3-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-146"><a href="#cb3-146" aria-hidden="true" tabindex="-1"></a><span class="fu">### Key Components</span></span>
<span id="cb3-147"><a href="#cb3-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-148"><a href="#cb3-148" aria-hidden="true" tabindex="-1"></a><span class="fu">#### 1. Laboratory-Triggered Surveillance (Option 3)</span></span>
<span id="cb3-149"><a href="#cb3-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-150"><a href="#cb3-150" aria-hidden="true" tabindex="-1"></a>**Implementation:**</span>
<span id="cb3-151"><a href="#cb3-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-152"><a href="#cb3-152" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Configure NHLS Laboratory Information System (LIS) to flag BChE results &lt; 50% of normal</span>
<span id="cb3-153"><a href="#cb3-153" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Auto-generate notification to NICD with:</span>
<span id="cb3-154"><a href="#cb3-154" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Patient demographics (age, sex, facility)</span>
<span id="cb3-155"><a href="#cb3-155" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>BChE value and normal range</span>
<span id="cb3-156"><a href="#cb3-156" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Test date and time</span>
<span id="cb3-157"><a href="#cb3-157" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Notification sent within **24 hours** of result validation</span>
<span id="cb3-158"><a href="#cb3-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-159"><a href="#cb3-159" aria-hidden="true" tabindex="-1"></a>**Data flow:**</span>
<span id="cb3-160"><a href="#cb3-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-161"><a href="#cb3-161" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-162"><a href="#cb3-162" aria-hidden="true" tabindex="-1"></a><span class="in">NHLS LIS → HL7 message → NICD middleware → NMC database → Surveillance dashboard</span></span>
<span id="cb3-163"><a href="#cb3-163" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-164"><a href="#cb3-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-165"><a href="#cb3-165" aria-hidden="true" tabindex="-1"></a>**Cost:** ~R55,000/year (mostly IT staff time for configuration)</span>
<span id="cb3-166"><a href="#cb3-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-167"><a href="#cb3-167" aria-hidden="true" tabindex="-1"></a><span class="fu">#### 2. Poisons Information Helpline Integration (Option 4)</span></span>
<span id="cb3-168"><a href="#cb3-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-169"><a href="#cb3-169" aria-hidden="true" tabindex="-1"></a>**Implementation:**</span>
<span id="cb3-170"><a href="#cb3-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-171"><a href="#cb3-171" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>PIH generates **quarterly reports** summarizing:</span>
<span id="cb3-172"><a href="#cb3-172" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Total pesticide-related calls</span>
<span id="cb3-173"><a href="#cb3-173" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Age/sex distribution</span>
<span id="cb3-174"><a href="#cb3-174" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Geographic distribution (by referring facility)</span>
<span id="cb3-175"><a href="#cb3-175" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Severity classification (minor, moderate, severe)</span>
<span id="cb3-176"><a href="#cb3-176" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Suspected pesticide type</span>
<span id="cb3-177"><a href="#cb3-177" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Reports sent to NICD for temporal trend analysis</span>
<span id="cb3-178"><a href="#cb3-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-179"><a href="#cb3-179" aria-hidden="true" tabindex="-1"></a>**Data flow:**</span>
<span id="cb3-180"><a href="#cb3-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-181"><a href="#cb3-181" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-182"><a href="#cb3-182" aria-hidden="true" tabindex="-1"></a><span class="in">PIH call log → Quarterly extraction → Excel/CSV → Email to NICD → Manual review</span></span>
<span id="cb3-183"><a href="#cb3-183" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-184"><a href="#cb3-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-185"><a href="#cb3-185" aria-hidden="true" tabindex="-1"></a>**Cost:** ~R62,000/year (PIH analyst time)</span>
<span id="cb3-186"><a href="#cb3-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-187"><a href="#cb3-187" aria-hidden="true" tabindex="-1"></a><span class="fu">#### 3. Inter-Agency Data Sharing (Options 1–2)</span></span>
<span id="cb3-188"><a href="#cb3-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-189"><a href="#cb3-189" aria-hidden="true" tabindex="-1"></a>**Implementation:**</span>
<span id="cb3-190"><a href="#cb3-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-191"><a href="#cb3-191" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Formalize Memoranda of Understanding (MOUs) between:</span>
<span id="cb3-192"><a href="#cb3-192" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>NICD ↔ NHLS (laboratory data sharing)</span>
<span id="cb3-193"><a href="#cb3-193" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>NICD ↔ PIH (clinical toxicology data)</span>
<span id="cb3-194"><a href="#cb3-194" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>NICD ↔ DALRRD (pesticide registration and use data)</span>
<span id="cb3-195"><a href="#cb3-195" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>NICD ↔ SAPS (forensic toxicology for intentional poisonings)</span>
<span id="cb3-196"><a href="#cb3-196" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Establish **data governance framework**:</span>
<span id="cb3-197"><a href="#cb3-197" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>What data are shared (minimum dataset)</span>
<span id="cb3-198"><a href="#cb3-198" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>How often (weekly, monthly, on-demand)</span>
<span id="cb3-199"><a href="#cb3-199" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Privacy safeguards (de-identification, access controls)</span>
<span id="cb3-200"><a href="#cb3-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-201"><a href="#cb3-201" aria-hidden="true" tabindex="-1"></a>**Legal basis:** Section 90 of the National Health Act (2003) allows inter-agency sharing for public health purposes</span>
<span id="cb3-202"><a href="#cb3-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-203"><a href="#cb3-203" aria-hidden="true" tabindex="-1"></a>**Cost:** ~R80,000/year (legal review, MOU development, ongoing liaison)</span>
<span id="cb3-204"><a href="#cb3-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-205"><a href="#cb3-205" aria-hidden="true" tabindex="-1"></a><span class="fu">#### 4. Hotspot Detection Algorithm</span></span>
<span id="cb3-206"><a href="#cb3-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-207"><a href="#cb3-207" aria-hidden="true" tabindex="-1"></a>**Method:**</span>
<span id="cb3-208"><a href="#cb3-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-209"><a href="#cb3-209" aria-hidden="true" tabindex="-1"></a>Use **space-time permutation scan statistic** (SaTScan software) to detect clusters of:</span>
<span id="cb3-210"><a href="#cb3-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-211"><a href="#cb3-211" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Higher-than-expected case counts</span>
<span id="cb3-212"><a href="#cb3-212" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>In defined geographic areas (district or sub-district level)</span>
<span id="cb3-213"><a href="#cb3-213" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Within defined time windows (2-week rolling window)</span>
<span id="cb3-214"><a href="#cb3-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-215"><a href="#cb3-215" aria-hidden="true" tabindex="-1"></a>**Implementation:**</span>
<span id="cb3-216"><a href="#cb3-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-217"><a href="#cb3-217" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Run weekly on aggregated case data (NMC + BChE auto-notifications + PIH reports)</span>
<span id="cb3-218"><a href="#cb3-218" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Generate alerts when:</span>
<span id="cb3-219"><a href="#cb3-219" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Relative risk &gt; 2.0 (cluster has 2× expected cases)</span>
<span id="cb3-220"><a href="#cb3-220" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>P-value &lt; 0.05</span>
<span id="cb3-221"><a href="#cb3-221" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Cluster includes ≥3 cases</span>
<span id="cb3-222"><a href="#cb3-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-223"><a href="#cb3-223" aria-hidden="true" tabindex="-1"></a>**Response protocol:**</span>
<span id="cb3-224"><a href="#cb3-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-225"><a href="#cb3-225" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Alert sent to provincial surveillance officer</span>
<span id="cb3-226"><a href="#cb3-226" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Officer reviews cluster for plausibility (ruling out data artifacts)</span>
<span id="cb3-227"><a href="#cb3-227" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>If plausible, initiate field investigation within **72 hours**</span>
<span id="cb3-228"><a href="#cb3-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-229"><a href="#cb3-229" aria-hidden="true" tabindex="-1"></a>**Cost:** Included in Option 5 (~R40,000/year for analyst time)</span>
<span id="cb3-230"><a href="#cb3-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-231"><a href="#cb3-231" aria-hidden="true" tabindex="-1"></a><span class="fu">## Implementation Roadmap</span></span>
<span id="cb3-232"><a href="#cb3-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-233"><a href="#cb3-233" aria-hidden="true" tabindex="-1"></a><span class="fu">### Phase 1: Pilot (Months 1–6)</span></span>
<span id="cb3-234"><a href="#cb3-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-235"><a href="#cb3-235" aria-hidden="true" tabindex="-1"></a>**Pilot provinces:** Gauteng, Western Cape, KwaZulu-Natal</span>
<span id="cb3-236"><a href="#cb3-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-237"><a href="#cb3-237" aria-hidden="true" tabindex="-1"></a>**Activities:**</span>
<span id="cb3-238"><a href="#cb3-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-239"><a href="#cb3-239" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Configure NHLS auto-notifications for pilot provinces</span>
<span id="cb3-240"><a href="#cb3-240" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Establish PIH quarterly reporting workflow</span>
<span id="cb3-241"><a href="#cb3-241" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Train provincial surveillance officers on hotspot response</span>
<span id="cb3-242"><a href="#cb3-242" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Develop standard operating procedures (SOPs)</span>
<span id="cb3-243"><a href="#cb3-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-244"><a href="#cb3-244" aria-hidden="true" tabindex="-1"></a>**Milestones:**</span>
<span id="cb3-245"><a href="#cb3-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-246"><a href="#cb3-246" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Month 2: First auto-notification sent</span>
<span id="cb3-247"><a href="#cb3-247" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Month 3: First PIH quarterly report delivered</span>
<span id="cb3-248"><a href="#cb3-248" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Month 4: First cluster alert (if any)</span>
<span id="cb3-249"><a href="#cb3-249" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Month 6: Pilot evaluation and refinement</span>
<span id="cb3-250"><a href="#cb3-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-251"><a href="#cb3-251" aria-hidden="true" tabindex="-1"></a><span class="fu">### Phase 2: National Rollout (Months 7–12)</span></span>
<span id="cb3-252"><a href="#cb3-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-253"><a href="#cb3-253" aria-hidden="true" tabindex="-1"></a>**Activities:**</span>
<span id="cb3-254"><a href="#cb3-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-255"><a href="#cb3-255" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Expand NHLS auto-notifications to all provinces</span>
<span id="cb3-256"><a href="#cb3-256" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Finalize MOUs for inter-agency data sharing</span>
<span id="cb3-257"><a href="#cb3-257" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Deploy SaTScan algorithm for weekly cluster detection</span>
<span id="cb3-258"><a href="#cb3-258" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Conduct national training for provincial teams</span>
<span id="cb3-259"><a href="#cb3-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-260"><a href="#cb3-260" aria-hidden="true" tabindex="-1"></a>**Milestones:**</span>
<span id="cb3-261"><a href="#cb3-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-262"><a href="#cb3-262" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Month 9: All provinces receiving auto-notifications</span>
<span id="cb3-263"><a href="#cb3-263" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Month 10: First national clustering analysis</span>
<span id="cb3-264"><a href="#cb3-264" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Month 12: System fully operational</span>
<span id="cb3-265"><a href="#cb3-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-266"><a href="#cb3-266" aria-hidden="true" tabindex="-1"></a><span class="fu">### Phase 3: Evaluation (Months 13–24)</span></span>
<span id="cb3-267"><a href="#cb3-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-268"><a href="#cb3-268" aria-hidden="true" tabindex="-1"></a>**Metrics:**</span>
<span id="cb3-269"><a href="#cb3-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-270"><a href="#cb3-270" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Timeliness**: Median time from exposure to notification</span>
<span id="cb3-271"><a href="#cb3-271" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Completeness**: % of severe BChE inhibitions with corresponding NMC notifications</span>
<span id="cb3-272"><a href="#cb3-272" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Sensitivity**: % of known outbreaks detected by cluster algorithm</span>
<span id="cb3-273"><a href="#cb3-273" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Response**: % of clusters investigated within 72 hours</span>
<span id="cb3-274"><a href="#cb3-274" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Impact**: Change in hospitalization rates in hotspot areas</span>
<span id="cb3-275"><a href="#cb3-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-276"><a href="#cb3-276" aria-hidden="true" tabindex="-1"></a><span class="fu">## Governance and Oversight</span></span>
<span id="cb3-277"><a href="#cb3-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-278"><a href="#cb3-278" aria-hidden="true" tabindex="-1"></a><span class="fu">### Roles and Responsibilities</span></span>
<span id="cb3-279"><a href="#cb3-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-280"><a href="#cb3-280" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Agency <span class="pp">|</span> Role <span class="pp">|</span></span>
<span id="cb3-281"><a href="#cb3-281" aria-hidden="true" tabindex="-1"></a><span class="pp">|:-------|:-----|</span></span>
<span id="cb3-282"><a href="#cb3-282" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **NICD** <span class="pp">|</span> Lead surveillance agency; cluster detection; national coordination <span class="pp">|</span></span>
<span id="cb3-283"><a href="#cb3-283" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **NHLS** <span class="pp">|</span> Laboratory testing; auto-notification configuration; quality assurance <span class="pp">|</span></span>
<span id="cb3-284"><a href="#cb3-284" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **PIH** <span class="pp">|</span> Clinical toxicology advice; quarterly reporting <span class="pp">|</span></span>
<span id="cb3-285"><a href="#cb3-285" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Provincial DoH** <span class="pp">|</span> Field investigation; source control; environmental sampling <span class="pp">|</span></span>
<span id="cb3-286"><a href="#cb3-286" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **DALRRD** <span class="pp">|</span> Pesticide registration data; agricultural extension liaison <span class="pp">|</span></span>
<span id="cb3-287"><a href="#cb3-287" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **SAPS Forensics** <span class="pp">|</span> Intentional poisoning investigations; evidence collection <span class="pp">|</span></span>
<span id="cb3-288"><a href="#cb3-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-289"><a href="#cb3-289" aria-hidden="true" tabindex="-1"></a>: Agency roles in the proposed framework {.striped}</span>
<span id="cb3-290"><a href="#cb3-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-291"><a href="#cb3-291" aria-hidden="true" tabindex="-1"></a><span class="fu">### Coordination Mechanisms</span></span>
<span id="cb3-292"><a href="#cb3-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-293"><a href="#cb3-293" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Quarterly steering committee meetings** (NICD, NHLS, PIH, provincial representatives)</span>
<span id="cb3-294"><a href="#cb3-294" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Monthly technical working group calls** (analysts and IT staff)</span>
<span id="cb3-295"><a href="#cb3-295" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Annual review and planning workshop**</span>
<span id="cb3-296"><a href="#cb3-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-297"><a href="#cb3-297" aria-hidden="true" tabindex="-1"></a><span class="fu">## Budget Summary</span></span>
<span id="cb3-298"><a href="#cb3-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-299"><a href="#cb3-299" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Component <span class="pp">|</span> Annual Cost (ZAR) <span class="pp">|</span> Notes <span class="pp">|</span></span>
<span id="cb3-300"><a href="#cb3-300" aria-hidden="true" tabindex="-1"></a><span class="pp">|:----------|------------------:|:------|</span></span>
<span id="cb3-301"><a href="#cb3-301" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> NHLS auto-notifications <span class="pp">|</span> 55,000 <span class="pp">|</span> IT staff time for LIS configuration <span class="pp">|</span></span>
<span id="cb3-302"><a href="#cb3-302" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PIH quarterly reports <span class="pp">|</span> 62,000 <span class="pp">|</span> Analyst time for data extraction <span class="pp">|</span></span>
<span id="cb3-303"><a href="#cb3-303" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Inter-agency MOUs <span class="pp">|</span> 80,000 <span class="pp">|</span> Legal review and liaison <span class="pp">|</span></span>
<span id="cb3-304"><a href="#cb3-304" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cluster detection <span class="pp">|</span> 40,000 <span class="pp">|</span> Analyst time for SaTScan runs <span class="pp">|</span></span>
<span id="cb3-305"><a href="#cb3-305" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Total (Full Package)** | **237,000** | **All four options combined** <span class="pp">|</span></span>
<span id="cb3-306"><a href="#cb3-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-307"><a href="#cb3-307" aria-hidden="true" tabindex="-1"></a>: Estimated annual costs for integrated surveillance framework {.striped .hover}</span>
<span id="cb3-308"><a href="#cb3-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-309"><a href="#cb3-309" aria-hidden="true" tabindex="-1"></a><span class="fu">## Limitations and Risks</span></span>
<span id="cb3-310"><a href="#cb3-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-311"><a href="#cb3-311" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning}</span>
<span id="cb3-312"><a href="#cb3-312" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key Assumptions</span></span>
<span id="cb3-313"><a href="#cb3-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-314"><a href="#cb3-314" aria-hidden="true" tabindex="-1"></a>This framework assumes:</span>
<span id="cb3-315"><a href="#cb3-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-316"><a href="#cb3-316" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**NHLS LIS can be configured** for auto-notifications (confirmed as technically feasible)</span>
<span id="cb3-317"><a href="#cb3-317" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**PIH has capacity** to generate quarterly reports (requires dedicated analyst time)</span>
<span id="cb3-318"><a href="#cb3-318" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Provincial teams have resources** for field investigations (may require additional funding)</span>
<span id="cb3-319"><a href="#cb3-319" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Legal basis is sufficient** — no new legislation required (confirmed by legal review)</span>
<span id="cb3-320"><a href="#cb3-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-321"><a href="#cb3-321" aria-hidden="true" tabindex="-1"></a>**Risks:**</span>
<span id="cb3-322"><a href="#cb3-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-323"><a href="#cb3-323" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Low uptake of BChE testing**: If clinicians don't order tests, laboratory triggers won't fire</span>
<span id="cb3-324"><a href="#cb3-324" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Data quality issues**: Incomplete or incorrect demographic data may hinder hotspot detection</span>
<span id="cb3-325"><a href="#cb3-325" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Response capacity constraints**: Provincial teams may lack vehicles, sampling equipment, or staff time</span>
<span id="cb3-326"><a href="#cb3-326" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-327"><a href="#cb3-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-328"><a href="#cb3-328" aria-hidden="true" tabindex="-1"></a><span class="fu">## Next Steps</span></span>
<span id="cb3-329"><a href="#cb3-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-330"><a href="#cb3-330" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Secure funding** for pilot phase (~R120,000 for 6 months)</span>
<span id="cb3-331"><a href="#cb3-331" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Finalize MOUs** with NHLS and PIH (Month 1)</span>
<span id="cb3-332"><a href="#cb3-332" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Configure NHLS auto-notifications** for pilot provinces (Months 1–2)</span>
<span id="cb3-333"><a href="#cb3-333" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Train provincial surveillance officers** (Month 2)</span>
<span id="cb3-334"><a href="#cb3-334" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Launch pilot** (Month 3)</span>
<span id="cb3-335"><a href="#cb3-335" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Evaluate and refine** (Month 6)</span>
<span id="cb3-336"><a href="#cb3-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-337"><a href="#cb3-337" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-338"><a href="#cb3-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-339"><a href="#cb3-339" aria-hidden="true" tabindex="-1"></a><span class="fu">## References</span></span>
<span id="cb3-340"><a href="#cb3-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-341"><a href="#cb3-341" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>National Institute for Communicable Diseases. *National Notifiable Medical Conditions Surveillance System Annual Report 2020–2024.*</span>
<span id="cb3-342"><a href="#cb3-342" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>NHLS Laboratory Information Services. *Butyrylcholinesterase Testing Data 2020–2024.*</span>
<span id="cb3-343"><a href="#cb3-343" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Red Cross War Memorial Children's Hospital. *Poisons Information Helpline Annual Report 2019.*</span>
<span id="cb3-344"><a href="#cb3-344" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Kulldorff M. *SaTScan User Guide for Version 10.0.* 2021.</span>
<span id="cb3-345"><a href="#cb3-345" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>National Health Act No. 61 of 2003, Section 90 (Inter-Agency Data Sharing for Public Health).</span>
<span id="cb3-346"><a href="#cb3-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-347"><a href="#cb3-347" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-348"><a href="#cb3-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-349"><a href="#cb3-349" aria-hidden="true" tabindex="-1"></a>::: {.footer-cta}</span>
<span id="cb3-350"><a href="#cb3-350" aria-hidden="true" tabindex="-1"></a>**Download the full concept note:** <span class="co">[</span><span class="ot">Pesticide_Poisoning_Surveillance_Concept_Note_DRAFT_3.docx</span><span class="co">](../Pesticide_Poisoning_Surveillance_Concept_Note_DRAFT_3_11082025_LL_BB05092025.docx)</span></span>
<span id="cb3-351"><a href="#cb3-351" aria-hidden="true" tabindex="-1"></a>:::</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 D2P Project Team</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="mailto:contact@example.com">
<p>Contact</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>